### ISSUE TITLE
Need help with memory usage on windows

### ISSUE THREAD

**Issue by amirotin** [arvidn/libtorrent#422] opened 2016-01-21 07:19 UTC
Hi.I know that windows is very specific for memory usage, but I have no way to use linux :(
So, what i have - PC with Windows 7 x64, 8Gb memory, drive pool with 8 drives (3TB and 4TB). Internet speed is 100mbit.
I've about 400 torrents different sizes (from 2gb to 20gb per file).
Here are my settings for libtorrent (based on high_performance_seed preset):
```
cache_size = -1 # 8Gb ram devided by 8 = 1gb cache?
disk_io_write_mode = disable_os_cache # on windows it is equal to disable_os_caches_for_aligned_files?
disk_io_read_mode = disable_os_cache # on windows it is equal to disable_os_caches_for_aligned_files?
file_pool_size = 500
use_disk_cache_pool = false
use_read_cache = false
```

With above settings libtorrent still consume lot of memory and finaly i get out of memory error.
there are so many combinations of settings for cache that I am little confused.

**Comment by arvidn** [comment] 2016-01-21 19:44
is this with libtorrent 1.0.x?
would it be possible for you to build with session-stats enabled?
there's also a sysinternals tool that can do coarse grained memory profiling, basically tell you what category different pages are attributed to. I suspect that in this case there may be a lot of disk cache pages (I get the impression that windows attributes disk cache to the process causing it, even though it's volatile). You could take a look at RamMap to get a rough idea of where the usage is coming from: https://technet.microsoft.com/en-us/sysinternals/rammap.aspx

Since you attempt to disable the disk cache, it seem like you're expecting the disk cache to be large. However, if you're using a sufficiently recent version of libtorrent, I wouldn't necessarily make that assumption. That problem used to be caused by FILE_FLAG_RANDOM_ACCESS, which shouldn't be used anymore.

**Comment by amirotin** [comment] 2016-01-22 05:55
It is last release - 1.0.8.
I tryed native python, deluge client (replaced standart libtorrent with yours) and qbittorrent 1.3.3.

Sorry, but i've no chance to build libtorrent by myself.
I know about RAMMap (very useful tool :) ) In all cases i've paged pool about 1gb and very large 'mapped file' section. Active size is about 5gb, standby ~100mb. 

On 'File summary' there is large amount of torrent files that are not seeding at all, but are active.

**Comment by amirotin** [comment] 2016-01-22 06:17
Also when i start hash check - memory doesn't grow. So it is only seeding problem.

**Comment by ruslanfedoseenko** [comment] 2016-01-22 06:31
Here is a blog post on some russian developers community about windows memory management  https://geektimes.ru/post/107637/ . The conclusion from it is that to reduce disk cache usage you shuld call SetThreadPriority with THREAD_MODE_BACKGROUND_BEGIN to make disk cache to have lower priority so it can be purged by system.

**Comment by arvidn** [comment] 2016-03-06 21:29
I have a feeling that the disk-cache-1.1 branch that just landed in RC_1_1 would solve this issue. please re-open if it didn't.

**Closed by arvidn** 2016-03-06 21:29 UTC
