### ISSUE TITLE
passing port 0 (random) causes different interface/IP to have different ports

### ISSUE THREAD

**Issue by ghost** [arvidn/libtorrent#5746] opened 2020-12-15 06:36 UTC
**Please provide the following information**

libtorrent version (or branch):
RC1_2
platform/architecture:
Windows 10 20H2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Passing port 0 causes different interface/IP to have different TCP/UDP ports.

```
Successfully listening on IP: 127.0.0.1, port: UDP/2622
Successfully listening on IP: 127.0.0.1, port: TCP/2622
Successfully listening on IP: 192.168.2.100, port: UDP/2621
Successfully listening on IP: 192.168.2.100, port: TCP/2621
Successfully listening on IP: 192.168.42.88, port: UDP/2618
Successfully listening on IP: 192.168.42.88, port: TCP/2618
```

So now If I want to fetch the port from the alerts to display current active port. It becomes problematic!
i.e- Port gets overwritten with whichever alerts come last...but that may not be the main interface.

**Comment by FranciscoPombal** [comment] 2020-12-15 14:25
Wasn't this already fixed in https://github.com/arvidn/libtorrent/pull/4314 (also see https://github.com/arvidn/libtorrent/pull/4335)? Past discussions: https://github.com/qbittorrent/qBittorrent/issues/12053#issuecomment-589963188 and the ones linked in that comment.

**Comment by arvidn** [comment] 2020-12-15 16:03
this is supposed to have been fixed and have a unit test to secure it..

**Comment by an0n666** [comment] 2020-12-16 03:16
> Wasn't this already fixed in #4314 (also see #4335)? Past discussions: [qbittorrent/qBittorrent#12053 (comment)](https://github.com/qbittorrent/qBittorrent/issues/12053#issuecomment-589963188) and the ones linked in that comment.

What's fixed is that the TCP/UDP ports are the same for each interface. But they're not the same across all interfaces.

**Comment by FranciscoPombal** [comment] 2021-05-05 12:58
> What's fixed is that the TCP/UDP ports are the same for each interface. But they're not the same across all interfaces.

Confirmed. Downstream issue: https://github.com/qbittorrent/qBittorrent/issues/14919

**Comment by arvidn** [comment] 2021-05-05 13:25
does it matter that different ports are picked for different interfaces?
The reason it's important within the same interface (across TCP and UDP) is that we only announce one port, and may be contacted over both TCP, uTP and DHT, so those better use the same port. However, for different interfaces we will look like a different client from the outside, I don't see the benefit of sharing port there.

**Comment by FranciscoPombal** [comment] 2021-05-05 13:27
@arvidn 

> However, for different interfaces we will look like a different client from the outside, I don't see the benefit of sharing port there.

What about in the case of announcing both IPv4 and IPv6 to the same tracker (mulltihome extension)? Wouldn't it be better to announce only one port in that case as well?

**Comment by arvidn** [comment] 2021-05-05 13:33
> What about in the case of announcing both IPv4 and IPv6 to the same tracker (mulltihome extension)? Wouldn't it be better to announce only one port in that case as well?

They will be two separate announces anyway, I don't think it matters that they use different ports.

I suppose there's a risk that some (private) trackers really like to associate those announces with each other and just pick one port. Do we know if trackers have a hard time with that?

**Comment by FranciscoPombal** [comment] 2021-05-05 13:38
@arvidn 

> I suppose there's a risk that some (private) trackers really like to associate those announces with each other and just pick one port. Do we know if trackers have a hard time with that?

I don't know, honestly. I would be inclined to say that most of them (at least the most known ones) are most likely to have their tracker software correctly setup. However, let's ask @an0n666 to be sure.

**Comment by an0n666** [comment] 2021-05-05 13:44
Yes you're right. Some trackers associate announces made from one peer_id and save them against one port. In such cases the tracker would end up sending wrong ports to other peers.
However, the reason I opened the ticket was to address another issue. When we use random ports the frontend application can't display the current active port to the user since there's too many ports active.

**Comment by FranciscoPombal** [comment] 2021-05-05 21:14
@an0n666 

> Yes you're right. Some trackers associate announces made from one peer_id and save them against one port. In such cases the tracker would end up sending wrong ports to other peers.
> However, the reason I opened the ticket was to address another issue. When we use random ports the frontend application can't display the current active port to the user since there's too many ports active.

The thing is, who is in the wrong here, according to the protocol specifications? This could very well be considered a problem on the tracker implementation that should be resolved, not necessarily an issue that warrants "fixing" in libtorrent. If the specification doesn't mandate strongly one way or the other, then I would lean towards libtorrent making things easier for tracker devs if possible. Otherwise, I'd say I'd say the responsibility falls on them.

**Comment by an0n666** [comment] 2021-05-05 22:33
The protocol specification doesn't mention anything regarding ports in a multi homed announce enviroment https://www.bittorrent.org/beps/bep_0007.html.

Anyways, most trackers do not support multi-homed announces the way arvidn wants (accept and store multiple endpoints against a single peer_id and then send them to other peers). Mostly because their software is outdated and they do not bother to fix it or they see it as an unncessary extra load on the server to process announces from multiple endpoints. 
Even if some top notch, latest and greatest tracker supports multi homing, they might not be aware of having to deal with different ports per endpoints. But if you put the responsibility on them, then these things should be documented somewhere in clear text.

**Comment by FranciscoPombal** [comment] 2021-05-05 22:39
@an0n666 

Thanks for the clarification.

> Anyways, most trackers do not support multi-homed announces the way arvidn wants (accept and store multiple endpoints against a single peer_id and then send them to other peers). Mostly because their software is outdated and they do not bother to fix it or they see it as an unncessary extra load on the server to process announces from multiple endpoints.

Well, even though the spec says nothing about it, I'd say it is perfectly reasonable that trackers get updated to behave that way. That settles it for me then - I don't consider this an issue then.

> But if you put the responsibility on them, then these things should be documented somewhere in clear text.

Agreed, good docs are always important. Perhaps even the spec could be updated to suggest this? Something like "(...) the tracker _should_ accept and store multiple endpoints against a single `peer_id` and then send them to other peers (...)".

**Comment by arvidn** [comment] 2021-05-05 23:43
I think it's a stretch to suggest that the port parameter specification is ambiguous. The announce parameters are defined in the original protocol specification (BEP 3) under "trackers", [here](https://github.com/bittorrent/bittorrent.org/blob/master/beps/bep_0003.rst#trackers). Where it says:

> port
>     The port number this peer is listening on. Common behavior is for a downloader to try to listen on port 6881 and if that port is taken try 6882, then 6883, etc. and give up after 6889.

BEP 7, [Announcing](https://github.com/bittorrent/bittorrent.org/blob/master/beps/bep_0007.rst#announcing) section is just talking about which source IPs to use when announcing.

> Each announce should use the corresponding local IP address as the source address of the connection.
> 
> The source address is set on a socket using the bind() call, before connecting.
> 
> This applies to TCP connections, for HTTP and HTTPS trackers, as well as UDP announces, to UDP trackers.
>

**Comment by arvidn** [comment] 2021-05-24 08:16
How do people feel about this issue? I can see arguments both for the current behavior of not tying ports on different interfaces together and the suggested behavior of making all ports the same. Although, I'm leaning toward the current behavior for these reasons:

1. It makes the logic simpler
2. Possibly improved privacy by not tying different IPs to the same client
3. The main reason to use the same port (as I understand it) is to allow a single tracker announce with one port and multiple interfaces. This feature is problematic and should be phased out in my opinion. It should use one announce per interface

**Comment by FranciscoPombal** [comment] 2021-05-24 09:29
@arvidn

After the discussion, I'm OK with the current behavior, and as such I have already closed https://github.com/qbittorrent/qBittorrent/issues/14919.

**Closed** 2021-05-24 11:34 UTC
