### ISSUE TITLE
Some torrents getting stuck on checking_files or checking_resume_data state

### ISSUE THREAD

**Issue by dessalines** [arvidn/libtorrent#169] opened 2015-09-20 14:19 UTC
When starting torrents in seed mode, I sometimes find that they get stuck on `checking_files`, or `checking_resume_data`. 

Its a weird glitch that seems to happen to random torrents; the vast majority are seeding correctly.

Here's more description:
https://github.com/frostwire/frostwire-jlibtorrent/issues/55#issuecomment-141496795

**Comment by sledgehammer999** [comment] 2015-11-04 21:56
There were some qbittorrent users that reported similarly "stuck" torrents in that state but I never followed through with investigating... Those reportes were rare and a while ago.
Sorry for not contributing anything to the debugging of this.

**Comment by tchoulihan** [comment] 2015-11-04 23:03
No problem, let me know if there is something I can do to provide info on what's happening.

**Comment by Falcosc** [comment] 2016-12-26 17:13
@dessalines did you seen this behaviour again on current libtorrent versions? Because we did apply many minor changes to code.

**Comment by dessalines** [comment] 2016-12-27 16:27
I haven't updated the libtorrent for the project I was having the problem on, so I'm not sure.

**Comment by Falcosc** [comment] 2016-12-28 11:00
@dessalines do you want to test it again or should we close the ticket because it is may be already fixed?

**Comment by Falcosc** [comment] 2017-01-10 20:31
@dessalines could you reproduce it? because we can't fix the issue if we are not able to reproduce it or not even able to guess what could cause it.

**Comment by rlueckl** [comment] 2018-04-29 14:58
I just stumbled across this ticker. Regarding the qBittorrent users: the issue still persist and probably has to do with libtorrent (some other Google searches popped up too). See this issue: https://github.com/qbittorrent/qBittorrent/issues/7947

I had this issue with self-made torrents, which I uploaded to a tracker and had to re-download again. The tracker adds some info to the files, changes the tracker URL, etc. So you have to download your torrent and add that one to your client, otherwise you won't be able to seed.

I point the re-downloaded torrent file to my local directory, where it sees that the files are present, and tries to re-check automatically. Then it's stuck in the loop ("checking resume data"). If you remove 1 file from the directory, usually it can finish checking and is stuck at whichever percent. If move back the file to the directory and do a force re-check it'll be stuck in the loop again.

This happens only for newly added torrents for me, which don't need any data to be downloaded. Apparently some others had similar issues by not closing their client properly (killing the process or similar).

**Comment by Seeker2** [comment] 2018-04-29 22:06
Read-only folders or 0-length files may be a cause of the problem due to bugs in qBT and/or libtorrent.

**Comment by rlueckl** [comment] 2018-04-30 05:38
Hi @Seeker2,

my folders aren't read-only and there are no 0-length files in them. I tried different files in different folders and always have this error.

I'm using Windows 7, source folder is on an NTFS partition, no attributes set on the folder and qBittorrent 4.0.4

**Comment by Seeker2** [comment] 2018-05-01 05:13
Any chance some of these files include "strange" characters or symbols in their names?
(I'm grasping for straws here!)

**Comment by rlueckl** [comment] 2018-05-01 15:55
Nope, sorry. :) Pretty basic stuff, like img01.jpg, img02.jpg, etc... Maybe there is an underscore in the name, but I don't think that counts as "strage".

**Comment by Col-blimp** [comment] 2018-05-01 16:17
Can you post a hash of one of the torrents giving the problem?

**Comment by Seeker2** [comment] 2018-05-01 22:09
Does the total path length plus filenames of any of these add up to >250 bytes (characters) in length?

**Comment by rlueckl** [comment] 2018-05-09 17:58
@Col-blimp Sorry, it's a private tracker, I won't be able to post it. Like I wrote, I create the torrent (with qBittorrent), but the tracker doesn't give me a personalized announce URL beforehand. So I add a placeholder, like `http://sometracker.net/announce`. Then, I upload the torrent to the site where it gets automatically processed and the announce URL is changed to a personalized URL (e.g. `http://sometracker.net/somehash/announce`). I have to download this torrent and add it to my client, to begin seeding. While I add the torrent I point it to the already existing directory with the files, so qBittorrent is immediately starting a check -> this is where the loop happens.

@Seeker2 No, the filenames are pretty short, no subdirectories or anything. Something like:
```
folder/
  filename1.mp4
  filename2.mp4
  filename3.mp4
  ...
  filename8.mp4
```

**Comment by Seeker2** [comment] 2018-05-10 14:30
Other than file system permissions issues, I'm completely out of ideas.

**Comment by rlueckl** [comment] 2018-05-11 05:11
I tried to reproduce the error yesterday with qBittorrent 4.0.10, but couldn't. Either it was fixed in qBittorrent (although I didn't see anything relevant in the changelog, and the bug has been there for quite a long time) or I'm doing something different.

I think you can close this issue and if I encounter it again, I'll try to gather more information.

**Closed** 2018-05-11 15:29 UTC

**Comment by BlackLight** [comment] 2019-06-28 23:28
My two cents.

I've bumped into the issue using libtorrent in one of my Python applications. It seems to occur when the method that created the session returns. In my case, I used to create the session in one method and then pass it to another thread for monitoring the transfer status.

```python
ses = libtorrent.session()
transfer = ses.add_torrent({...})
...
def monitor():
    while not transfer.is_finished():
        # do something

threading.Thread(target=monitor).start()
return
```

Note that with the snippet above the issue occurs also when no files have yet been downloaded at all.

Everything works fine instead and the download starts successfully when I run everything in the same method/thread:

```python
ses = libtorrent.session()
transfer = ses.add_torrent({...})
...
while not transfer.is_finished():
        # do something

return
```

My speculation is that it's probably related to some destructor being called on a stack object when the function returns and leaves the session in a "hanging" state, but I haven't investigated enough yet, nor I'm sure whether this is the same scenario reported by other users.

**Comment by arvidn** [comment] 2019-06-29 00:53
well, unless `ses` is a global variable in your example (and iirc you'd have to say `global ses` for it to be), it will go out of scope when you return. the session will be destroyed.

I would expect that any attempt to access the `torrent_handle` after that would just throw an exception. Or does the `monitor` function somehow capture the `ses` object also?
