### ISSUE TITLE
MSVC libtorrent-2.0.0-release unable to compile with boost 1.74

### ISSUE THREAD

**Issue by 5523eeOMEGALUL** [arvidn/libtorrent#5111] opened 2020-09-07 05:51 UTC
libtorrent-2.0.0
MSVC 16.7 x64

2 compile errors (same):
`Error	C2338	Handler buffer not large enough, please increase it`
1. `(compiling source file libtorrent-rasterbar-2.0.0\src\peer_connection.cpp)`
2. `(compiling source file libtorrent-rasterbar-2.0.0\src\session_impl.cpp)`

`libtorrent-rasterbar-2.0.0\include\libtorrent\aux_\allocating_handler.hpp	line 180`

https://github.com/arvidn/libtorrent/blob/v2.0.0/include/libtorrent/aux_/allocating_handler.hpp#L180
not point which part of `peer_connection.cpp` or `session_impl.cpp` assert fail

edit: https://paste.ubuntu.com/p/V8TK76zxZg/

**Comment by arvidn** [comment] 2020-09-07 19:20
Which version of boost are you using?

**Comment by FranciscoPombal** [comment] 2020-09-07 22:07
Cannot reproduce with Boost 1.73.0, by the way. I get a couple of warnings/unnecessary output noise though, I'll open an issue about that later.

**Comment by arvidn** [comment] 2020-09-07 22:17
I have a feeling this a some build configuration that isn't covered by CI.

@5523eeOMEGALUL are you building a release build with debug iterators enabled by any chance? Or some other debug feature?

**Comment by FranciscoPombal** [comment] 2020-09-07 22:27
For reference, I was building with cmake with all default configure options, except `-Dbuild_examples=ON` and `-Dbuild_tools=ON`. Both `Release` and `Debug` build configurations configurations compiled successfully and generated identical warnings.

**Comment by 5523eeOMEGALUL** [comment] 2020-09-07 22:33
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -G "Visual Studio 16 2019" ..`
boost 1.74
not using ninja

**Comment by vktr** [comment] 2020-09-07 22:39
I had a similar error in debug builds only IIRC. I fixed in #4070 and haven't seen it since. Both master and 2.0 has built correctly on Windows since then.

@5523eeOMEGALUL How are you building the generated code?

The simplest way to build with CMake on Windows is this,

```
git clone https://github.com/arvidn/libtorrent
cd libtorrent
git checkout v2.0.0
mkdir build
cd build
cmake ..
cmake --build .
```

Or for Release builds,

```
cmake --build . --config Release
```

This is with MSVC 19.27.29111.

**Comment by 5523eeOMEGALUL** [comment] 2020-09-07 22:44
my command is in previous post
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -G "Visual Studio 16 2019" ..`

**Comment by vktr** [comment] 2020-09-07 22:50
> 
> 
> my command is in previous post
> `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -G "Visual Studio 16 2019" ..`

Works here. Although I'm using Boost 1.73 and not 1.74.

**Comment by FranciscoPombal** [comment] 2020-09-07 22:53
@5523eeOMEGALUL I tried again with `-DCMAKE_CXX_STANDARD=17`. Still able to compile fine, though I do get some different warnings than previously when I didn't force any `-DCMAKE_CXX_STANDARD`.

**Comment by 5523eeOMEGALUL** [comment] 2020-09-07 23:13
using boost 1.73
` Build: 3 succeeded, 0 failed`

**Comment by vktr** [comment] 2020-09-07 23:21
@5523eeOMEGALUL Is it only debug builds that fail with Boost 1.74? Or release builds as well? I can do some more testing tomorrow, perhaps we need to do a similar patch as #4070. Reasonable @arvidn?

**Comment by 5523eeOMEGALUL** [comment] 2020-09-07 23:24
not have any debug builds, only https://github.com/arvidn/libtorrent/releases/tag/2.0
`-DCMAKE_BUILD_TYPE=Release` if you reference MSVC solution build type

**Comment by vktr** [comment] 2020-09-07 23:30
Specifying `-DCMAKE_BUILD_TYPE=Release` will not make MSVC build in release mode - it it is only meaningful for single-configuration generators (https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html)

To build in release mode with MSVC you need to either use `cmake --build . --config Release` or `msbuild torrent-rasterbar.sln /t:Build /p:Configuration=Release` or fire up the ol' studio and choose Release in the dropdown.

**Comment by 5523eeOMEGALUL** [comment] 2020-09-07 23:41
did set it in MSVS gui

**Comment by arvidn** [comment] 2020-09-08 11:13
could you try this patch? https://github.com/arvidn/libtorrent/pull/5116

I think the reason it works for some people is that they are building 32 bit builds (which is not ideal).

The cmake build really should be defaulting to 64 bits\

**Comment by FranciscoPombal** [comment] 2020-09-08 11:27
> The cmake build really should be defaulting to 64 bits\

That depends on the host system, the installed toolchains and their configuration.

@5523eeOMEGALUL 

To make sure you're doing a x64 build, use `-G "Visual Studio 16 2019" -A x64`

**Comment by 5523eeOMEGALUL** [comment] 2020-09-08 12:52
> could you try this patch? #5116
had two of same errors for different files
1 error gone 
1 left
`Error	C2338	Handler buffer not large enough, please increase it`
`(compiling source file libtorrent-rasterbar-2.0.0\src\peer_connection.cpp)`
`torrent-rasterbar	libtorrent-rasterbar-2.0.0\include\libtorrent\aux_\allocating_handler.hpp	186	`

https://github.com/arvidn/libtorrent/pull/5116/commits/36694578c1ebd107e30365b2a3964c0786dd08d9
#ifndef NDEBUG
#if _HAS_ITERATOR_DEBUGGING > 0
changed nothing, NDEBUG was defined

**Comment by arvidn** [comment] 2020-09-08 13:13
@5523eeOMEGALUL There's a part in the error message that looks like this:

```
libtorrent::aux::assert_message<libtorrent::aux::required_size<248>,libtorrent::aux::available_size<224>,libtorrent::aux::write_handler>' being compiled
```

Which says how large the buffer needs to be, how large it is, and which handler the buffer is for.

Can you tell me what it says in your remaining error message? I can no longer reproduce this with my patch, testing all combinations of 32/64 bits, debug/release and C++14/17

**Comment by 5523eeOMEGALUL** [comment] 2020-09-08 13:29
fails with boost 1.74
https://paste.ubuntu.com/p/jVt3fCkk6g/
++14/17/x32 unrelated

`'libtorrent::aux::assert_message<libtorrent::aux::required_size<272>,libtorrent::aux::available_size<252>,libtorrent::aux::write_handler>' being compiled (compiling source file libtorrent-rasterbar-2.0.0\src\peer_connection.cpp)`
`torrent-rasterbar	libtorrent-rasterbar-2.0.0\include\libtorrent\aux_\allocating_handler.hpp	209	`

https://paste.ubuntu.com/p/bQtWfyhNkF/

**Comment by arvidn** [comment] 2020-09-08 13:48
those warnings refer to the *standard library* using deprecated features. If you interpret it as libtorrent using features deprecated in C++17, please explain what it is specifically.

**Comment by 5523eeOMEGALUL** [comment] 2020-09-08 13:57
forgot to add `/Zc:__cplusplus`
deprecated warnings gone

**Comment by arvidn** [comment] 2020-09-08 16:54
@5523eeOMEGALUL please test that PR again. I added another commit. I'm not building with openssl, that's why I couldn't reproduce it.

**Comment by 5523eeOMEGALUL** [comment] 2020-09-08 23:22
`'libtorrent::aux::assert_message<libtorrent::aux::required_size<304>,libtorrent::aux::available_size<280>,libtorrent::aux::read_handler>' being compiled (compiling source file C:\vs\libtorrent-rasterbar-2.0.0\src\peer_connection.cpp)`
`torrent-rasterbar	C:\vs\libtorrent-rasterbar-2.0.0\include\libtorrent\aux_\allocating_handler.hpp	211	`
extra 8 lines in allocating_handler.hpp mean original 211 = 203
https://github.com/arvidn/libtorrent/blob/v2.0.0/include/libtorrent/aux_/allocating_handler.hpp#L202

**Comment by 5523eeOMEGALUL** [comment] 2020-09-08 23:36
libtorrent need one more fix
https://github.com/arvidn/libtorrent/blob/v2.0.0/CMakeLists.txt#L606
after `/bigobj` add `/Zc:__cplusplus` somewhere
https://github.com/arvidn/libtorrent/blob/v2.0.0/Jamfile#L308
change `result += <cflags>/bigobj ;`
to `result += <cflags>/bigobj /Zc:__cplusplus ;`

https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus
`/Zc:__cplusplus compiler option enables the __cplusplus preprocessor macro`
in MSVC no `__cplusplus` macro unless `/Zc:__cplusplus` used

https://github.com/arvidn/libtorrent/blob/v2.0.0/include/libtorrent/units.hpp#L163
https://github.com/arvidn/libtorrent/issues/5114

**Comment by arvidn** [comment] 2020-09-09 07:24
> libtorrent need one more fix

Can you explain why?
I think the more important point is that if the client is built with this flag, libtorrent should also have to be built with this flag.

**Comment by 5523eeOMEGALUL** [comment] 2020-09-09 07:26
> Can you explain why?

it said
https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus
/Zc:__cplusplus compiler option enables the __cplusplus preprocessor macro
`enables the __cplusplus preprocessor macro`
and link to file with code
https://github.com/arvidn/libtorrent/blob/v2.0.0/include/libtorrent/units.hpp#L163

**Comment by arvidn** [comment] 2020-09-09 07:49
so, `units.hpp` look at `__cplusplus` to determine whether to use `std::hash<>::result_type` or not. If it isn't using it, it just defines it as `std::size_t`. Presumably nobody should be using this `result_type` typedef anyway, since it's deprecated. It's defined in the custom hash wrapper to stay backwards compatible.

Let's say `__cplusplus` is incorrectly defined (as it is by default on msvc), where's the harm in that? The fact that you get deprecation warnings?

There's a risk in "fixing" the warnings by passing the `/Zc:__cplusplus` flag, which is that there may be other things in libtorrent (or even 3rd party libraries used by libtorrent) that change ABI based on the value of `__cplusplus`, in which case it's *critical* that the client, linking against libtorrent, *also* pass this compiler flag. If not, you'd get subtle memory corruption.

So, perhaps there is no code like that, maybe it's safe to have different values for `__cplusplus` in the client and library, but that might change in the future.

If the only reason you have to set this flag is to suppress warnings, it's not obvious to me that it's worth the risk of introducing ABI incompatibilities.

Would it work to just remove the declaration of `result_type` altogether for instance? that would be the safest way of getting rid of the warnings. If anyone uses that typedef anywhere, it would be a compilation error, which would be a good error.

**Comment by 5523eeOMEGALUL** [comment] 2020-09-09 10:14
did some more googling.
MSVC have `_MSVC_LANG` `Defined as an integer literal that specifies the C++ language standard targeted by the compiler.`
without forcing `/Zc:__cplusplus`
`#if __cplusplus >= 201402 || (defined(_MSVC_LANG) && _MSVC_LANG >= 201402L)` + swap `= std::size_t` and `= typename`

https://github.com/arvidn/libtorrent/issues/5111#issuecomment-689186645
after adding more since assert did happen one more time for different file
`constexpr std::size_t read_handler_max_size = tracking + debug_read_iter + openssl_read_cost + 102 + (8 * sizeof(void*)) + 24;`
`constexpr std::size_t write_handler_max_size = tracking + debug_write_iter + openssl_write_cost + 110 + (6 * sizeof(void*)) + 32;`
now just 6 messages and 1 warning
https://paste.ubuntu.com/p/qw9w2bH2fZ/

have no idea what `m_read_handler_storage` `m_write_handler_storage` are
able to download some random torrent with 2.0 version
thanks

**Comment by arvidn** [comment] 2020-09-09 10:33
@5523eeOMEGALUL could you try out the patch again? I've updated it and tested it more thoroughly on msvc now (with openssl)

**Comment by 5523eeOMEGALUL** [comment] 2020-09-09 10:43
dont see anything new
https://github.com/arvidn/libtorrent/pull/5116/commits/36694578c1ebd107e30365b2a3964c0786dd08d9
where to get it?

**Comment by arvidn** [comment] 2020-09-09 10:56
I force pushed to the top commit

**Comment by 5523eeOMEGALUL** [comment] 2020-09-09 11:06
https://github.com/arvidn/libtorrent/pull/5116/commits/b4527da5748e8d1ab6165009df91046bdc057f5e

for a test did put -1 to `read_handler_max_size` and then to `write_handler_max_size` 

`'libtorrent::aux::assert_message<libtorrent::aux::required_size<304>,libtorrent::aux::available_size<303>,libtorrent::aux::read_handler>' being compiled (compiling source file libtorrent-rasterbar-2.0.0\src\peer_connection.cpp)`

`'libtorrent::aux::assert_message<libtorrent::aux::required_size<304>,libtorrent::aux::available_size<303>,libtorrent::aux::write_handler>' being compiled (compiling source file C:\vs\libtorrent-rasterbar-2.0.0\src\peer_connection.cpp)`

304 seems correct number, boost 1.74 openssl 1.1.1h
`Rebuild All: 3 succeeded, 0 failed`

**Comment by arvidn** [comment] 2020-09-09 12:30
thanks for testing!

**Closed** 2020-09-09 14:57 UTC
