### ISSUE TITLE
1.1.0 make error in Centos7

### ISSUE THREAD

**Issue by zoudf** [arvidn/libtorrent#651] opened 2016-04-26 22:16 UTC
**Please provide the following information**

libtorrent version (or branch): 1.1.0

platform/architecture:Centos7 64bit

compiler and compiler version:gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Error Log:
  CXX      error_code.lo
error_code.cpp:44:30: error: expected ‘;’ at end of member declaration
   virtual const char* name() const BOOST_SYSTEM_NOEXCEPT;
                              ^
error_code.cpp:44:36: error: ‘BOOST_SYSTEM_NOEXCEPT’ does not name a type
   virtual const char* name() const BOOST_SYSTEM_NOEXCEPT;
                                    ^
error_code.cpp:45:39: error: expected ‘;’ at end of member declaration
   virtual std::string message(int ev) const BOOST_SYSTEM_NOEXCEPT;
                                       ^
error_code.cpp:45:45: error: ‘BOOST_SYSTEM_NOEXCEPT’ does not name a type
   virtual std::string message(int ev) const BOOST_SYSTEM_NOEXCEPT;
                                             ^
error_code.cpp:46:74: error: expected ‘;’ at end of member declaration
   virtual boost::system::error_condition default_error_condition(int ev) const BOOST_SYSTEM_NOEXCEPT
                                                                          ^
error_code.cpp:46:80: error: ‘BOOST_SYSTEM_NOEXCEPT’ does not name a type
   virtual boost::system::error_condition default_error_condition(int ev) const BOOST_SYSTEM_NOEXCEPT
                                                                                ^
error_code.cpp:50:54: error: expected initializer before ‘BOOST_SYSTEM_NOEXCEPT’
  const char* libtorrent_error_category::name() const BOOST_SYSTEM_NOEXCEPT
                                                      ^
error_code.cpp:55:63: error: expected initializer before ‘BOOST_SYSTEM_NOEXCEPT’
  std::string libtorrent_error_category::message(int ev) const BOOST_SYSTEM_NOEXCEPT
                                                               ^
error_code.cpp:352:1: error: expected ‘}’ at end of input
 }
 ^
make[1]: *** [error_code.lo] Error 1
make[1]: Leaving directory `/home/azou/Source/libtorrent-rasterbar-1.1.0/src'
make: *** [all-recursive] Error 1

**Comment by arvidn** [comment] 2016-04-26 23:04
duplicate of #645

**Closed by arvidn** 2016-04-26 23:04 UTC
Labels: duplicate
