### ISSUE TITLE
I/O errors and upload mode issues

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#6073] opened 2021-03-18 17:34 UTC
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

The documentation states:
`If a torrent hits a disk write error, it will be put into upload mode. This means it will not download anything, but only upload. The assumption is that the write error is caused by a full disk or write permission errors. If the torrent is auto-managed, it will periodically be taken out of the upload mode, trying to write things to the disk again. This means torrent will recover from certain disk errors if the problem is resolved. If the torrent is not auto managed, you have to call set_upload_mode() to turn downloading back on again.`

The problem is average users won't read this documentation ever and they're left wondering why their torrents don't resume immediately after freeing up some space(which is the most common cause of I/O errors).

There's been multiple tickets (https://github.com/qbittorrent/qBittorrent/issues/13680 , https://github.com/qbittorrent/qBittorrent/issues/14377 https://github.com/qbittorrent/qBittorrent/issues/14288 ) in the qBt issue tracker regarding this problem.

Seeking a better solution for such I/O related issues.
My suggestion is to pause torrents after I/O error and let the user resume it after resolving the space related problem.

P.S - Torrents by default are auto mananged in qBt unless force resumed.

**Comment by glassez** [comment] 2021-03-19 06:00
> My suggestion is to pause torrents after I/O error and let the user resume it after resolving the space related problem.

I hope you're not suggesting libtorrent to turn off `auto_managed` for such torrents... libtorrent should NEVER touch `auto_managed` property. Otherwise, it will not be able to be managed in a more or less reliable way.

**Comment by an0n666** [comment] 2021-03-19 14:23
> I hope you're not suggesting libtorrent to turn off `auto_managed` for such torrents... libtorrent should NEVER touch `auto_managed` property. Otherwise, it will not be able to be managed in a more or less reliable way.

No, I'm just suggesting to pause the torrent just like utorrent does. Putting a torrent into upload mode without any visual que or user confirmation is a bad UIX because even after manual pause/resume/force recheck the torrent is stuck in upload mode(till auto management decides to turn that flag off). 

So the user is left with only two options to immediately resume downloading:
1. Force resume.
2. Remove and re-add the torrent to session.

Most would probably choose the latter due to lack of documentation regarding these issues.

**Comment by glassez** [comment] 2021-03-19 17:12
@an0n666
Offering such changes to libtorrent behind the back of the developers of client applications, you just aggravate this problem.

>If a torrent hits a disk write error, it will be put into upload mode.

@arvidn
Doesn't it report an error and pause the torrent like in other cases?

> Putting a torrent into upload mode without any visual que or user confirmation is a bad UIX

Upload mode isn't error itself to indicate it. Client application is free to set it up on its own. 
But since qBittorrent never use it (for regular torrent) we can treat it as exceptional case and indicate in some way.
>even after manual pause/resume/force recheck the torrent is stuck in upload mode(till auto management decides to turn that flag off).

We can clear it from application side.

Pausing the torrent by itself will not solve the problem. There must be some reasonable way to get the torrent out of this state both automatically and manually by the user.

**Comment by arvidn** [comment] 2021-03-19 23:19
Generally, when a torrent encounters a disk error, it will be stopped, a [file_error_alert](http://libtorrent.org/reference-Alerts.html#file_error_alert) is posted and I believe a [torrent_error_alert](http://libtorrent.org/reference-Alerts.html#torrent_error_alert) too. The torrent is paused and set into not-auto managed (force-stopped).

However, if the disk failure was from a *write* operation, the torrent will be placed in upload-mode and not stopped. However, the file_error_alert should still be posted. If the underlying error is serious enough to also affect disk reads, it ought to fail as described above soon anyway.

> No, I'm just suggesting to pause the torrent just like utorrent does. Putting a torrent into upload mode without any visual que or user confirmation is a bad UIX because even after manual pause/resume/force recheck the torrent is stuck in upload mode(till auto management decides to turn that flag off).

libtorrent doesn't have any UX though. It has an API. Granted, an API can be poor as well, and I'm always open to suggestions of improvements.

> So the user is left with only two options to immediately resume downloading:
> 
> Force resume.
> Remove and re-add the torrent to session.
> Most would probably choose the latter due to lack of documentation regarding these issues.

It's also possible to directly clear the [upload_mode](http://libtorrent.org/reference-Core.html#torrent_flags_t) flag with [torrent_handle::unset_flag](http://libtorrent.org/reference-Torrent_Handle.html#flags-unset-flags-set-flags).

Assuming "user" means the programmer interacting with the libtorrent API.

**Comment by an0n666** [comment] 2021-03-22 15:51
> Pausing the torrent by itself will not solve the problem. There must be some reasonable way to get the torrent out of this state both automatically and manually by the user.

I think qBt could just clear the upload only flag anytime an errored torrent is resumed. That would also resolve this issue.

**Comment by an0n666** [comment] 2021-03-22 15:58
> However, if the disk failure was from a _write_ operation, the torrent will be placed in upload-mode and not stopped. However, the file_error_alert should still be posted. If the underlying error is serious enough to also affect disk reads, it ought to fail as described above soon anyway.

I think this case matches with disk full scenarios. Where only writes fail and the torrent would never be stopped. The user will have to manually unset the flag (the client application we're talking about currently doesn't offer such options) or wait for auto management.

> libtorrent doesn't have any UX though. It has an API. Granted, an API can be poor as well, and I'm always open to suggestions of improvements.

> It's also possible to directly clear the [upload_mode](http://libtorrent.org/reference-Core.html#torrent_flags_t) flag with [torrent_handle::unset_flag](http://libtorrent.org/reference-Torrent_Handle.html#flags-unset-flags-set-flags).
> 
> Assuming "user" means the programmer interacting with the libtorrent API.

Sorry, I was talking about the possibilities through a particular client program. Not the API.

**Comment by an0n666** [comment] 2021-03-30 08:31
@arvidn 
I just got my disk full while downloading a torrent and the torrent got stalled(no download speed) as expected. After I relocated the files it started downloading again. 
However, the torrent stalled again at 99.8% despite being connected with seeders.
Two files were incomplete. One had 16 MiB remaining and another one 96 MiB. The torrent had 16 MiB pieces.
Pause/resume didn't fix the problem. Had to force recheck.

**Comment by arvidn** [comment] 2021-03-30 09:15
I suspect there's an issue where pieces that fail being written to disk are still somehow not considered for downloading again.

**Comment by glassez** [comment] 2021-04-16 12:01
>The problem is average users won't read this documentation ever and they're left wondering why their torrents don't resume immediately after freeing up some space(which is the most common cause of I/O errors).

I try to understand this problem...
In order for torrent to start immediately resume immediately after user freeing up some space, it must try to do this every moment (e.g  every second), which does not look reasonable. libtorrent currently tries to exit the upload mode every 10 minutes. Isn't that enough (given that the disk can remain full for hours, or even days)? An additional problem is that this doesn't work for non-auto-managed (at libtorrent level) torrents, but we can fix this at the application level.
Another solution is mark torrent as errored once it goes to upload mode so that the user can see this and can manually "revive" such a torrent after freeing up free space, if he does not want to wait for this to happen automatically.

**Comment by glassez** [comment] 2021-04-16 12:05
@arvidn
Wouldn't it be a good idea to libtorrent considers such errors as regular IO errors? At least add some setting to change this behavior to not break current one by default?

**Comment by an0n666** [comment] 2021-04-19 08:20
> Another solution is mark torrent as errored once it goes to upload mode so that the user can see this and can manually "revive" such a torrent after freeing up free space, if he does not want to wait for this to happen automatically.
>
I think this behaviour is seen in utorrent as well..When disk becomes full the torrent gets errored with a message : 
`Error: There's not enough space on disk. (WriteToDisk)`.
This gives a hint to the user that their disk is full and they need to free up some space.
But in qBt it'll just throw a I/O error notification and nothing is displayed in the UI. So unless the user checks their disk space they'll left wondering what's causing the I/O error. So I think it's better to throw a specific error for disk full scenarios so the applications can display a more precise state.

**Comment by glassez** [comment] 2021-04-20 14:47
@an0n666
Can you try https://github.com/qbittorrent/qBittorrent/pull/14825?

**Comment by an0n666** [comment] 2021-04-20 17:34
> @an0n666
> Can you try [qbittorrent/qBittorrent#14825](https://github.com/qbittorrent/qBittorrent/pull/14825)?

It worked nicely!

However the issue with some pieces not getting re-downloaded still remains.
A workaround could be to require force recheck of such errored torrents when users try to resume.
Or wait for @arvidn to find out the actual bug and fix it.

**Comment by glassez** [comment] 2021-04-21 03:39
> However the issue with some pieces not getting re-downloaded still remains.

I didn't do anything about it.
Probably, this problem is more global and does not apply only to `upload_mode`. qBittorrent users often report a situation where the torrent completes the download, but in fact has missing pieces, so that after rechecking the progress falls below 100%.

**Comment by an0n666** [comment] 2021-04-21 07:24
> qBittorrent users often report a situation where the torrent completes the download, but in fact has missing pieces, so that after rechecking the progress falls below 100%.
>
In this case the download doesn't complete. Pieces are shown as incomplete however not downloaded from peers.

**Comment by arvidn** [comment] 2021-05-05 07:11
I've written a test that exercise the disk-full case, and ensures libtorrent recovers when there's space available again (as long as the torrent is auto-managed). It does not reproduce this issue unfortunately, so I think there may be something more subtle going on.

The test is a simulation that replaces the disk subsystem with a simulated one, in order to inject the disk-full errors. So perhaps the issue is in the real disk I/O code.

Here's the PR: https://github.com/arvidn/libtorrent/pull/6183

**Comment by an0n666** [comment] 2021-05-06 23:22
Looks like the PR is aimed at RC2_0? Does it work the same on 1_2?

**Comment by arvidn** [comment] 2021-05-07 09:28
the disk subsystem was overhauled in 2.0, so this test won't work in 1.2.x, and it would essentially have to be rewritten from scratch for 1.2.x.

However, I'm not aware of any fixes that might have addressed pieces failing to download but yet being believed to have been downloaded by libtorrent, in 2.0.x since 1.2.x

**Comment by an0n666** [comment] 2021-05-08 10:22
@arvidn the download does complete after restarting qbittorrent as well. That does not require a force recheck.

**Comment by arvidn** [comment] 2021-06-07 14:15
I'm tempted to close this issue. As far as I can tell, it's not describing a problem nor a feature request in libtorrent.

**Closed** 2021-06-07 15:17 UTC
Labels: bug
