### ISSUE TITLE
flags gone ?? not save to resume data.

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4637] opened 2020-05-11 14:06 UTC
After I started libtorrent, I added torrent and set some flags. Setting and removing them by handle were successful.
but
When I close libtorrent and restart it, when libtorrent reads torrent from the resume data, there are no flags. It seems that flags are not saved to the resume data. Do you need to save them additionally in this case?

**Comment by arvidn** [comment] 2020-05-11 20:22
No, you're not supposed to have to save them separately.
Do the flags show up in the saved resume file?
Do they show up in the `add_torrent_params` object?

**Comment by zbooa** [comment] 2020-05-11 23:46
According to your opinion, if it is not my saving method that is wrong, it is my reading method that is wrong. Can I have a hint?
This is my code.
Read falgs.
`lt::torrent_status tss = h.status(lt::torrent_handle::query_torrent_file);`
`CString h_dht = ((tss.flags & lt::torrent_flags::disable_dht) == lt::torrent_flags::disable_dht) ? "0" : "1";`
Save resume data.
`h.save_resume_data(lt::torrent_handle::save_info_dict);`
These codes can be used without restarting libtorrent. But it's not good to restart. I don't know if I wrote something wrong.

**Comment by arvidn** [comment] 2020-05-12 00:31
I'm suggesting you narrow down where the problem is by looking at the flags in the add_torrent_params` object, in the buffer in memory, on disk. then when you load it again, look in the memory buffer, in the `add_torrent_params` object. That will give you a hind of where you're losing the flags.

**Comment by zbooa** [comment] 2020-05-12 03:17
> I'm suggesting you narrow down where the problem is by looking at the flags in the add_torrent_params`object, in the buffer in memory, on disk. then when you load it again, look in the memory buffer, in the`add_torrent_params` object. That will give you a hind of where you're losing the flags.

I try check it.
```lt::add_torrent_params p = lt::read_resume_data(resume_data, ec);

if ((p.flags & lt::torrent_flags::disable_dht) == lt::torrent_flags::disable_dht) {
	int xxx = 888888;//NOT IN HERE
}
lt::torrent_handle h = ses.add_torrent(std::move(p));
```
I want to know if my judgment is correct

**Comment by arvidn** [comment] 2020-05-12 08:55
it looks like `write_resume_data` only saves these flags:

* `sequential_download`
* `seed_mode`
* `super_seeding`
* `paused`
* `auto_managed`
* `stop_when_ready`

**Comment by zbooa** [comment] 2020-05-12 13:10
> it looks like `write_resume_data` only saves these flags:
> 
> * `sequential_download`
> * `seed_mode`
> * `super_seeding`
> * `paused`
> * `auto_managed`
> * `stop_when_ready`

... ... I test a few flags,  And I recorded whether they can restore the state of libtorrent before restarting libtorrent. (You should be right.)
`lt::torrent_flags::disable_dht`    **can't**
`lt::torrent_flags::disable_lsd`     **can't**
`lt::torrent_flags::disable_pex`    **can't**
`lt::torrent_flags::apply_ip_filter`     **can't**
`lt::torrent_flags::auto_managed`    **can [only it can be recorded]**
If it's like you said, I have to find another way to save these flags, isn't it?

**Comment by arvidn** [comment] 2020-05-12 21:59
could you try this patch? https://github.com/arvidn/libtorrent/pull/4642

**Comment by zbooa** [comment] 2020-05-13 02:41
> could you try this patch? #4642

I modified two key files on version 1.2.4,
`src/read_resume_data.cpp`
`src/write_resume_data.cpp`
It doesn't work to re edit and load it into the project. It will try again later with 1.2.7.

**Comment by arvidn** [comment] 2020-05-13 10:22
I don't understand. Did you try the patch and it didn't work?

**Comment by zbooa** [comment] 2020-05-13 12:40
> I don't understand. Did you try the patch and it didn't work?

Yes，my version is 1.2.4. Didn't work.  I have only modified two files, recompiled lib and DLL, loaded them into the project record, recompiled the project, deleted the old resume file, regenerated them, and reloaded torrent. I still can't read the relevant marks from the resume data. 

I want to know to make sure if there is any error in my code?
```
lt::add_torrent_params p = lt::read_resume_data(resume_data, ec);
if ((p.flags & lt::torrent_flags::disable_dht) == lt::torrent_flags::disable_dht) {
        //The flags from the resume data
}
```

**Comment by arvidn** [comment] 2020-05-13 13:05
> Yes，my version is 1.2.4. Didn't work.

The patch is against `RC_1_2`, did the patch apply cleanly? (I would imagine so).

Can you be a bit more specific as to *what* did not work? where it failed?
Did the field "disable_dht" end up in your resume file?

```
if ((p.flags & lt::torrent_flags::disable_dht) == lt::torrent_flags::disable_dht) {
        //The flags from the resume data
}
```

Yes, that how you check if a flag is set. You don't need to compare it against `lt::torrent_flags::disable_dht`, if the flag is set it will implicitly convert to `true`

**Comment by zbooa** [comment] 2020-05-13 13:34
> > Yes，my version is 1.2.4. Didn't work.
> 
> The patch is against `RC_1_2`, did the patch apply cleanly? (I would imagine so).
> 
> Can you be a bit more specific as to _what_ did not work? where it failed?
> Did the field "disable_dht" end up in your resume file?
> 
> ```
> if ((p.flags & lt::torrent_flags::disable_dht) == lt::torrent_flags::disable_dht) {
>         //The flags from the resume data
> }
> ```
> 
> Yes, that how you check if a flag is set. You don't need to compare it against `lt::torrent_flags::disable_dht`, if the flag is set it will implicitly convert to `true`

You mean I have to use `RC_1_2` ？May I change the 1.2.4 source code and it won't work? I have recompiled lib and DLL.

**Comment by arvidn** [comment] 2020-05-13 13:42
> You mean I have to use RC_1_2 ？May I change the 1.2.4 source code and it won't work?

if by "change" you mean "apply the patch", sure.

**Comment by zbooa** [comment] 2020-05-13 13:47
> > You mean I have to use RC_1_2 ？May I change the 1.2.4 source code and it won't work?
> 
> if by "change" you mean "apply the patch", sure.

How "apply the patch" ? use git soft ?

**Comment by arvidn** [comment] 2020-05-13 13:54
download the patch: https://patch-diff.githubusercontent.com/raw/arvidn/libtorrent/pull/4642.diff

apply it with current working directory the root of the libtorrent repo:
```
patch -p1 <4642.diff
```

**Comment by zbooa** [comment] 2020-05-13 16:27
> download the patch: https://patch-diff.githubusercontent.com/raw/arvidn/libtorrent/pull/4642.diff
> 
> apply it with current working directory the root of the libtorrent repo:
> 
> ```
> patch -p1 <4642.diff
> ```

... Looks like I'm going to download a Git. Because I don't use git very often, it's not installed.

**Comment by zbooa** [comment] 2020-05-13 23:37
> download the patch: https://patch-diff.githubusercontent.com/raw/arvidn/libtorrent/pull/4642.diff
> 
> apply it with current working directory the root of the libtorrent repo:
> 
> ```
> patch -p1 <4642.diff
> ```

So sad. It doesn't work as scheduled. I try two ways
A use git to patch and compile the library.
B. Using 1.2.7 directly, compile. Carefully check whether the code is the same as the patch.
Add lib and dll to my project again and recompile. it's still the same
The flags is not recorded in the resume file
But others, such as upload limit , download limit, and file progress, are normal.
Can you do a test, including saving and reading flags.
Thank you for everything.

**Comment by arvidn** [comment] 2020-05-14 10:02
there are unit tests in that patch that ensure these flags round-trip through `read_resume_data()` and `write_resume_data()`.
When you ask for the `add_torrent_params` object from the `torrent_handle`, does it have the flags set in it?

**Comment by arvidn** [comment] 2020-05-14 10:13
@zbooa please try again with the updated patch

**Comment by zbooa** [comment] 2020-05-14 11:18
> @zbooa please try again with the updated patch

Can you see what's wrong with my code?
Flags set in handle, save to resume file.
`h.set_flags(lt::torrent_flags::disable_dht);`
Shut down and restart libtorrent, read resume file
```
lt::add_torrent_params p = lt::read_resume_data(resume_data, ec);
if ((p.flags & lt::torrent_flags::disable_dht) == lt::torrent_flags::disable_dht) {
	int xxx = 888888;
}
lt::torrent_handle h = ses.add_torrent(std::move(p));
```
Then read from the handle if there is some flags
```
lt::torrent_status tss = h.status(lt::torrent_handle::query_torrent_file);
if ((tss.flags & lt::torrent_flags::disable_dht) == lt::torrent_flags::disable_dht){
        int yyy = 99999;
}
```
Do you have any tips?

**Comment by arvidn** [comment] 2020-05-14 11:40
> Do you have any tips?

Can you please tell me where the flag disappear?

**Comment by zbooa** [comment] 2020-05-14 11:52
> > Do you have any tips?
> 
> Can you please tell me where the flag disappear?

Shut down and restart libtorrent, read resume file. Can only read auto_managed....
I don't think flags wrote to the resume file,
auto_manage, which is added by default and can be read every time.

**Comment by arvidn** [comment] 2020-05-14 12:06
> I don't think flags wrote to the resume file,

could you open the resume file and take a look, to be sure?

If it's not there, please take a look at the `flags` field of the `add_torrent_params` you pass to `write_resume_data()` to see if it's there.

You are using the updated patch, right?

**Comment by zbooa** [comment] 2020-05-14 12:30
> > I don't think flags wrote to the resume file,
> 
> could you open the resume file and take a look, to be sure?
> 
> If it's not there, please take a look at the `flags` field of the `add_torrent_params` you pass to `write_resume_data()` to see if it's there.
> 
> You are using the updated patch, right?

There's no such function as you said, only `write_resume_data_buf`, Is it a problem？？？

```
...
else if (auto p = lt::alert_cast<lt::save_resume_data_alert>(a)) {
	lt::torrent_handle h = p->handle;
	auto buf = write_resume_data_buf(p->params);
	SaveFile(ResumeFile(h.info_hash()), buf);
}
...
```

**Comment by zbooa** [comment] 2020-05-14 13:03
> > I don't think flags wrote to the resume file,
> 
> could you open the resume file and take a look, to be sure?
> 
> If it's not there, please take a look at the `flags` field of the `add_torrent_params` you pass to `write_resume_data()` to see if it's there.
> 
> You are using the updated patch, right?

It can't be implemented with the following code.


> > I don't think flags wrote to the resume file,
> 
> could you open the resume file and take a look, to be sure?
> 
> If it's not there, please take a look at the `flags` field of the `add_torrent_params` you pass to `write_resume_data()` to see if it's there.
> 
> You are using the updated patch, right?

I prefer that the libtorrent of my pc does not save the flags to resume file, rather than cannot read the flags. But I'm not sure.
Please indicate a version that can save the tag and read the tag after restart,
Don't patch. I'm afraid I won't use the patch. I'll try again.
Thank you.

**Comment by zbooa** [comment] 2020-05-14 13:04
> > I don't think flags wrote to the resume file,
> 
> could you open the resume file and take a look, to be sure?
> 
> If it's not there, please take a look at the `flags` field of the `add_torrent_params` you pass to `write_resume_data()` to see if it's there.
> 
> You are using the updated patch, right?

I prefer that the libtorrent of my pc does not save the flags to resume file, rather than cannot read the flags. But I'm not sure.
Please indicate a version that can save the tag and read the tag after restart,
Don't patch. I'm afraid I won't use the patch. I'll try again.
Thank you.

**Comment by zbooa** [comment] 2020-05-14 13:33
> > I don't think flags wrote to the resume file,
> 
> could you open the resume file and take a look, to be sure?
> 
> If it's not there, please take a look at the `flags` field of the `add_torrent_params` you pass to `write_resume_data()` to see if it's there.
> 
> You are using the updated patch, right?

This is my new code, but It's still the same as using `write_resume_data_buf()`
```
else if (auto p = lt::alert_cast<lt::save_resume_data_alert>(a)) {
    lt::torrent_handle h = p->handle;
    //auto buf = write_resume_data_buf(p->params);
    auto buf = lt::write_resume_data(p->params);

    std::vector<char> buffer;
    lt::bencode(std::back_inserter(buffer), buf);		

    SaveFile(ResumeFile(h.info_hash()), buffer);
    buffer.clear();
    buffer.shrink_to_fit();
}
```

**Comment by arvidn** [comment] 2020-05-14 14:00
write_resume_data() and write_resume_data_buf() do the same thing. It doesn't matter which one you use.

> Please indicate a version that can save the flags and read the flags after restart,

I'm suggesting the version I pointed to in #4642 does it correctly. I'm interested in whether it solves your use case, or whether I've missed something.

> Don't patch. I'm afraid I won't use the patch. I'll try again.

I'm not following. Software evolves by applying changes to it. This bug will only be fixed by a patch.

**Comment by zbooa** [comment] 2020-05-14 14:29
> write_resume_data() and write_resume_data_buf() do the same thing. It doesn't matter which one you use.
> 
> > Please indicate a version that can save the flags and read the flags after restart,
> 
> I'm suggesting the version I pointed to in #4642 does it correctly. I'm interested in whether it solves your use case, or whether I've missed something.
> 
> > Don't patch. I'm afraid I won't use the patch. I'll try again.
> 
> I'm not following. Software evolves by applying changes to it. This bug will only be fixed by a patch.

Yes, I see.
OK, thank you. I will focus on this problem until it is solved.  thank you again. Love you.

**Comment by zbooa** [comment] 2020-05-15 13:16
> write_resume_data() and write_resume_data_buf() do the same thing. It doesn't matter which one you use.
> 
> > Please indicate a version that can save the flags and read the flags after restart,
> 
> I'm suggesting the version I pointed to in #4642 does it correctly. I'm interested in whether it solves your use case, or whether I've missed something.
> 
> > Don't patch. I'm afraid I won't use the patch. I'll try again.
> 
> I'm not following. Software evolves by applying changes to it. This bug will only be fixed by a patch.

It's my code problem. Used #4642 compile and reintroduce to my project, which has realized the relevant functions. Thank you for everything.

**Comment by arvidn** [comment] 2020-05-15 14:03
so the fix works then?

**Comment by zbooa** [comment] 2020-05-16 00:45
> so the fix works then?

I think so. At least the flags I tested can be restored. Thank you again.

**Closed** 2020-05-16 08:31 UTC
