### ISSUE TITLE
tools/dht_put crash

### ISSUE THREAD

**Issue by thomas-yuan** [arvidn/libtorrent#271] opened 2015-11-16 17:26 UTC
version: 0dbe94616a5710bcb3562ae338e6c2e17665d16b

```
dht get e28910ea0adb94dd45ced75fbff3e135c01bc437
load dht state from .dht
broadcast socket [ if: 127.0.0.1 group: 239.255.255.250 mask: 255.0.0.0 ] Success
broadcast socket [ if: 172.250.250.198 group: 239.255.255.250 mask: 255.255.255.0 ] Success
broadcast socket [ if: 172.16.206.1 group: 239.255.255.250 mask: 255.255.255.0 ] Success
broadcast socket [ if: 192.168.31.1 group: 239.255.255.250 mask: 255.255.255.0 ] Success
broadcast socket [ if: 127.0.0.1 group: 239.192.152.143 mask: 255.0.0.0 ] Success
broadcast socket [ if: 172.250.250.198 group: 239.192.152.143 mask: 255.255.255.0 ] Success
broadcast socket [ if: 172.16.206.1 group: 239.192.152.143 mask: 255.255.255.0 ] Success
broadcast socket [ if: 192.168.31.1 group: 239.192.152.143 mask: 255.255.255.0 ] Success
broadcast socket [ if: ::1 group: ff15::efc0:988f mask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff ] Success
bootstrapping
/
bootstrap done.
GET e28910ea0adb94dd45ced75fbff3e135c01bc437
/
hello
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.1.0.0
4c0b00c

file: '../src/kademlia/traversal_algorithm.cpp'
line: 359
function: void libtorrent::dht::traversal_algorithm::failed(libtorrent::dht::observer_ptr, int)
expression: m_invoke_count > 0

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2: libtorrent::dht::traversal_algorithm::failed(boost::intrusive_ptr<libtorrent::dht::observer>, int)
3: libtorrent::dht::observer::abort()
4: libtorrent::dht::rpc_manager::~rpc_manager()
5: libtorrent::dht::node::~node()
6: libtorrent::dht::dht_tracker::~dht_tracker()
7: boost::detail::sp_ms_deleter<libtorrent::dht::dht_tracker>::destroy()
8: boost::detail::sp_ms_deleter<libtorrent::dht::dht_tracker>::operator()(libtorrent::dht::dht_tracker*)
9: boost::detail::sp_counted_impl_pd<libtorrent::dht::dht_tracker*, boost::detail::sp_ms_deleter<libtorrent::dht::dht_tracker> >::dispose()
10: boost::detail::sp_counted_base::release()
11: boost::detail::shared_count::~shared_count()
12: boost::shared_ptr<libtorrent::dht::dht_tracker>::~shared_ptr()
13: boost::_bi::value<boost::shared_ptr<libtorrent::dht::dht_tracker> >::~value()
14: boost::_bi::storage1<boost::_bi::value<boost::shared_ptr<libtorrent::dht::dht_tracker> > >::~storage1()
15: boost::_bi::storage2<boost::_bi::value<boost::shared_ptr<libtorrent::dht::dht_tracker> >, boost::arg<1> >::~storage2()
16: boost::_bi::list2<boost::_bi::value<boost::shared_ptr<libtorrent::dht::dht_tracker> >, boost::arg<1> >::~list2()
17: boost::_bi::bind_t<void, boost::_mfi::mf1<void, libtorrent::dht::dht_tracker, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<boost::shared_ptr<libtorrent::dht::dht_tracker> >, boost::arg<1> > >::~bind_t()
18: boost::asio::detail::binder1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, libtorrent::dht::dht_tracker, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<boost::shared_ptr<libtorrent::dht::dht_tracker> >, boost::arg<1> > >, boost::system::error_code>::~binder1()
19: boost::asio::detail::wait_handler<boost::_bi::bind_t<void, boost::_mfi::mf1<void, libtorrent::dht::dht_tracker, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<boost::shared_ptr<libtorrent::dht::dht_tracker> >, boost::arg<1> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long)
20: boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task_io_service&, boost::system::error_code const&, unsigned long)
21: boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&)
22: boost::asio::detail::task_io_service::run(boost::system::error_code&)
23: boost::asio::io_service::run()
24: boost::_mfi::mf0<unsigned long, boost::asio::io_service>::operator()(boost::asio::io_service*) const
25: unsigned long boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> >::operator()<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list0>(boost::_bi::type<unsigned long>, boost::_mfi::mf0<unsigned long, boost::asio::io_service>&, boost::_bi::list0&, long)
26: boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >::operator()()
27: boost::asio::detail::posix_thread::func<boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > > >::run()
28: boost_asio_detail_posix_thread_function
29: 
30: clone
```

**Comment by ssiloti** [comment] 2015-11-17 04:49
The bug is caused when an observer gets abandoned due to traversal_algorithm::m_results being greater than 100. If the traversal is done before the observer times out then the observer does not get flag_done set on it. The when the rpc_manager is destroyed the observer tries to call traversal_algorithm::failed() but the invoke count has already been cleared to zero in traversal_algorithm::done().

This wasn't directly caused by c2277b3ea50b42fd0461cd7640cafb046f335dd7 but it exposed the bug due to the traversal finishing much sooner than before.

I'm working on a fix.

One other thing I noticed is that despite the traversal being finished, m_results is not empty. There are a small number of observers with no flags set. This seems suspicious so I'll investigate it later.

**Comment by arvidn** [comment] 2015-11-18 00:11
this patch is merged. @thomas-yuan could you confirm it's fixed?

**Comment by thomas-yuan** [comment] 2015-11-18 01:36
Sure. Actually I have verified as I mentioned in the comments of PR #272

**Closed** 2015-11-18 01:37 UTC
