### ISSUE TITLE
1.2.4 connecting to less people than 1.2.3 ?

### ISSUE THREAD

**Issue by Rootax** [arvidn/libtorrent#4329] opened 2020-02-14 18:35 UTC
**Please provide the following information**

1.2.3 vs 1.2.4

platform/architecture:
 Windows 10 x64

Hi.

So I compiled qbt 4.2.1 (tried the official 4.2.1, and the one with most recent fixes like https://github.com/an0n666/qBittorrent/commits/fix-not-contacted-tracker ) against 1.2.4, and I noticed that the download speed was a lot slower than 1.2.3.
So, I build the same version of qbt against 1.2.3, and yeah, instant faster dl speed. I tried the exact same torrent on the same tracker, which I know is very fast very quickly. On 1.2.3, I hit around 350mo/s (yes, mo, I've a 10g fiber at home). With 1.2.4, around 30-40mo/sec. No cpu usage problem, no tracker error.... And then I noticed that with 1.2.3, I quickly connected to the maximum peers that I allow in qbt, while with 1.2.4, It was hard to go above 20 conn. (vs 125 in 1.2.3).

I reproduced the same behavior accross multiple torrents. And same results, with ipv4 only, or ipv4+ipv6. I can't really log why the 1.2.4 version is not connecting to a lot of peers, but I guess the big difference in speed come from here. 

EDIT : moreover, I noticed that with 1.2.4, I've slow speed from libtorrent 0.13.x clients, while with 1.2.3, it normal.

Sorry for my english.

**Comment by an0n666** [comment] 2020-02-15 20:56
Is your incoming port accessible in 1.2.4?
Are you doing manual forwarding or UPnP?

**Comment by an0n666** [comment] 2020-02-15 21:05
Ok I confirm I have same issue. Libtorrent 1.2.4 is not getting any incoming connections. @arvidn

**Comment by Rootax** [comment] 2020-02-16 05:42
> Is your incoming port accessible in 1.2.4?
> Are you doing manual forwarding or UPnP?

Yes, they are accessible, and I do manual forwarding.

**Comment by an0n666** [comment] 2020-02-16 05:59
For me the problem gets solved by manual forwarding. Even though the port is accessible when forwarded through UPnP.

**Comment by Rootax** [comment] 2020-02-16 07:28
Strange, I already do manual forwarding, never done upnp, and I've the problem.

**Comment by arvidn** [comment] 2020-02-16 08:28
Anyone having issues with UPnP not working, do you have a gateway that’s not on the network you listen on? (But on a different network)

In order to avoid spamming everything on the network responding to ssdp, the upnp device ip is filtered by the netmask.

I should add an exemption for the gateway as well, as I recently learned the gateway isn’t necessarily on the same network

**Comment by an0n666** [comment] 2020-02-16 09:57
Looks like when you change your port and restart client, the same peers will not connect with you if they do not accept multiple connections from same IP. I was being a victim of that when my port changed. So actually I couldn't reproduce this issue and it's not related to UPnP / port forwarding.

**Comment by Rootax** [comment] 2020-02-16 10:04
I don't change port between the 1.2.3 client and 1.2.4 client. I was thinking about that, but even if I close everything for 60 minutes, start the 1.2.4 clients, I have the problem. Then I close it, switch to 1.2.3, insta high speed again...

**Comment by rwasef1830** [comment] 2020-02-16 16:57
I just compiled qBittorrent 4.2.1 with libtorrent 1.2.4 and tracker updating is completely broken. All trackers are marked as "Not working" and choosing Force reannounce does nothing. I had to revert to libtorrent 1.2.3 and recompile and qBittorrent is working again. @arvidn

**Comment by arvidn** [comment] 2020-02-17 07:41
@rwasef1830 sounds like a duplicate of https://github.com/arvidn/libtorrent/issues/4325

**Comment by T00old4This** [comment] 2020-02-17 13:30
All right, I have found something. I had the connectivity problem with my usual setup, which was, in "network interface" to chose my active network card, and in "ip address to bind", chose "all addresses" (or ipv4 or v6 only for testing purposes). 
So, this morning I did another test, with "any interface" instead of choosing my network card, and bam, high speed again, and a lot of peers/seeders. I don't know why, but, if this constatation can help...

**Comment by arvidn** [comment] 2020-02-17 13:35
I think this is consistent with my suspicion of this: https://github.com/arvidn/libtorrent/pull/4331 being the problem.

Anyone experiencing this symptom with the ability to build from source, please give that patch a try!

**Comment by arvidn** [comment] 2020-02-18 12:34
when experiencing this issue, is it the case that no peers are connected over uTP?

**Comment by Safari77** [comment] 2020-02-20 14:22
Try out https://github.com/arvidn/libtorrent/pull/4339

**Comment by Rootax** [comment] 2020-02-21 21:11
All right, so I compiled qbt against the route-error-message branch today. And, same problem. I had the connectivity if I chose in "network interface" to chose my active network card, and in "ip address to bind", chose "all addresses" (or ipv4 or v6 only for testing purposes). If I put "any interface" and "ipv4 address", it's ok. 

when experiencing this issue, is it the case that no peers are connected over uTP? => The contrary, I've only utp connex in that case, no tcp at all.

**Comment by arvidn** [comment] 2020-03-09 14:28
I believe this has been fixed in the 1.2.5 release

**Closed by arvidn** 2020-03-09 14:28 UTC

**Comment by Rootax** [comment] 2020-03-09 14:57
In my case, it's not if I choose a specific interface (yeah I build lastest qt against lastest lbt).

**Comment by arvidn** [comment] 2020-03-09 15:07
do you get any error alerts? Could you enable peer-, torrent- and session logging?

**Comment by Rootax** [comment] 2020-03-09 15:12
Don't know how to enable debug/log : / Do I have to enable some options when compiling ?

**Comment by arvidn** [comment] 2020-03-09 15:18
you have to update the [alert_mask](https://libtorrent.org/reference-Settings.html#alert_mask) setting to include [tracker_notification](https://libtorrent.org/reference-Alerts.html#tracker_notification), [session_log_notification](https://libtorrent.org/reference-Alerts.html#session_log_notification), [torrent_log_notification](https://libtorrent.org/reference-Alerts.html#torrent_log_notification) and [peer_log_notification](https://libtorrent.org/reference-Alerts.html#peer_log_notification) flags

**Comment by arvidn** [comment] 2020-03-09 15:20
could you explain again exactly which problem remains? If you *don't* select a specific interface, is everything working fine then?
and if you pick a specific interface, you see fewer peers? Or do you see the same number of peers but slower transfer rates?
Is the interface you pick a VPN? Do you have reasons to believe that the interface itself has slower connectivity than another interface?

**Comment by Rootax** [comment] 2020-03-09 15:29
-If i don't select a specific interface, everything is fine.
-If I select a specific interface (which is my network card, no vpn here. i've only one anyway), I have a less peer (in a significant fashion) => lower speed.

In both cases, I've "successfully listening on ip xxxxxxxx". 

In the first case, I've 127.0.0.1 , and 192.168.1.40 (my network card). In the second case, I only have 192.168.1.40, which is normal (but I don't know why I connect to a lot less peers)

**Comment by arvidn** [comment] 2020-03-09 15:32
It could be the DHT or the tracker failing in some way. Do you get any tracker alerts?
enabling the logging would give a lot more details of what's going on too.

**Comment by an0n666** [comment] 2020-03-09 15:35
> -If I select a specific interface (which is my network card, no vpn here. i've only one anyway), I have a less peer (in a significant fashion) => lower speed.
> 
> In both cases, I've "successfully listening on ip xxxxxxxx".
> 
> In the first case, I've 127.0.0.1 , and 192.168.1.40 (my network card). In the second case, I only have 192.168.1.40, which is normal (but I don't know why I connect to a lot less peers)

Maybe libtorrent is reporting your private IP to tracker. Are you facing it on private torrents on a specific tracker?

**Comment by Rootax** [comment] 2020-03-09 15:49
Private tracker, and the tracker is working, and detects my external ip correctly. I'll produce log if I can.

**Comment by an0n666** [comment] 2020-03-10 09:19
I could connect with same number of peers by selecting specific interface as well. Maybe you should cross check with other private trackers as well to make sure it's not a specific tracker issue.

As for the logs, qbt doesn't log any of those mentioned by arvidn. You'll have to change the source and make it log those alerts.
