### ISSUE TITLE
No Python class registered for C++ class class std::shared_ptr<class libtorrent::entry>

### ISSUE THREAD

**Issue by David-Luis** [arvidn/libtorrent#2841] opened 2018-03-13 18:36 UTC
libtorrent version (or branch):
master

platform/architecture:
windows 64 bits

compiler and compiler version:
Python 3.6

Hi! I'm receiving this error while trying to save resume_data:
`No Python class registered for C++ class class std::shared_ptr<class libtorrent::entry>`
 this is the code that triggers the error (directly taken from the example client.py):

`data = lt.bencode(a.resume_data)`

Seems the error is inside resume_data

**Comment by arvidn** [comment] 2018-03-24 16:07
are you using boost 1.60 by any chance. I think this may be caused by a bug in 1.60, that was fixed in 1.61. https://github.com/boostorg/python/pull/59

**Comment by David-Luis** [comment] 2018-03-25 06:41
I'm using boost 1.63... but I will test with 1.64 and update this :)

**Comment by arvidn** [comment] 2018-03-25 09:10
if you could extend ``test.py`` (under bindings/python) to reproduce this issue and create a pull request, it would be much appreciated. Then it's a lot easier to fix

**Comment by ssiloti** [comment] 2018-04-05 03:33
I haven't been able to repro this. I'm wondering how you even got as far as you did considering building libtorrent for python3 was broken at the time this bug was filed.

Like arvid said, it would help a lot of you could provide a script which reproduces the issue.

**Comment by arvidn** [comment] 2018-04-05 08:04
I looked at this last night and reproduced it. There are two aspects, the resume data buffer is deprecated in favor of params, which also doesn’t seem to work passing it into write_resume_data_buf()

**Comment by arvidn** [comment] 2018-04-05 08:11
I haven’t had time to look closely yet, but I believe entry does not have a smart pointer holder in the bindings, so the conversion fails

**Comment by arvidn** [comment] 2018-04-14 14:49
please test this patch! https://github.com/arvidn/libtorrent/pull/2939

**Comment by arvidn** [comment] 2018-04-22 11:03
@David-Luis have you had a chance to test my patch?

**Comment by David-Luis** [comment] 2018-04-24 07:18
sorry I had not time to test it recently :(. I will try during the week.

**Comment by arvidn** [comment] 2018-04-26 23:49
thanks, please let me know!

**Closed** 2018-04-29 14:33 UTC
