### ISSUE TITLE
Building latest LibTorrent for MIPSel

### ISSUE THREAD

**Issue by SysMan-One** [arvidn/libtorrent#1812] opened 2017-03-14 15:22 UTC
root@SysMan-Ubuntu:/home/sysman/LibTorrent/libtorrent# git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
root@SysMan-Ubuntu:/home/sysman/LibTorrent/libtorrent#

./configure --target=mipsel-linux-gnu  --disable-dht --with-boost-libdir=/noxbit/mipsel/lib --disable-encryption --with-boost=/noxbit/mipsel --disable-debug --disable-logging --disable-dht --disable-pool-allocators

root@SysMan-Ubuntu:/home/sysman/LibTorrent/libtorrent# make
Making all in include/libtorrent
make[1]: Entering directory '/home/sysman/LibTorrent/libtorrent/include/libtorrent'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/sysman/LibTorrent/libtorrent/include/libtorrent'
Making all in src
make[1]: Entering directory '/home/sysman/LibTorrent/libtorrent/src'
  CXX      web_connection_base.lo
  CXX      alert.lo
alert.cpp: In constructor ‘libtorrent::torrent_alert::torrent_alert(libtorrent::aux::stack_allocator&, const libtorrent::torrent_handle&)’:
alert.cpp:77:63: error: use of deleted function ‘boost::basic_string_view<charT, traits>::basic_string_view(std::__cxx11::basic_string<charT, traits, Allocator>&&) [with Allocator = std::allocator<char>; charT = char; traits = std::char_traits<char>]’
     m_name_idx = alloc.copy_string(aux::to_hex(t->info_hash()));
                                                               ^
In file included from ../include/libtorrent/string_view.hpp:47:0,
                 from ../include/libtorrent/entry.hpp:75,
                 from ../include/libtorrent/alert_types.hpp:46,
                 from alert.cpp:39:
/noxbit/mipsel/include/boost/utility/string_view.hpp:100:9: note: declared here
         basic_string_view(      std::basic_string<charT, traits, Allocator>&&)
         ^
Makefile:954: recipe for target 'alert.lo' failed
make[1]: *** [alert.lo] Error 1
make[1]: Leaving directory '/home/sysman/LibTorrent/libtorrent/src'
Makefile:618: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@SysMan-Ubuntu:/home/sysman/LibTorrent/libtorrent#

**Comment by arvidn** [comment] 2017-03-15 11:21
This looks like a duplicate of https://github.com/arvidn/libtorrent/issues/1803

**Comment by arvidn** [comment] 2017-03-21 04:00
There's a chance that this will be corrected in boost.

**Closed by arvidn** 2017-03-21 04:00 UTC
