### ISSUE TITLE
ABI breakage in 1.0.10 and 1.1.1

### ISSUE THREAD

**Issue by fbriere** [arvidn/libtorrent#1696] opened 2017-02-12 01:23 UTC
#698 and #704 apparently broke the ABI for 1.1.1 and 1.0.10, respectively.

Using qBittorrent compiled with an earlier version of libtorrent, the files newly written in `.local/share/data/qBittorrent/BT_backup` when adding torrents will be truncated copies.  Everything will appear to work fine as long as qBittorrent is running, but upon restarting, those corrupt copies will (obviously) not be loaded.

Recompiling qBittorrent against newer versions of the library fixes the issue.

For 1.0.10, I have bisected this down to 9d32f1f, and while I cannot do the same for 1.1.1 (#1242 makes it unusable for me), [Debian bug 842538](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842538) confirms that it is affected in the same way.

(For the record, all of this was on Debian/amd64, using gcc 6.3.0 in my case.)

**Comment by arvidn** [comment] 2017-02-12 01:48
1.0.x and 1.1.x are not supposed to be ABI compatible. As you can tell from the ``configure.in`` file, 1.0.x has [so-version 8](https://github.com/arvidn/libtorrent/blob/RC_1_0/configure.ac#L44) and 1.1.x has [so-version 9](https://github.com/arvidn/libtorrent/blob/RC_1_1/configure.ac#L44)

**Comment by arvidn** [comment] 2017-02-12 01:49
My understanding and intention of that version number is that it indicates ABI incompatibility. Please let me know if I have misunderstood how that number is encoded in the build

**Comment by fbriere** [comment] 2017-02-12 02:27
My apologies if my original message was ambiguous.  Basically, upgrading from 1.0.9 to 1.0.10, *or* from 1.1.0 to 1.1.1, will trigger this bug.  Both branches had their own ABI broken separately.

**Comment by arvidn** [comment] 2017-02-12 02:55
ah, I see. I didn't read your message all that carefully either I suppose. Thanks for tracking down that patch. I'm guessing that the same patch applied to the 1.1.x branch is responsible for its ABI breakage as well.

Looking at that patch, it's not obvious to me how it could affect the ABI. The size of the ``entry`` class' union should remain the same, since there's already a vector in there. Other than that, it's purely adding functions to the class. I was very careful when making this change to make sure to avoid ABI breakage. It does create a (non-ABI related) backwards compatibility issue. Files saved with a newer version cannot be loaded by an older version.

This sacrifice was considered worth the benefit of the fix (qBittorrent relies on creating a torrent from another torrent to produce the exact same result. Previously, if the original torrent had incorrect bencoding, the output would have fixed the encoding producing a different info-hash).

@sledgehammer999 Could you describe how those files in ``BT_backup`` are generated. Is that the output from ``create_torrent``?

@fbriere this happens to all torrents, right? not just torrents with invalid bencoding (very few torrents suffer from this problem generally)

**Comment by arvidn** [comment] 2017-02-12 02:55
@fbriere would you be able to post an example of a truncated torrent? feel free to mail it to me at arvid@libtorrent.org or paste it somewhere

**Comment by arvidn** [comment] 2017-02-12 03:05
actually, I figured it out. The problem is that a new version of libtorrent will produce an ``entry`` tree with a new node type in it (preformatted). The compiled client will then use an inlined encoder function (``bencode.hpp``) which (since it's inlined) will be the old version of the function, which does not understand this new node type. It will fail to encode it properly.

any idea of how to improve this? maybe revert the ``entry`` from not including the new type, but make the encoder support it? maybe there is some way to detect a newer version of the client to start including the new type.

**Comment by arvidn** [comment] 2017-02-12 17:55
@fbriere if you have a chance, please confirm that this patch fixes the issue. i.e. works against a qbt that's built against an old version.

https://github.com/arvidn/libtorrent/pull/1702

If that works, I will apply it to RC_1_1 as well

**Comment by sledgehammer999** [comment] 2017-02-12 18:37
>@sledgehammer999 Could you describe how those files in BT_backup are generated. Is that the output from create_torrent?

I suppose my input isn't needed anymore, but I'll explain anyway. IIRC, qbt creates the files in BT_backup always by using create_torrent, regardless if the original was a .torrent or a magnet link. We switched to that approach to avoid file permission issues, related to the original file being copied.

**Comment by arvidn** [comment] 2017-02-12 19:43
That patch I made will essentially restore the behavior to not preserve (invalid) key orders from .torrent files, unless a different ``create_torrent`` constructor is used explicitly, to allow it. This constructor is new and indicates building against a new version of the library

**Comment by fbriere** [comment] 2017-02-12 20:47
I've successfully tested #1702 with copies of qBittorrent compiled against 1.0.7 and 1.0.10 (before and after the ABI change).

However, this seems to break the qBittorrent (3.3.10) build:

```
../../src/base/bittorrent/torrenthandle.cpp: In member function 'bool BitTorrent::TorrentHandle::saveTorrentFile(const QString&)':
../../src/base/bittorrent/torrenthandle.cpp:1315:70: error: call of overloaded 'create_torrent(libtorrent::torrent_info&)' is ambiguous
     libt::create_torrent torrentCreator(*(m_torrentInfo.nativeInfo()));
                                                                      ^
In file included from ../../src/base/bittorrent/torrenthandle.cpp:41:0:
/usr/include/libtorrent/create_torrent.hpp:182:3: note: candidate: libtorrent::create_torrent::create_torrent(const libtorrent::torrent_info&, int)
   create_torrent(torrent_info const& ti, int libtorrent_version = LIBTORRENT_VERSION_NUM);
   ^~~~~~~~~~~~~~
/usr/include/libtorrent/create_torrent.hpp:177:3: note: candidate: libtorrent::create_torrent::create_torrent(const libtorrent::torrent_info&)
   create_torrent(torrent_info const& ti);
   ^~~~~~~~~~~~~~
/usr/include/libtorrent/create_torrent.hpp:112:24: note: candidate: libtorrent::create_torrent::create_torrent(const libtorrent::create_torrent&)
  struct TORRENT_EXPORT create_torrent
                        ^~~~~~~~~~~~~~
Makefile:1612: recipe for target 'torrenthandle.o' failed
```

(I don't really get the third candidate, but the first two are clearly ambiguous if `libtorrent_version` is omitted.)

**Comment by arvidn** [comment] 2017-02-12 21:07
yeah, I updated the PR a while ago. I gave up on trying to make this transparent to the client. I can't think of a way to do that

**Comment by arvidn** [comment] 2017-02-12 22:56
here's the same patch for 1.1 https://github.com/arvidn/libtorrent/pull/1703

**Comment by fbriere** [comment] 2017-02-13 01:48
Indeed, the latest #1702 (319199d) seems to do the trick.  Thanks!

**Comment by arvidn** [comment] 2017-02-13 02:04
thanks for confirming!

**Comment by arvidn** [comment] 2017-02-14 01:43
both patches have landed

**Closed by arvidn** 2017-02-14 01:43 UTC
