### ISSUE TITLE
Path duplication in libtorrent-rasterbar.pc

### ISSUE THREAD

**Issue by lgbaldoni** [arvidn/libtorrent#5125] opened 2020-09-09 16:02 UTC
**Please provide the following information**

> libtorrent version (or branch):

2.0

>platform/architecture:

openSUSE Tumbleweed x86_64

> compiler and compiler version:

gcc 10

> please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Build with:
```
/usr/bin/cmake /home/abuild/rpmbuild/BUILD/libtorrent-rasterbar-2.0.0/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DCMAKE_INSTALL_LIBEXECDIR=/usr/libexec -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS=-flto=auto -Wl,--as-needed' '-DCMAKE_SHARED_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/lib64/cmake/libtorrent-rasterbar -Dpython-bindings=ON -Dboost-python-module-name=python
```

libtorrent-rasterbar.pc looks like:
```
prefix=/usr
libdir=${prefix}//usr/lib64

Name: libtorrent
Description: Bittorrent library
Version: 2.0.0
Libs: -L${libdir} -ltorrent-rasterbar -L/usr/lib64 -lpthread -lssl -lcrypto -lboost_system
Cflags: -fexceptions -I/usr/include -DTORRENT_LINKING_SHARED -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_NO_DEPRECATED -DTORRENT_USE_OPENSSL -DTORRENT_USE_LIBCRYPTO -DTORRENT_SSL_PEERS -DOPENSSL_NO_SSL2 -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_DYN_LINK
```
(see the libdir line)

Also the Name: line used to be libtorrent-rasterbar with autotools, but perhaps that's secondary.

**Comment by arvidn** [comment] 2020-09-10 11:53
the issue is that `${libdir}` is invalid, right? it ends up `/usr//usr/lib64`

**Comment by arvidn** [comment] 2020-09-10 12:07
@zeule it looks to me that in `cmake/Modules/GeneratePkgConfig/pkg-config.cmake.in` the variable `_INSTALL_LIBDIR` is assumed to not include the prefix, but it is.

I tested this change:

```
index 435413472..73e74ca0d 100644                                                                                                                                                                                                                                           --- a/cmake/Modules/GeneratePkgConfig/pkg-config.cmake.in                                                                                                                                                                                                                   +++ b/cmake/Modules/GeneratePkgConfig/pkg-config.cmake.in
@@ -1,5 +1,4 @@
-prefix=@CMAKE_INSTALL_PREFIX@
-libdir=${prefix}/@_INSTALL_LIBDIR@
+libdir=@_INSTALL_LIBDIR@
 
 Name: @_PROJECT_NAME@
 Description: @_PROJECT_DESCRIPTION@
```

But it still seems something else in there makes that same (incorrect) assumption, as I saw this output when running `make install`:

```
-- Installing: /home/arvid/dev/2/libtorrent/build/./usr/./usr/lib64/cmake/LibtorrentRasterbar/LibtorrentRasterbarTargets.cmake
-- Installing: /home/arvid/dev/2/libtorrent/build/./usr/./usr/lib64/cmake/LibtorrentRasterbar/LibtorrentRasterbarTargets-relwithdebinfo.cmake
-- Installing: /home/arvid/dev/2/libtorrent/build/./usr/./usr/lib64/cmake/LibtorrentRasterbar/LibtorrentRasterbarConfig.cmake
-- Installing: /home/arvid/dev/2/libtorrent/build/./usr/./usr/lib64/cmake/LibtorrentRasterbar/LibtorrentRasterbarConfigVersion.cmake
```

(I had set the prefix to `./usr`)

Alternatively, @lgbaldoni, are you sure you're supposed to specify full paths for all of those cmake variables, and not paths relative to the prefix?

**Comment by lgbaldoni** [comment] 2020-09-10 12:34
> Alternatively, @lgbaldoni, are you sure you're supposed to specify full paths for all of those cmake variables, and not paths relative to the prefix?

That macro works for every other openSUSE package built with cmake. I checked and they are more than 1600.

(I believe it's meson that uses relative paths).

By the way, it looks like https://github.com/arvidn/libtorrent/pull/4928 wasn't merged into RC_1_2.

**Comment by zeule** [comment] 2020-09-10 12:51
> @zeule it looks to me that in `cmake/Modules/GeneratePkgConfig/pkg-config.cmake.in` the variable `_INSTALL_LIBDIR` is assumed to not include the prefix, but it is.

I don't remember and did not look yet, but my .pc file is almost OK (compiled yesterday, the only problem I see is `-I/usr/include`):
```
prefix=/usr
libdir=${prefix}/lib64

Name: libtorrent
Description: Bittorrent library
Version: 2.0.0
Libs: -L${libdir} -ltorrent-rasterbar -lpthread -lssl -lcrypto -lboost_system-mt
Cflags: -fexceptions -I/usr/include -DTORRENT_LINKING_SHARED -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_NO_DEPRECATED -DTORRENT_DISABLE_LOGGING -DTORRENT_USE_OPENSSL -DTORRENT_USE_LIBCRYPTO -DTORRENT_SSL_PEERS -DOPENSSL_NO_SSL2
```

The code relies on the GNUInstallDirs CMake module. There are files in the `torrent-rasterbar-pkgconfig` subdir of the build directory after the install stage, that contain all the strings. Their content shall show what is going on.

**Comment by lgbaldoni** [comment] 2020-09-12 06:52
> There are files in the torrent-rasterbar-pkgconfig subdir of the build directory after the install stage, that contain all the strings. Their content shall show what is going on.

I hope this can [shed](https://github.com/arvidn/libtorrent/files/5212309/libtorrent-rasterbar-2.0.0_pc.tar.gz) some light.

**Comment by zeule** [comment] 2020-09-12 22:09
`CMAKE_INSTALL_LIBDIR`  may not contain installation prefix, but you pass `-DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64` (the same applies to LIBEXEC).

**Comment by lgbaldoni** [comment] 2020-09-13 06:10
I see. Is [this](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) the source? I need to make a good argument with the cmake maintainer on openSUSE.

**Comment by zeule** [comment] 2020-09-13 14:35
Sure, and maybe https://gitlab.kitware.com/cmake/cmake/-/issues/20250 too.

**Comment by lgbaldoni** [comment] 2020-09-14 10:50
@zeule looks like you're right. Still, would you consider using CMAKE_FULL_INSTALL_LIBDIR in that line?

**Comment by krop** [comment] 2020-09-14 11:03
> `CMAKE_INSTALL_LIBDIR` may not contain installation prefix, but you pass `-DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64` (the same applies to LIBEXEC).

This is perfectly fine. Code assuming CMAKE_INSTALL_LIBDIR is relative needs fixing. That's a wrong assumption.

**Comment by zeule** [comment] 2020-09-14 14:04
Thank you, I missed that change (turns out as old as CMake 3.4). As I don't understand how that can work with absolute path in `install(DESTINATION ...)` (do I need to call `make install` as root?), correcting the invocation args seems much saner too me.

**Comment by krop** [comment] 2020-09-14 14:45
Unfortunately, you can't predict how CMake will be invoked :)
But you can decide how you want to treat CMAKE_INSTALL_LIBDIR. An easy fix could be:

```
if(IS_ABSOLUTE "${CMAKE_INSTALL_LIBDIR}")
  file(RELATIVE_PATH CMAKE_INSTALL_LIBDIR "${CMAKE_INSTALL_PREFIX}" "${CMAKE_INSTALL_LIBDIR}")
endif()
```
somewhere in your CMakeLists.txt.

When running eg. `cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib64`, this guarantees CMAKE_INSTALL_LIBDIR will be relative.

**Comment by zeule** [comment] 2020-09-14 14:51
How that could work if I pass `-DCMAKE_INSTALL_PREFIX=/some_path -DCMAKE_INSTALL_LIBDIR=/some_other_path/lib64` (because I can't predict how it will be called)?

**Comment by krop** [comment] 2020-09-14 15:01
> How that could work if I pass `-DCMAKE_INSTALL_PREFIX=/some_path -DCMAKE_INSTALL_LIBDIR=/some_other_path/lib64` (because I can't predict how it will be called)?

Let's see with a test CMakeLists.txt:
```
project(test)

cmake_minimum_required(VERSION 3.5 FATAL_ERROR)

message (STATUS "Original variable: ${CMAKE_INSTALL_LIBDIR}")

if(IS_ABSOLUTE "${CMAKE_INSTALL_LIBDIR}")
  file(RELATIVE_PATH CMAKE_INSTALL_LIBDIR "${CMAKE_INSTALL_PREFIX}" "${CMAKE_INSTALL_LIBDIR}")
endif()

message(STATUS "Relative: ${CMAKE_INSTALL_LIBDIR}")
```
 `% cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/opt/lib64`

Result:

> -- Original variable: /opt/lib64
> -- Relative: ../opt/lib64

**Comment by zeule** [comment] 2020-09-14 15:11
Exactly, the prefix path makes no sense anymore and we would need to generate .pc file without it.

**Comment by krop** [comment] 2020-09-14 15:24
> Exactly, the prefix path makes no sense anymore and we would need to generate .pc file without it.

I don't understand. The code proposed fixes the issue reported here.
With the current libtorrent code, libtorrent-rasterbar.pc would contain:

```
prefix=/usr
libdir=${prefix}//opt/lib64
```
With the suggested change it would contain:
```
prefix=/usr
libdir=${prefix}/../opt/lib64
```

**Comment by zeule** [comment] 2020-09-14 15:46
> The code proposed fixes the issue reported here.

Absolutely agree. I'm just saying that a case with senseless input data requires a workaround that make no sense either.

**Comment by arvidn** [comment] 2020-09-30 06:48
I forget. Was there a fix applied? If not, would someone mind submitting a pull request? (either against `RC_1_2` or `RC_2_0`)

**Comment by lgbaldoni** [comment] 2020-09-30 16:36
@krop I believe that's your cue

**Comment by arvidn** [comment] 2020-11-11 13:11
@krop @zeule the fix you guys are referring to, it's [this one](https://github.com/arvidn/libtorrent/issues/5125#issuecomment-692105851), right?

**Closed** 2020-11-14 19:25 UTC
