### ISSUE TITLE
make check fails in both master and RC_1_1

### ISSUE THREAD

**Issue by zywo** [arvidn/libtorrent#498] opened 2016-02-26 13:02 UTC
master:

```
CXX      test_upnp.o
In file included from /usr/include/boost/smart_ptr/make_shared.hpp:15:0,
                 from /usr/include/boost/make_shared.hpp:15,
                 from /usr/include/boost/smart_ptr.hpp:28,
                 from ../include/libtorrent/settings_pack.hpp:41,
                 from ../include/libtorrent/session_settings.hpp:38,
                 from ../include/libtorrent/i2p_stream.hpp:53,
                 from ../include/libtorrent/socket_type.hpp:40,
                 from ../include/libtorrent/http_connection.hpp:59,
                 from ../include/libtorrent/upnp.hpp:39,
                 from test_upnp.cpp:33:
/usr/include/boost/smart_ptr/make_shared_object.hpp: In instantiation of ‘typename boost::detail::sp_if_not_array<T>::type boost::make_shared(const A1&, const A2&, const A3&, const A4&, const A5&, const A6&) [with T = libtorrent::upnp; A1 = boost::reference_wrapper<boost::asio::io_service>; A2 = boost::asio::ip::address_v4; A3 = std::__cxx11::basic_string<char>; A4 = void (*)(int, const boost::asio::ip::address&, int, const boost::system::error_code&); A5 = void (*)(const char*); A6 = bool; typename boost::detail::sp_if_not_array<T>::type = boost::shared_ptr<libtorrent::upnp>]’:
test_upnp.cpp:164:48:   required from here
/usr/include/boost/smart_ptr/make_shared_object.hpp:988:5: error: no matching function for call to ‘libtorrent::upnp::upnp(const boost::reference_wrapper<boost::asio::io_service>&, const boost::asio::ip::address_v4&, const std::__cxx11::basic_string<char>&, void (* const&)(int, const boost::asio::ip::address&, int, const boost::system::error_code&), void (* const&)(const char*), const bool&)’
     ::new( pv ) T( a1, a2, a3, a4, a5, a6 );
     ^
In file included from test_upnp.cpp:33:0:
../include/libtorrent/upnp.hpp:134:2: note: candidate: libtorrent::upnp::upnp(libtorrent::io_service&, const string&, const portmap_callback_t&, const log_callback_t&, bool)
  upnp(io_service& ios
  ^
../include/libtorrent/upnp.hpp:134:2: note:   candidate expects 5 arguments, 6 provided
../include/libtorrent/upnp.hpp:131:28: note: candidate: libtorrent::upnp::upnp(const libtorrent::upnp&)
 class TORRENT_EXTRA_EXPORT upnp : public boost::enable_shared_from_this<upnp>
                            ^
../include/libtorrent/upnp.hpp:131:28: note:   candidate expects 1 argument, 6 provided
Makefile:1316: recipe for target 'test_upnp.o' failed
make[3]: *** [test_upnp.o] Error 1
make[3]: Leaving directory '/home/$USER/libtorrent/test'
Makefile:1518: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/$USER/libtorrent/test'
Makefile:1808: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/$USER/libtorrent/test'
Makefile:625: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

RC_1_1:

```
CXX      test_upnp.o
In file included from /usr/include/boost/function/detail/maybe_include.hpp:38:0,
                 from /usr/include/boost/function/function5.hpp:11,
                 from ../include/libtorrent/http_connection.hpp:40,
                 from ../include/libtorrent/upnp.hpp:39,
                 from test_upnp.cpp:33:
/usr/include/boost/function/function_template.hpp: In instantiation of ‘static void boost::detail::function::void_function_invoker5<FunctionPtr, R, T0, T1, T2, T3, T4>::invoke(boost::detail::function::function_buffer&, T0, T1, T2, T3, T4) [with FunctionPtr = void (*)(int, const boost::asio::ip::address&, int, const boost::system::error_code&); R = void; T0 = int; T1 = boost::asio::ip::address; T2 = int; T3 = int; T4 = const boost::system::error_code&]’:
/usr/include/boost/function/function_template.hpp:940:38:   required from ‘void boost::function5<R, T1, T2, T3, T4, T5>::assign_to(Functor) [with Functor = void (*)(int, const boost::asio::ip::address&, int, const boost::system::error_code&); R = void; T0 = int; T1 = boost::asio::ip::address; T2 = int; T3 = int; T4 = const boost::system::error_code&]’
/usr/include/boost/function/function_template.hpp:728:7:   required from ‘boost::function5<R, T1, T2, T3, T4, T5>::function5(Functor, typename boost::enable_if_c<boost::type_traits::ice_not<boost::is_integral<Functor>::value>::value, int>::type) [with Functor = void (*)(int, const boost::asio::ip::address&, int, const boost::system::error_code&); R = void; T0 = int; T1 = boost::asio::ip::address; T2 = int; T3 = int; T4 = const boost::system::error_code&; typename boost::enable_if_c<boost::type_traits::ice_not<boost::is_integral<Functor>::value>::value, int>::type = int]’
/usr/include/boost/function/function_template.hpp:1077:16:   required from ‘boost::function<R(T0, T1, T2, T3, T4)>::function(Functor, typename boost::enable_if_c<boost::type_traits::ice_not<boost::is_integral<Functor>::value>::value, int>::type) [with Functor = void (*)(int, const boost::asio::ip::address&, int, const boost::system::error_code&); R = void; T0 = int; T1 = boost::asio::ip::address; T2 = int; T3 = int; T4 = const boost::system::error_code&; typename boost::enable_if_c<boost::type_traits::ice_not<boost::is_integral<Functor>::value>::value, int>::type = int]’
/usr/include/boost/smart_ptr/make_shared_object.hpp:988:5:   required from ‘typename boost::detail::sp_if_not_array<T>::type boost::make_shared(const A1&, const A2&, const A3&, const A4&, const A5&, const A6&) [with T = libtorrent::upnp; A1 = boost::reference_wrapper<boost::asio::io_service>; A2 = boost::asio::ip::address_v4; A3 = std::__cxx11::basic_string<char>; A4 = void (*)(int, const boost::asio::ip::address&, int, const boost::system::error_code&); A5 = void (*)(const char*); A6 = bool; typename boost::detail::sp_if_not_array<T>::type = boost::shared_ptr<libtorrent::upnp>]’
test_upnp.cpp:164:48:   required from here
/usr/include/boost/function/function_template.hpp:118:11: error: invalid initialization of reference of type ‘const boost::system::error_code&’ from expression of type ‘int’
           BOOST_FUNCTION_RETURN(f(BOOST_FUNCTION_ARGS));
           ^
Makefile:1260: recipe for target 'test_upnp.o' failed
make[3]: *** [test_upnp.o] Error 1
make[3]: Leaving directory '/home/$USER/libtorrent/test'
Makefile:1462: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/$USER/libtorrent/test'
Makefile:1745: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/$USER/libtorrent/test'
Makefile:625: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by arvidn** [comment] 2016-02-28 05:37
it works for me, in RC_1_1 on OSX with Apple LLVM 7.0.2 and boost 1.59.
What OS, compiler and boost version are you on?

**Comment by zywo** [comment] 2016-02-28 06:02
Ubuntu 15.10
boost 1.58.0
gcc/g++ 5.2.1

**Comment by arvidn** [comment] 2016-02-28 06:10
ok. I actually spoke too soon. I accidentally ran it on RC_1_0. I see errors in RC_1_1 too

**Comment by arvidn** [comment] 2016-02-28 07:21
does this fix it for you? (this is RC_1_1 for now, if this looks good I will merge it down stream)

**Comment by zywo** [comment] 2016-02-28 07:55
It still fails.


[test_build.txt](https://github.com/arvidn/libtorrent/files/149792/test_build.txt)

**Comment by arvidn** [comment] 2016-02-28 15:42
I see. you have to pass in --enable-tests for the tests to link. The reason for this is that the unit tests actually test internal types and functions in libtorrent, that aren't normally exported. the --enable-tests flag make the library export more types and functions that the unit tests refer to. I'm not automake savvy enough to make this a bit more user friendly. say, make could tell you that it wasn't configured to run the tests. (patches are welcome!)

**Comment by zywo** [comment] 2016-02-28 20:12
In 1.0.8, it works without passing that option.

Now "make check" works in RC_1_1 branch after passing --enable-tests option to ./configure.

But qBittorrent crashs after resume a paused torrent. I don't know if it's qbittorrent or libtorrent issue.

```
Catching signal: SIGSEGV
Please file a bug report at http://bug.qbittorrent.org and provide the following information:

qBittorrent version: v3.4.0alpha
stack trace:
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xeee1e  [0x7f4d8a198e1e]
  /usr/lib/libtorrent-rasterbar.so.9 : libtorrent::unchoke_sort(std::vector<libtorrent::peer_connection*, std::allocator<libtorrent::peer_connection*> >&, int, boost::chrono::duration<long, boost::ratio<1l, 1000000000l> >, libtorrent::aux::session_settings const&)+0x67d  [0x7f4d8a199f9d]
  /usr/lib/libtorrent-rasterbar.so.9 : libtorrent::aux::session_impl::recalculate_unchoke_slots()+0x2ad  [0x7f4d8a2e9fed]
  /usr/lib/libtorrent-rasterbar.so.9 : libtorrent::aux::session_impl::on_tick(boost::system::error_code const&)+0xf30  [0x7f4d8a2fb9b0]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2589dd  [0x7f4d8a3029dd]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x20c0ba  [0x7f4d8a2b60ba]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x10ab4f  [0x7f4d8a1b4b4f]
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x76aa  [0x7f4d89c8f6aa]
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x6d  [0x7f4d87723e9d]
Segmentation fault (core dumped)
```

**Comment by arvidn** [comment] 2016-02-28 20:55
that looks like a problem in libtorrent. would you have the ability to run that in a debugger and provide some more information about where that crash happens, which variable it's accessing that's corrupt?

**Comment by zywo** [comment] 2016-02-28 22:29
under gdb:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd2975700 (LWP 23906)]
0x00007ffff766291e in ?? () from /usr/lib/libtorrent-rasterbar.so.9
(gdb) bt
#0  0x00007ffff766291e in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#1  0x00007ffff7663a9d in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#2  0x00007ffff77b414d in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#3  0x00007ffff77c5ca3 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#4  0x00007ffff77ccced in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#5  0x00007ffff778014a in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#6  0x00007ffff767e69f in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#7  0x00007ffff71976aa in start_thread (arg=0x7fffd2975700) at pthread_create.c:333
#8  0x00007ffff4c2be9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by zywo** [comment] 2016-02-29 08:38
Some more tests, libtorrent RC_1_1 compiled with --enable-debug.

under gdb:

```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.1.0.0-7f05551

file: 'session_impl.cpp'
line: 6952
function: void libtorrent::aux::session_impl::check_invariant() const
expression: m_stats_counters[counters::num_unchoke_slots] == (std::numeric_limits<int>::max)()

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2: 
3: 
4: 
5: 
6: 
7: 
8: 
9: 
10: clone


Program received signal SIGINT, Interrupt.
[Switching to Thread 0x7fffda7fc700 (LWP 22682)]
0x00007ffff70f3bd9 in raise (sig=2) at ../sysdeps/unix/sysv/linux/pt-raise.c:36
36	../sysdeps/unix/sysv/linux/pt-raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff70f3bd9 in raise (sig=2) at ../sysdeps/unix/sysv/linux/pt-raise.c:36
#1  0x00007ffff75989f8 in assert_fail(char const*, int, char const*, char const*, char const*, int) () from /usr/lib/libtorrent-rasterbar.so.9
#2  0x00007ffff7743288 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#3  0x00007ffff77691b9 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#4  0x00007ffff7745164 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#5  0x00007ffff774ee07 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#6  0x00007ffff776666a in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#7  0x00007ffff7703ea1 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#8  0x00007ffff75e53ef in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#9  0x00007ffff70ea6aa in start_thread (arg=0x7fffda7fc700) at pthread_create.c:333
#10 0x00007ffff4b7ee9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) l
31	in ../sysdeps/unix/sysv/linux/pt-raise.c
(gdb)
```

**Comment by arvidn** [comment] 2016-02-29 23:36
could you build with debug symbols on? (--enable-debug iirc)

**Comment by zywo** [comment] 2016-03-01 06:37
Look at my post above.

> Some more tests, libtorrent RC_1_1 compiled with --enable-debug.

**Comment by arvidn** [comment] 2016-03-01 06:59
there are no debug symbol in that binary. perhaps --enable-debug does not add -g, but I would be surprised if that's the case. are you sure the new build got installed over the previous build correctly?

**Comment by zywo** [comment] 2016-03-01 07:24
After running "./configure --prefix=/usr --enable-debug" I checked the makefile and -g is added to 3 FLAGS:
```
CFLAGS = -pthread -g -O2 -fvisibility=hidden
CXXFLAGS = -g -O2 -ftemplate-depth=120 -fvisibility=hidden -fvisibility-inlines-hidden
DEBUGFLAGS = -g
```

My steps to build and install libtorrent:
```
- sudo make uninstall
- make distclean
- ./configure --prefix=/usr --enable-debug
- make clean
- make -j$(nproc)
- sudo make install
```

**Comment by arvidn** [comment] 2016-03-02 06:40
I believe this fixes that issue. could please give it a try?
https://github.com/arvidn/libtorrent/pull/514

**Comment by zywo** [comment] 2016-03-02 20:03
libtorrent and qbittorent builds in progress.

P.S: I would like to report a strange behavior: this issue doesn't occur on ubuntu 14.04 LTS, only on 15.10 and 16.04 (fresh and clean install).

**Comment by zywo** [comment] 2016-03-02 20:16
Same problem with https://github.com/arvidn/libtorrent/pull/514

```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.1.0.0-7f05551

file: 'disk_io_thread.cpp'
line: 1238
function: int libtorrent::disk_io_thread::do_read(libtorrent::disk_io_job*, libtorrent::jobqueue_t&)
expression: false

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2: 
3: 
4: 
5: 
6: 
7: 
8: 
9: clone


Program received signal SIGINT, Interrupt.
[Switching to Thread 0x7fffd8ff9700 (LWP 26870)]
0x00007ffff70f3bd9 in raise (sig=2) at ../sysdeps/unix/sysv/linux/pt-raise.c:36
36	../sysdeps/unix/sysv/linux/pt-raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff70f3bd9 in raise (sig=2) at ../sysdeps/unix/sysv/linux/pt-raise.c:36
#1  0x00007ffff75989f8 in assert_fail(char const*, int, char const*, char const*, char const*, int) () from /usr/lib/libtorrent-rasterbar.so.9
#2  0x00007ffff75e20d0 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#3  0x00007ffff75de912 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#4  0x00007ffff75e02ca in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#5  0x00007ffff75e3477 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#6  0x00007ffff75e56f6 in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#7  0x00007ffff75e53ef in ?? () from /usr/lib/libtorrent-rasterbar.so.9
#8  0x00007ffff70ea6aa in start_thread (arg=0x7fffd8ff9700) at pthread_create.c:333
#9  0x00007ffff4b7ee9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) l
31	in ../sysdeps/unix/sysv/linux/pt-raise.c
(gdb)
```

**Comment by arvidn** [comment] 2016-03-02 22:10
that looks like a different assert to me...

**Comment by arvidn** [comment] 2016-03-03 00:20
that's actually a pretty interesting failure. Is that reproducible for you? by one of the tests? if so, do you know which one?

**Comment by arvidn** [comment] 2016-03-03 06:13
if you hit that assert in the debugger again, would you mind posting a backtrace of the other threads as well?

**Comment by zywo** [comment] 2016-03-03 11:51
> that's actually a pretty interesting failure. Is that reproducible for you? by one of the tests? if so, do you know which one?

What tests?

> if you hit that assert in the debugger again, would you mind posting a backtrace of the other threads as well?

What threads?

**Comment by arvidn** [comment] 2016-03-03 13:17
when you encounter it in gdb, instead of calling "bt", run "thread apply all bt" to print the stack of all threads in the process.

I believe "make check" builds and runs all the tests under the tests directory

**Comment by zywo** [comment] 2016-03-03 14:10
I hope these back-traces may help you.
 
[RC_1_1_backtrace.txt](https://github.com/arvidn/libtorrent/files/156871/RC_1_1_backtrace.txt)
[RC_1_1_debug_backtrace.txt](https://github.com/arvidn/libtorrent/files/156872/RC_1_1_debug_backtrace.txt)
[RC_1_1_thread_apply_all_bt.txt](https://github.com/arvidn/libtorrent/files/156874/RC_1_1_thread_apply_all_bt.txt)
[allowed-unchoke-1.1_thread_apply_all_bt.txt](https://github.com/arvidn/libtorrent/files/156876/allowed-unchoke-1.1_thread_apply_all_bt.txt)

**Comment by arvidn** [comment] 2016-03-04 05:17
I made another attempt at fixing the allowed upload slots assert

**Comment by zywo** [comment] 2016-03-04 07:39
Same problem.

[514.txt](https://github.com/arvidn/libtorrent/files/158272/514.txt)

**Comment by arvidn** [comment] 2016-03-04 21:41
this is a different assert. which makes me think the unchoke slots one may be fixed at least. The disk io thread asserts (this last one and one of the previous asserts) are more difficult to track. I'm a bit surprised you hit all these asserts. it's possible qbittorrent uses a sufficiently different configuration than I'm used to test perhaps. the ones in the disk I/O though, I wonder if there's some heap corruption issue involved there.

Is there anything about your system you'd say is unusual?

**Comment by zywo** [comment] 2016-03-05 20:44
I just tested the current RC_1_1, and the problem is still present.
After that, I tested the new PR disk-cache-1.1(https://github.com/arvidn/libtorrent/pull/523) and the issue is gone (at least for now).

**Comment by arvidn** [comment] 2016-03-06 21:28
As the disk-cache-1.1 branch has landed, I believe this solves the remaining asserts you encountered.

**Closed by arvidn** 2016-03-06 21:28 UTC

**Comment by zywo** [comment] 2016-03-07 05:07
Yes.
Thank you.
