### ISSUE TITLE
setup.py using b2 has broken make installs on RC_1_2

### ISSUE THREAD

**Issue by liaralabs** [arvidn/libtorrent#5763] opened 2020-12-21 19:27 UTC
**Please provide the following information**

libtorrent version (or branch):
RC_1_2 at b87d01292a11af2d3dad1c91dbd27bd90d04350a

platform/architecture:
amd64
Debian 10

compiler and compiler version:
gcc8.3

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I understand boost builds are the future of this project and I am working on migrating my build process over to `b2`; however, this is quite an undertaking and I haven't yet had the time to devote to rewriting the scripts to make this happen. Thus, my build scripts are currently utilizing `make` to build libtorrent as they have for some time.

The biggest issue I can see right now is that `make` produces a library called `libtorrent-rasterbar` and `b2` produces a library called `libtorrent`.

As it stands, if you configure and make libtorrent with the python binding while using `make`, the compiler will go through and make the `libtorrent-rasterbar` library then call `b2` once setup.py is called, which then goes through the trouble of recompiling the entire `libtorrent` library followed by the python shared object, but it will then link the shared object to `libtorrent.so.1.2.11` which will cause an import failure due to the installed library being called `libtorrent-rasterbar.so`.

Reproducible build method which is now failing causing an import error due to `libtorrent.so` not found:

```
./autotool.sh
PYTHON=python3 ./configure --enable-python-binding --with-libiconv --with-boost-python=boost_python3 CXXFLAGS=-std=c++14
make -j$(nproc)
make install
python3 -c "import libtorrent"
ImportError: libtorrent.so.1.2.11: cannot open shared object file: No such file or directory
```
As it stands, the python binding can no longer be created correctly while utilizing `make`, which seems like a very big change for a minor point release. Also, it seems like cxxflags and the `-j` make argument are not being passed to the python build command either.

Attached is the build log and final result/errors given by the steps above.

[make.log](https://github.com/arvidn/libtorrent/files/5726074/make.log)

**Comment by arvidn** [comment] 2020-12-22 00:36
I believe covering this in CI went away with travis. I forgot to convert this to github actions

**Comment by arvidn** [comment] 2020-12-22 01:47
does this fix it for you? https://github.com/arvidn/libtorrent/pull/5767

**Comment by liaralabs** [comment] 2020-12-22 02:17
Unfortunately, it looks like I'm still receiving the same error at the end of the steps above:

```
root@debian-4gb-hel1-1:/tmp/libtorrent# python3 -c "import libtorrent"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libtorrent.so.1.2.11: cannot open shared object file: No such file or directory
```
end of the build log
```
gcc.link.dll ../../bin/gcc-8.3.0/release/address-model-64/lt-visibility-hidden/threading-multi/libtorrent.so.1.2.11
gcc.link.dll bin/gcc-8.3.0/release/address-model-64/lt-visibility-hidden/libtorrent.cpython-37m-x86_64-linux-gnu.so
common.copy build/lib.linux-x86_64-3.7/libtorrent.cpython-37m-x86_64-linux-gnu.so
...updated 195 targets...
make[2]: Leaving directory '/tmp/libtorrent/bindings/python'
make[2]: Entering directory '/tmp/libtorrent/bindings'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/tmp/libtorrent/bindings'
make[1]: Leaving directory '/tmp/libtorrent/bindings'
```

ldd on the shared object
```
root@debian-4gb-hel1-1:/usr/local/lib/python3.7/dist-packages/python_libtorrent-1.2.11-py3.7-linux-x86_64.egg# ldd libtorrent.cpython-37m-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffd8276f000)
        libtorrent.so.1.2.11 => not found
        libboost_python37.so.1.67.0 => /lib/x86_64-linux-gnu/libboost_python37.so.1.67.0 (0x00007fdc3609e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc36099000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdc36078000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fdc36073000)
        libboost_system.so.1.67.0 => /lib/x86_64-linux-gnu/libboost_system.so.1.67.0 (0x00007fdc3606c000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdc35ee6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdc35d63000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdc35d49000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc35b88000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdc35b7e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdc362e2000)
```

**Comment by liaralabs** [comment] 2020-12-22 02:30
Wait ignore that previous message :unamused: I did a `git pull` but did not apply the patch :roll_eyes:

**Comment by liaralabs** [comment] 2020-12-22 02:50
Okay, progress here at least, but the library itself still has the wrong numbering:

```
root@debian-4gb-hel1-1:/tmp/libtorrent# python3 -c "import libtorrent"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libtorrent-rasterbar.so.1.2.11: cannot open shared object file: No such file or directory
```

`ls -la /usr/local/lib`:
```
-rw-r--r--  1 root root 19316518 Dec 22 03:44 libtorrent-rasterbar.a
-rwxr-xr-x  1 root root     1066 Dec 22 03:44 libtorrent-rasterbar.la
lrwxrwxrwx  1 root root       30 Dec 22 03:44 libtorrent-rasterbar.so -> libtorrent-rasterbar.so.10.0.0
lrwxrwxrwx  1 root root       30 Dec 22 03:44 libtorrent-rasterbar.so.10 -> libtorrent-rasterbar.so.10.0.0
-rwxr-xr-x  1 root root  4668416 Dec 22 03:44 libtorrent-rasterbar.so.10.0.0
```

Oddly enough, it's not enough to just create a link to libtorrent-rasterbar.1.2.11 in `/usr/local/lib` -- it needs to be in `/usr/lib`; however, working around this numbering/naming issue, once that link is created this error presents:

```
root@debian-4gb-hel1-1:/usr/local/lib# ln -s /usr/local/lib/libtorrent-rasterbar.so.10.0.0 /usr/lib/libtorrent-rasterbar.so.1.2.11
root@debian-4gb-hel1-1:/usr/local/lib# ldconfig
root@debian-4gb-hel1-1:/usr/local/lib# python3 -c "import libtorrent"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/lib/python3.7/dist-packages/python_libtorrent-1.2.11-py3.7-linux-x86_64.egg/libtorrent.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK10libtorrent5entry4dictEv
```

I'm guessing this is because the project was built with c++14 but the python object then used c++11

**Comment by arvidn** [comment] 2020-12-22 11:46
yes, that's caused by the library being built with C++14 and the python module being built with C++11. There was an unfortunate issue I introduced a while ago in libtorrent 1.2. This has been addressed in libtorrent 2.0, to (attempt) to make C++ version not affect ABI.

**Comment by arvidn** [comment] 2020-12-22 22:42
I updated the patch to fix the library version number as well as propagate the `-std=c++` compiler flag to the python module. Would you mind testing the new patch?

**Comment by liaralabs** [comment] 2020-12-23 09:30
No errors as far as I can see and a clean import with python3. Looks like these 3 commits solved this for me.

**Closed** 2020-12-27 23:01 UTC
