### ISSUE TITLE
function: bool libtorrent::dht::routing_table::add_node

### ISSUE THREAD

**Issue by zz64** [arvidn/libtorrent#108] opened 2015-08-21 16:50 UTC
Hi,
using 1.0.6 from releases, qBittorrent crash.
```
Clearing torrent properties
clearing peer list
clear called
QSpiAccessible::accessibleEvent not handled:  "8008"  obj:  QObject(0x0)  " invalid interface!" 
QString::arg: Argument missing: "Sans Catégorie" , 0 
Torrent deleted.
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 20 (X_GetProperty)
  Resource id:  0x3800175
Changed tab to search engine, giving focus to search input
Changed tab to search engine, giving focus to search input
Search with category: all
Search with category: all
Search with category: all
Changed tab to transfer list, refreshing the list
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.0.6.0
$Rev$

file: 'kademlia/routing_table.cpp'
line: 458
function: bool libtorrent::dht::routing_table::add_node(libtorrent::dht::node_entry)
expression: m_buckets.size() <= 50


stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2: 
3: 
4: 
5: 
6: 
7: 
8: 
9: 
10: 
11: 
12: 
13: 
14: 
15: boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&)
16: boost::asio::detail::task_io_service::run(boost::system::error_code&)
17: 
18: boost_asio_detail_posix_thread_function
19: 
20: clone
Catching SIGINT, exiting cleanly

*************************************************************
Catching SIGABRT, please report a bug at http://bug.qbittorrent.org
and provide the following backtrace:
qBittorrent version: v3.3.0beta
stack trace:
  /lib/x86_64-linux-gnu/libc.so.6 : gsignal()+0x37  [0x7fe6c2b7c107]
  /lib/x86_64-linux-gnu/libc.so.6 : abort()+0x148  [0x7fe6c2b7d4e8]
  /usr/local/lib/libtorrent-rasterbar.so.8 : assert_fail(char const*, int, char const*, char const*, char const*, int)+0xaa  [0x7fe6c55a9b3a]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x2df9c0  [0x7fe6c58069c0]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x2dfb3e  [0x7fe6c5806b3e]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x2e8e21  [0x7fe6c580fe21]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x2e8fa0  [0x7fe6c580ffa0]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x2ce999  [0x7fe6c57f5999]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x2ecb71  [0x7fe6c5813b71]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x2e5a36  [0x7fe6c580ca36]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x2d4f5e  [0x7fe6c57fbf5e]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x2c5a45  [0x7fe6c57eca45]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x28e4d2  [0x7fe6c57b54d2]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x28f24f  [0x7fe6c57b624f]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x28f5a2  [0x7fe6c57b65a2]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x293db5  [0x7fe6c57badb5]
  /usr/local/lib/libtorrent-rasterbar.so.8 : boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&)+0x2ac  [0x7fe6c559fafc]
  /usr/local/lib/libtorrent-rasterbar.so.8 : boost::asio::detail::task_io_service::run(boost::system::error_code&)+0xd1  [0x7fe6c55a3841]
  /usr/local/lib/libtorrent-rasterbar.so.8 : ()+0x1ce720  [0x7fe6c56f5720]
  /usr/local/lib/libtorrent-rasterbar.so.8 : boost_asio_detail_posix_thread_function()+0x42  [0x7fe6c55a3a32]
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x80a4  [0x7fe6c510e0a4]
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x6d  [0x7fe6c2c2d04d]
Abandon
```
Debian jessie amd64
boost 1.55.0+dfsg-3
gcc-4.9 (g++-4.9) 4.9.2-10
kernel Linux 4.1.3 amd64

Thanks.

**Comment by arvidn** [comment] 2015-08-21 20:55
duplicate of https://github.com/arvidn/libtorrent/issues/107

**Closed by arvidn** 2015-08-21 20:55 UTC
