### ISSUE TITLE
qBittorrent outgoing traffic ends up in too big UDP datagrams; immediate fragmentation

### ISSUE THREAD

**Issue by D33M0N** [arvidn/libtorrent#5836] opened 2021-01-08 13:09 UTC
**Please provide the following information**
For starters I opened a bugreport also under qBittorrent directly, where they suggested to open one here also (as they apparently use libtorrent, which apparently is responsible for the traffic shaping?).
https://github.com/qbittorrent/qBittorrent/issues/14180

(
Also the problem was found probing another NIC driver crash issue :D
https://bugzilla.kernel.org/show_bug.cgi?id=209839
)

libtorrent version (or branch):
Libtorrent 1.2.10.0

platform/architecture:
Manjaro linux
qBittorrent v4.3.1 64bit

compiler and compiler version:
no idea.

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

for some reason SOME (not all) UDP traffic from qBittorrent is send out to local NIC in 1480 byte payload chunks (1488 byte UDP datagram), which would end up in 1508 byte IP packet, but since my NIC MTU is 1500, it gets immidiately fragmented into 2 pieces. Which is just BAD for multiple reasons.

How to produce: start downloading some stuff with torrent... preferably something from questionable origin and/or questionable legality, so you download from real users, not some corporate server, and people actually want you to upload stuff also (rarely happens when you torrent lets say Ubuntu installer iso.). Wait a while. Capture traffic with Wireshark or something.

one example of such badly fragmented outgoing traffic: https://bugzilla.kernel.org/attachment.cgi?id=294519
(which ended up fragmenting the packet immidiately into 1472 + 8 byte data chunks; which totally unrelated to this fragmentation issue here, the second part ended up being encapsulated into too small ethernet frame (runt frame) which caused the nic hw crash; yes, the driver fix/workaround can fix the issue there, but the fragmentation in the first hop should never happen in the first place.)

**Comment by arvidn** [comment] 2021-01-08 21:25
thanks for the report! excellent with a pcap file up-front!

the example packet in the pcap is definitely odd, the maximum packet size to be used should be 1500 - sizeof(ipv4) - sizeof(udp). However, the full story about fragmented packets is a bit more involved.

libtorrent implements path MTU discovery. This turns out to be necessary because there are too many users whose traffic is wrapped in additional layers, causing an effective smaller MTU than a clean ethernet+ipv4+udp link. There is not reasonable "sweet spot" where a fixed maximum MTU works for everyone without causing performance degradations for others (that *have* larger MTUs).

The MTU discovery is a binary search between a floor (based on the minimum guaranteed MTU on the internet) and a ceiling (which I'll describe below). The effective MTU for a specific uTP connection starts off in the middle. Once each congestion window (i.e. once each RTT) one packet is sent as an MTU probe, with the do-not-fragment bit set. If the probe is lost, it's taken to mean the MTU is lower and the ceiling is lowered to just below the dropped probe. However, the uTP protocol is quite simple and doesn't support re-packetization, so the lost probe still needs to be sent as a fragmented packet. This should only happen infrequently.

The MTU ceiling is determined based on:

* whether the destination address is a Teredo address (teredo links have much smaller effective MTUs).
* whether the destination address is IPv4 or IPv6 (since those headers differ in size)
* whether a SOCKS5 proxy is configured for the client (since the SOCKS5 UDP wrapper eats into the effective MTU)

The code for this logic is found [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/utp_socket_manager.cpp#L91).

Looking at that code, the one case I can think of where it would produce packets larger than the MTU would be if you use a SOCKS5 proxy that you contact over an IPv6 address. Currently the assumption in there is that the SOCKS5 proxy is reached via IPv4. However, in the pcap it's clear that both endpoints are IPv4, so this shouldn't be the case you hit.

Could you share some more details of your setup? Do you use a proxy?

**Comment by D33M0N** [comment] 2021-01-09 04:39
No proxy, no vpn (usually; at least not in this case), normal ethernet connection.
Could there be any reason or scenario how the starting mtu size (in this case 1508?) before subtractions might be bigger (different? usually smaller but somehow ended up being larger?) from the NIC set mtu (1500)?

**Comment by arvidn** [comment] 2021-01-11 00:55
@D33M0N that pcap file, is that a sample of bittorrent traffic that you're seeing?

I ask because the only case that I've suspected so far, is when a packet in the send buffer is being re-sent and its packet header is updated with additional extensions. I don't see *any* extensions in the uTP headers in your pcap though.

The uTP packet header allows for arbitrary header extensions, similar to to IP. The only extension there is (currently) is selective-ack. Which is a bitfield indicating which packets have been received and which ones haven't. The uTP header is stored with the outgoing packets in the send buffer, and when a packet is re-sent, its header has to be updated. Most notably, the current ACK sequence number is likely to have changed. If there's a selective ACK message in the header, it will also be updated.

Looking closer at the code however, it turns out that *if* there is a selective ACK header, and there are still unacked packets, the existing header field is updated in place, and not extended. So I believe this is a dead-end anyway.

I found one issue where a packet that's larger than the current effective MTU may be sent, but only if it's the nagle-packet, and it was initially allocated with a larger MTU was in effect. However, it doesn't explain how a packet could exceed the MTU *ceiling*.

**Comment by D33M0N** [comment] 2021-01-11 02:52
> is that a sample of bittorrent traffic that you're seeing?

yes. qBittorrent to be specific. Just cut out the portion where it caused the driver r8619 to crash to the driver people can figure out how to fix the driver part (add padding to runt frames in this case... because this particular HW piece doesn't do it on it's own.).

I can provide a larger file (like, what came before) of this if this helps somehow to detect the potential problem? though it's like 40MB and it allows only to upload like 10MB here.

**Comment by arvidn** [comment] 2021-01-11 10:26
Wireshark does not display fragmented (and re-assembled) packets very clearly and intuitively I think. When I disabled this feature in Wireshark to see the packets, as fragments, I think it becomes clearer what's happening. (not necessarily why it's happening though).

**Assumptions**

The basic assumptions in libtorrent (and my understanding) is that the normal [ethernet frame](https://en.wikipedia.org/wiki/Ethernet_frame) can carry 1500 bytes of payload. The ethernet preamble, header and frame-check-sequence are in *addition* to those 1500 bytes. So, payload + uTP_header + UDP_header + IP_header all have exactly 1500 bytes to fit in. Specifically on your network, there's no PPPoE headers or anything else eating into those bytes.

The Ethernet header is typically 14 bytes (dst MAC, src MAC, Ethertype).

The normal IPv4 header (without any options set) is 20 bytes.

The UDP header is 8 bytes.

This leaves 1500 - 20 - 8 = 1472 bytes for libtorrent to put the uTP header + payload in.

**Analysis**

There are a handful of example packets in the capture, I will just consider the first one. The others look similar.

There's a packet of total size 1505 Bytes. Wireshark shows the first 14 bytes to be the ethernet header (14 bytes), leaving just 1491 Bytes for the IP packet. It appears the effective MTU on this hardware is 1491 rather than 1500.

The reassembled IP packet shows that the payload is exactly 1472, which is what libtorrent would expect to be available.

Now, the question is, do you see any packets with the dont-fragment flag set? Perhaps they are dropped by the kernel and wouldn't show up in a capture, but I would expect the true MTU to be discovered by libtorrent via those probes.

**Comment by D33M0N** [comment] 2021-01-11 13:03
> Assumptions

They are generally correct. Except that the default Ethernet frame is actually 1518 bytes, because there is also 4 byte checksum in the end, which Wireshark does not record nor show. So it's like 14 ethernet header + 1500 mtu + 4 ethernet checksum.

> There's a packet of total size 1505 Bytes. Wireshark shows the first 14 bytes to be the ethernet header (14 bytes), leaving just 1491 Bytes for the IP packet. It appears the effective MTU on this hardware is 1491 rather than 1500.
> 
> The reassembled IP packet shows that the payload is exactly 1472, which is what libtorrent would expect to be available.
> 
> Now, the question is, do you see any packets with the dont-fragment flag set? Perhaps they are dropped by the kernel and wouldn't show up in a capture, but I would expect the true MTU to be discovered by libtorrent via those probes.

No. The "true MTU" is 1500. I have no clue where you got the impression it might not be.
```
$ ping -M do -s 1472 1.1.1.2
PING 1.1.1.2 (1.1.1.2) 1472(1500) bytes of data.
1480 bytes from 1.1.1.2: icmp_seq=1 ttl=59 time=2.28 ms
1480 bytes from 1.1.1.2: icmp_seq=2 ttl=59 time=2.16 ms
1480 bytes from 1.1.1.2: icmp_seq=3 ttl=59 time=2.19 ms
1480 bytes from 1.1.1.2: icmp_seq=4 ttl=59 time=2.17 ms
```
(IP + ICMP headers are also 28 bytes, like for IP + UDP)

The part you seem to misunderstand is, how this fragmentation and MTU size selection and stuff work exactly.
Read this: https://en.wikipedia.org/wiki/Path_MTU_Discovery
quote: "For IPv4 packets, Path MTU Discovery works by setting the Don't Fragment (DF) flag bit in the IP headers of outgoing packets. Then, any device along the path whose MTU is smaller than the packet will drop it, and send back an Internet Control Message Protocol (ICMP) Fragmentation Needed (Type 3, Code 4) message containing its MTU, allowing the source host to reduce its Path MTU appropriately. The process is repeated until the MTU is small enough to traverse the entire path without fragmentation."

is it possible that some device sends back ICMP type 3, code 4 with it's larger mtu than local, and then libtorrent or something blindly accepts it and doesn't even compare it to local ceiling?

I don't know **exactly** how this works, but lets say my computer sends out "probe packet" 10kB, which obviously should trigger the fragmentation and PMTUD ICMP reply, but the reply comes back with like proposing it's MTU 1508? And then libtorrent somehow thinks, that it's OK to use it even though it's larger than locally possible? Maybe?

**Comment by arvidn** [comment] 2021-01-11 13:24
> No. The "true MTU" is 1500. I have no clue where you got the impression it might not be.

I get the impression from your IP stack fragmenting a UDP packet that *would have fit* in 1500 bytes.

> The part you seem to misunderstand is, how this fragmentation and MTU size selection and stuff work exactly.

Where do you get that impression from? I implemented PMTUD.

> is it possible that some device sends back ICMP type 3, code 4 with it's larger mtu than local, and then libtorrent or something blindly accepts it and doesn't even compare it to local ceiling?

It's complicated to handle incoming ICMP messages at the application layer, in a platform agnostic way. libtorrent does not do that. In fact, uTorrent has some limited support. But on the internet, those ICMP messages are filtered surprisingly often. They are not particularly useful in practice.

> I don't know exactly how this works, but lets say my computer sends out "probe packet" 10kB, which obviously should trigger the fragmentation and PMTUD ICMP reply, but the reply comes back with like proposing it's MTU 1508? And then libtorrent somehow thinks, that it's OK to use it even though it's larger than locally possible? Maybe?

The MTU ceiling is initialized to 1472 and only ever decreased when a probe (with the DF flag set) is lost. It's rare that you actually get an ICMP Packet too big response back, in practice. libtorrent does not handle ICMP responses.

If you look at the pcap file, you'll notice that the fragmented packet carries exactly 1472 bytes of payload. It was fragmented, presumably, because the IP stack thought your network's MTU was smaller than 1500.

**Comment by arvidn** [comment] 2021-01-11 13:29
> I think it shows quite clearly.

You'll notice that you can see the raw first fragment, but there's no way to see the "raw" second fragment, because that slot is where the reassembled packet is. You'll also notice that if you drill down into the headers, you don't necessarily know which IP header is shown for the reassembled packet, nor where in the final buffer it belongs, because there are multiple buffers, the bottom pane, with hex, switches between different buffers as you move across different headers.

The "size" column show 42 bytes, but the buffer is clearly larger than that, but it also switches around to different buffers.

Also, in my version of wireshark, the reassembled packet doesn't actually parse the UDP header, it lumps all of the IP packet payload into a single blob of "payload".

Anyway, I take it that you see how the reassembled packet only has 1472 Bytes of payload then, right?

That's exactly what would have fit in a 1500 byte IPv4 + UDP packet. Why was it fragmented?

**Comment by D33M0N** [comment] 2021-01-11 13:46
> That's exactly what would have fit in a 1500 byte IPv4 + UDP packet. Why was it fragmented?

Good question. Wild guess, but because the path to final destination (not my local MTU as you suggested) was not with MTU 1500 but 1492? But this information was not present in libtorrent (so it prepared MTU 1500 packet), but NIC/driver/kernel knew the MTU for this connection/path to be 1492 instead?

**Comment by arvidn** [comment] 2021-01-11 13:48
fragmentation is supposed to happen at network boundaries, when a packet is forwarded to a network with lower MTU. That's also where the MTU probes would be dropped.

**Comment by D33M0N** [comment] 2021-01-11 13:50
Well. Network boundaries are endpoints. Eg. my NIC. That's exactly where it's happening.

**Comment by arvidn** [comment] 2021-01-11 13:54
> (you did say it's not easy to get the ICMP reply on application level, but maybe it was sent by remote router and kernel got it and acted accordingly?)

Perhaps, although I would be surprised if it did. It would incur a cost on the large-MTU network with no apparent upside.

Still, whichever network has a lower MTU, it would also drop the MTU probe which would cause libtorrent to lower its ceiling. So fragmented packets would still be rare in that case.

> Well. Network boundaries are endpoints. Eg. my NIC. That's exactly where it's happening.

I'm not sure what your point is. Assuming your MTU is 1500, it's not a network boundary that would drop such packets. Your local stack supports 64 kiB packets, your ethernet NIC supports 1500 Byte packets (presumably).

**Comment by petacz** [comment] 2021-01-11 13:54
I have a similar issue.
Whatever MTU is set on my NIC the uTP traffic get fragmented.
The problem could be also caused by the fact that my router is using PPPoE.
Is is possible to solve it somehow?
![image](https://i.imgur.com/1WZ2rPk.png)

**Comment by arvidn** [comment] 2021-01-11 13:58
@petacz as I explained [here](https://github.com/arvidn/libtorrent/issues/5836#issuecomment-757005621) *some* fragmented packets are to be expected because of how uTP works. But they are expected to be rare. a few send window worth of packets per socket.

I take it you see a lot of fragmented packets, is that right?

Perhaps there is a problem with setting the DF flag on sockets. That's something that isn't standardised across platforms.

**Comment by petacz** [comment] 2021-01-11 14:01
@arvidn Hi, yes I see a lot of fragmented packets. Basically all large packets are fragmented.

**Comment by D33M0N** [comment] 2021-01-11 14:06
> @arvidn Hi, yes I see a lot of fragmented packets. Basically all large packets are fragmented.

if you use PPPoE primarly, you should set your MTU accordingly. What is it now? if it's 1500, then set it to 1492 if it changes anything. PPPoE v2 header is another 8 bytes. So lower whatever you have now by 8 bytes.

**Comment by arvidn** [comment] 2021-01-11 14:30
the Path MTU is supposed to be discovered automatically

**Comment by arvidn** [comment] 2021-01-11 17:54
excellent. @D33M0N does `ifconfig` give you the 1492 MTU? If so, I could probably pull it out of the network interfaces.
if you have a libtorrent repo checked out, you could even try running `enum_if`, which is a test program to test libtorrent's ability to list routes in network interfaces. I think it includes the MTUs.

**Comment by D33M0N** [comment] 2021-01-11 18:36
No? My MTU is fixed 1500 (also shown by ifconfig for ethernet NIC; (loopback has 65k)). Didn't we agree on that already? I have no clue, how to see per peer/connection/other_end/packets_destined_to_ip_address_XXX.XXX.XXX.XXX path MTUs sadly.

**Comment by D33M0N** [comment] 2021-01-11 19:53
@arvidn 
https://www.man7.org/linux/man-pages/man7/ip.7.html

quote:
When PMTU discovery is enabled, the kernel automatically 
              keeps track of the path MTU per destination host.  When it
              is connected to a specific peer with connect(2), the
              currently known path MTU can be retrieved conveniently
              using the IP_MTU socket option (e.g., after an EMSGSIZE
              error occurred).  The path MTU may change over time.

**Comment by arvidn** [comment] 2021-01-11 20:38
yes. that only works on connected sockets. libtorrent uses a single UDP socket for all uTP connections, all DHT interactions and all UDP trackers. It cannot be `connect()`ed to a specific host.

There may be some other ioctl to get this information as well. But, packets marked with the DF flag should also be dropped, so it should still be rare to fragment packets. If it isn't rare, I would expect there to be something wrong with the DF flag logic.

**Comment by arvidn** [comment] 2021-01-12 02:05
Is there some way the number of fragmented packet can be quantified?
For example, wireshark should be able to plot a histogram of packet sizes. That way I think it may be clear if the fragmented packets are happening because they are inherent to uTP or because there's a bug.

**Comment by D33M0N** [comment] 2021-01-12 14:10
> Is there some way the number of fragmented packet can be quantified?

Not that I am aware of.

> For example, wireshark should be able to plot a histogram of packet sizes. That way I think it may be clear if the fragmented packets are happening because they are inherent to uTP or because there's a bug.

As far as I have gathered, there is a "bug" on design level. You seem to use one MTU size for everything (yes, you try to do your best to figure out the "correct" one, but still, only 1 end result MTU, which is used for everything), whereas NIC MTU should be used only as ceiling value and there should be hundreds of different MTU's used, one per every peer/path.

**Comment by D33M0N** [comment] 2021-01-12 14:37
![pmtus](https://user-images.githubusercontent.com/15782020/104328341-677e0e80-54f4-11eb-9d30-5aeccc9d9583.png)

**Comment by D33M0N** [comment] 2021-01-12 14:47
Even if "THE ONE MTU" on the picture I drew you, would be 1111, although the packets would not get fragmented instantly, it would still not be optimal, because then the 1111 mtu size packets would be used for every outgoing traffic, rendering the overhead quite burden on the bandwidth. So only acceptable solution is to use per peer path mtu.

**Comment by arvidn** [comment] 2021-01-12 15:16
> You seem to use one MTU size for everything (yes, you try to do your best to figure out the "correct" one, but still, only 1 end result MTU, which is used for everything)

What gives you that impression?

**Comment by arvidn** [comment] 2021-01-12 15:25
> Kernel/NIC/driver seems to be aware of those per peer MTU's, but your libtorrent does not get/ask this information from them

It does. I think this is the third time I explain this: The DF flag is set and then a packet is sent. If the packet is dropped that means the MTU (is likely) smaller than that packet size. Do you disagree with this statement? Can you think of a case where this would over-estimate the path MTU? As far as I can tell, this is the *most* reliable way to ask for the path MTU (as long as you can set the DF flag).

> and therefore uses it's own "THE ONE MTU", which is quite often wrong sadly.

Please quantify "quite often". Is every UDP packet sent by libtorrent fragmented? presumably not the initial handshake packets nor DHT packets. But are all other packets fragmented?

This is important. I don't doubt that you and @petacz are experiencing problems, presumably that's why you looked at packet captures in the first place. But a single fragmented packet is just as reliable evidence of a bug as a single unfragmented packet is evidence of being bug-free.

**Comment by D33M0N** [comment] 2021-01-12 16:47
> What gives you that impression?

Your obfuscating talk about histograms and statistics instead of the problem at hand. Also you mentioned µTP using only one socket or something. Also as I see the same MTU size used for every outgoing packet from application layer to network layer (before the NIC fragments them).

> Please quantify "quite often". Is every UDP packet sent by libtorrent fragmented? presumably not the initial handshake packets nor DHT packets. But are all other packets fragmented?

Yes. To all the peers that have smaller MTU than µTP has set, almost every packet is fragmented.

> The DF flag is set and then a packet is sent.

TO WHOM?
You have still not answered, if this is done for every single peer and to every single peer.

> If the packet is dropped that means the MTU (is likely) smaller than that packet size.

Yes. How do you know it's dropped? Not all network devices even reply to that, they just silently drop them.

>Do you disagree with this statement? Can you think of a case where this would over-estimate the path MTU? As far as I can tell, this is the _most_ reliable way to ask for the path MTU (as long as you can set the DF flag).

No, generally I don't disagree with this, **as long as this is done for every single path used**. But is it?
And just "sending out DF flag set packet" doesn't tell you anything. The reply (or lack thereof) will tell you something. And what you do with that something is the question :-)

**Comment by D33M0N** [comment] 2021-01-12 16:50
[packets_to_216.154.38.116.zip](https://github.com/arvidn/libtorrent/files/5803545/packets_to_216.154.38.116.zip)

**Comment by arvidn** [comment] 2021-01-12 16:59
> Your obfuscating talk about histograms and statistics instead of the problem at hand.

The ratio of fragmented packets vs. large unfragmented packets is the next step in pin-pointing whether there's a problem or not. A histogram in wireshark would be a reasonable way of learning about this. If you'd post a larger pcap file I could take a look. This *is* the problem at hand.

> Also you mentioned µTP using only one socket or something.

That's correct. libtorrent and uTorrent does this. I was careful to say "UDP socket". There are multiple uTP sockets, but they all send and receive packets over the same kernel socket.

> Also as I see the same MTU size used for every outgoing packet from application layer to network layer (before the NIC fragments them).

That hardly seems like something that would indicate *my* understanding of networking.

> Yes. To all the peers that have smaller MTU than µTP has set, almost every packet is fragmented.

Ok, good. Do you see any DF flags set?

> TO WHOM?

The peer.

> You have still not answered, if this is done for every single peer and to every single peer.

I don't know what you mean by "for" and "to" there. Path MTU means the MTU for a path, which means from one endpoint to another. Each uTP socket performs path MTU discovery. I thought this was obvious. I mentioned it [here](https://github.com/arvidn/libtorrent/issues/5836#issuecomment-757005621)

> The effective MTU for a specific uTP connection starts off in the middle. Once each congestion window (i.e. once each RTT) one packet is sent as an MTU probe, with the do-not-fragment bit set. If the probe is lost, it's taken to mean the MTU is lower and the ceiling is lowered to just below the dropped probe.

> Yes. How do you know it's dropped? Not all network devices even reply to that, they just silently drop them.

It's not ACKed by the other end.

> No, generally I don't disagree with this, as long as this is done for every single path used. But is it?

Yes (otherwise it wouldn't be called *Path* MTU discovery).

> And just "sending out DF flag set packet" doesn't tell you anything. The reply (or lack thereof) will tell you something. And what you do with that something is the question :-)

How to do path MTU discovery is well documented in the RFCs describing it for TCP. It's a binary search.

> Every single outgoing packet bigger than mtu 1492 is fragmented.

Right, that's what you would expect if your MTU is 1492. I'm guessing that your local network has 1500 Bytes MTU, but your gateway is connected to a PPPoE network, and your kernel knows that.

**Comment by D33M0N** [comment] 2021-01-12 17:09
> Right, that's what you would expect if your MTU is 1492. I'm guessing that your local network has 1500 Bytes MTU, but your gateway is connected to a PPPoE network, and your kernel knows that.

🤦
NO! How many times have I already explained to you, that it is NOT "my computer" or "my router" or "my link to the interwebs via my ISP" BUT THE PEER ON THE OTHER END (OTHER PERSON ON THE OTHER END OF THE COMMUNICATION IN ANOTHER COUNTRY) that is connected over the PPPoE or whatever to their ISP.
**For which you have not discovered the right pmtu.**
[packets_to_188.27.146.7_a.zip](https://github.com/arvidn/libtorrent/files/5803661/packets_to_188.27.146.7_a.zip)

**Comment by D33M0N** [comment] 2021-01-12 17:09
[packets_to_212.102.39.184.zip](https://github.com/arvidn/libtorrent/files/5803662/packets_to_212.102.39.184.zip)
[packets_to_93.104.20.236.zip](https://github.com/arvidn/libtorrent/files/5803664/packets_to_93.104.20.236.zip)

**Comment by D33M0N** [comment] 2021-01-12 17:11
If you claim, that you do this path discovery per peer, and it obviously fails gived those per peer filtered packet captures. Is it safe to assume, your path discovery doesn't always work as intended?

**Comment by arvidn** [comment] 2021-01-12 17:24
> NO! How many times have I already explained to you, that it is NOT "my computer" or "my router" or "my link to the interwebs via my ISP" BUT THE PEER ON THE OTHER END (OTHER PERSON ON THE OTHER END OF THE COMMUNICATION IN ANOTHER COUNTRY) that is connected over the PPPoE or whatever to their ISP.

Dude, it's not relevant. It's not an insult to guess that your link is running over PPPoE, is it?

> If you claim, that you do this path discovery per peer, and it obviously fails given those per peer filtered packet captures I just uploaded. Is it safe to assume, your path discovery doesn't always work as intended?

It suggests that the logic that sets the DF flag is not working correctly, at least under certain circumstances (as I suggested [here](https://github.com/arvidn/libtorrent/issues/5836#issuecomment-757968485)). I don't see any DF flags by manual inspection in wireshark in those captures. So, let's move forward with this trouble shooting.

**Comment by D33M0N** [comment] 2021-01-12 22:35
so what now? :)

**Comment by arvidn** [comment] 2021-01-12 23:36
I've updated my analysis tool and I don't see a single DF flag in any of your pcap files

**Comment by D33M0N** [comment] 2021-01-13 03:39
Now when you mention it, I found two:
Within wireshark use filter: ip.flags.df == 1
in 212.102.39.184 file I see 1 packet. weirdly enough it's incoming, not outgoing.
in 188.x.x.x 0 packets.
in 93.104.20.236 file I see 1 packet. this time outgoing.

**Comment by arvidn** [comment] 2021-01-14 10:14
@D33M0N or @petacz would you be able to compile a custom version of libtorrent to test this patch?
https://github.com/arvidn/libtorrent/pull/5862

**Comment by D33M0N** [comment] 2021-01-14 12:50
Maaaaybe. I can try at least. But now when I started looking into it, qbittorrent uses as dependacy "libtorrent-rasterbar".
Is this even the same libtorrent? :blush:

**Comment by D33M0N** [comment] 2021-01-14 13:10
And/or there are a lot of AUR versions for libtorrent-rasterbar.
Can any of them be exactly what I would want? Or with as little modification as possible?
https://aur.archlinux.org/packages/?O=0&K=libtorrent-rasterbar

Like 1_2-git uses `source=('git+https://github.com/arvidn/libtorrent.git#branch=RC_1_2')` and then just swapping some numbers around. or 2.0.0.RC uses ```
source=('libtorrent-rasterbar'::'git+https://github.com/arvidn/libtorrent.git#branch=master'
        'git+https://github.com/arvidn/libsimulator.git'
        'git+https://github.com/arvidn/try_signal.git'
        'git+https://github.com/paullouisageneau/boost-asio-gnutls.git'
        'git+https://github.com/paullouisageneau/libdatachannel.git'
        'json-vinniefalco'::'git+https://github.com/vinniefalco/json.git')
```
as source... changing any of the links there and done? :)

**Comment by arvidn** [comment] 2021-01-14 20:37
I'm not very familiar with those packages or whether they can help to build a patched version. I would recommend you use the 1.2.x as base version, both because that's what you're currently using and that's what my patch is against. So it's the most likely to apply cleanly against.

you can apply the patch from my PR with `patch -p1`.

Alternatively, you can `git clone` the repo, go to the specific branch and either do:

```
b2
sudo b2 install
```
or 
```
cmake --build . --target install
```

I'm not sure those install rules get a lot of testing, so there's a risk something will go wrong.

**Comment by D33M0N** [comment] 2021-01-14 21:07
> you can apply the patch from my PR with `patch -p1`.

can you give like the full link please?
something that would look like this:
`source=('git+https://github.com/arvidn/libtorrent.git#branch=RC_1_2')`
or this:
`https://github.com/arvidn/libtorrent.git#branch=RC_1_2`

**Comment by userdocs** [comment] 2021-01-15 20:55
My build script can apply custom patches to libtorrent and or qbittorrent and provide a static build. In this case use the bootstrap option to create the required directories then place your patch in that location. It will be automatically applied. 

```
./qbittorrent-nox-static.sh -bs
```

An example output.

```
 Using the defaults, these directories have been created:

 ~/docker/qb-build/patches/libtorrent/1.2.12

 ~/docker/qb-build/patches/qbittorrent/4.3.2

 If a patch file, named patch is found in these directories it will be applied to the relevant module with a matching tag.
```

https://github.com/userdocs/qbittorrent-nox-static

**Comment by arvidn** [comment] 2021-01-17 00:43
> can you give like the full link please?

Sorry, I missed this comment.

At the bottom of https://github.com/arvidn/libtorrent/pull/5862 there are command line instructions that can be revealed. So, something like this:

```
git clone https://github.com/arvidn/libtorrent.git
cd libtorrent
git checkout -b utp-mtu origin/utp-mtu
```

Alternatively, if you already have 1.2.x. sources and want a patch to apply using `patch -p1 <file.diff` you can get the diff by appending ".diff" to the URL:

https://patch-diff.githubusercontent.com/raw/arvidn/libtorrent/pull/5862.diff

**Comment by D33M0N** [comment] 2021-01-17 08:28
> git clone https://github.com/arvidn/libtorrent.git
> cd libtorrent
> git checkout -b utp-mtu origin/utp-mtu

[deemon@Zen libtorrent-rasterbar-1_2-git]$ git checkout -b utp-mtu origin/utp-mtu
fatal: 'origin/utp-mtu' is not a commit and a branch 'utp-mtu' cannot be created from it
[deemon@Zen libtorrent-rasterbar-1_2-git]$ cd libtorrent/
[deemon@Zen libtorrent]$ git checkout -b utp-mtu origin/utp-mtu
fatal: this operation must be run in a work tree

**Comment by arvidn** [comment] 2021-01-17 11:02
> I need to get a git link with patches pre-applied already. Is there such a thing?

```
git clone https://github.com/arvidn/libtorrent.git --branch utp-mtu
```

That will clone the branch with the path applied to it

**Comment by D33M0N** [comment] 2021-01-17 11:29
Alright! Now we're in business. :-)
Managed to build it finally with correct (patched) files. hopefully qBittorrent uses it also now.
How or what can I test manually to see it in action? What should have been changed?

**Comment by D33M0N** [comment] 2021-01-17 11:50
Something radically changed. Now I see ICMP replies with requests to reduce the packet size, however it seems qBittorrent still ignores them ... or reverts back to previous rather fast.
[utp-mtp-patch_2021-01-17.zip](https://github.com/arvidn/libtorrent/files/5825982/utp-mtp-patch_2021-01-17.zip)

when you apply filter ip.flags.df == 1 you see quite nice picture now where you send UDP df packet out and instantly get ICMP reply from some router inbetween (with different IP than the peer) about recuding packetsize when destination is "peer":
![image](https://user-images.githubusercontent.com/15782020/104839568-af24e180-58ca-11eb-9c2e-eee9a1662798.png)

**Comment by D33M0N** [comment] 2021-01-17 11:52
without the filter you see that the fragmentation on kernel still happens and that UTP tries to send out 1514 size packets although it should know to use smaller now... ?

**Comment by arvidn** [comment] 2021-01-17 16:10
great! thanks for testing. I really need to improve the unit tests for the MTU discovery. I'm extending my analysis tool to easier understand what's going on in your packet capture. So far it definitely looks like the lost MTU probe is acknowledged as lost, but the MTU ceiling doesn't seem to be adjusted as the next packet that's sent is still too large.

I'll keep investigate this. I will probably add patches to the branch and ask you to test again later.

**Comment by arvidn** [comment] 2021-01-17 23:39
I have updated the branch with more fixes now. I've been testing this patch in the `RC_2_0` branch which has a more sophisticated simulator. I imagine I'll add the tests there and back-port the fixes here, in `RC_1_2`.

**Comment by D33M0N** [comment] 2021-01-18 17:10
Updated. However now the situation is rather bizarre. It almost feels like there is never a full sized packet anymore from uTP to anyone. I can see only packets with sizes 1345, 1344, 1343, 1342, 1341, 1340 and downwards. On the positive side, there is almost no fragmentation at all anymore.

**Comment by arvidn** [comment] 2021-01-18 17:47
do you have another capture?
one of the bugs I discovered that would suppress MTU-probes from being sent was that the payload would have to exceed the mtu floor. The problem was that once the mtu floor was high enough, that would never happen because the payload was just the uTP payload, not including the uTP header. The condition has to be `payload + header_size >= mtu_floor`.

**Comment by D33M0N** [comment] 2021-01-18 19:57
[2021-01-18_10k_1.zip](https://github.com/arvidn/libtorrent/files/5832156/2021-01-18_10k_1.zip)
[2021-01-18_10k_2.zip](https://github.com/arvidn/libtorrent/files/5832158/2021-01-18_10k_2.zip)

**Comment by arvidn** [comment] 2021-01-19 23:02
I've tweaked the patch a little bit, to be less aggressive when resetting the PMTUd search. While in steady-state, one MTU probe is still sent once every RTT. If that probe is lost (after previous probes going through at the same packet size), the floor is no longer reduced all the way to the minimum MTU, but only half-way there, so it should save one RTT of small packets when that happens by chance.

As for the largest packets; the connections I looked at (the ones with the most packets in them) did not have particularly small MTU ceilings. one was 1492 (which is the largest over PPPoE) and one had 1481.

Would you mind testing again? I feel pretty good about this change and I'm tempted to land it, merge it into `RC_2_0` so I can get started on the tests

**Comment by D33M0N** [comment] 2021-01-20 15:27
not sure it will help, but some new packets with the tweaked version. Hopefully :)
[2021-01-20_10k_18.zip](https://github.com/arvidn/libtorrent/files/5843463/2021-01-20_10k_18.zip)
[2021-01-20_10k_19.zip](https://github.com/arvidn/libtorrent/files/5843464/2021-01-20_10k_19.zip)

**Comment by D33M0N** [comment] 2021-01-20 17:38
I do know that the mtu size theoretically can change in time when the route changes, but practically this happens very rarely. And packets do get lost naturally also sometimes. So immediately after every single lost packet to reduce the mtu would be over-reacting a little IMHO. Just saying. I don't know your exact logic behind it, but ... when a packet gets lost (even when it previously worked at this exact MTU size) I propose at least second and maybe even third probe to be sent out with the same size before mtu reduction -- because sometimes the cause for packet loss is ... packet loss, not too big packet size.

Other scenario where you are just discovering the initial packet size for new peer, then more aggressive approach to reach/find the maximum working mtu would be preferred.

**Comment by arvidn** [comment] 2021-01-20 17:42
> So immediately after every single lost packet to reduce the mtu would be over-reacting a little IMHO. Just saying. I don't know your exact logic behind it,

There's only a single MTU probe per RTT, so the risk of the probe being the packet that's lost decreases as the congestion window increases (i.e. latency or throughput increases).

Yes, I think requiring two lost probes in a row would be better. It's also more complexity, which is less confidence in correct behavior.

**Comment by arvidn** [comment] 2021-01-21 11:54
I've landed this in RC_1_2 now

**Closed by arvidn** 2021-01-21 11:54 UTC
