### ISSUE TITLE
libtorrent prevents reannounce to a tracker if endpoints of a listen socket become empty or invalid at any point

### ISSUE THREAD

**Issue by summerqB** [arvidn/libtorrent#6603] opened 2021-12-21 15:20 UTC
**Please provide the following information**

libtorrent version (or branch):
RC1_2
platform/architecture:
debian 11
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Since libtorrent 1.2.4 a change was introduced to libtorrent which disables a listen socket from re-annoucing to the tracker if the listen socket has no valid endpoints or have endpoints which can't route to the internet.
This is very problematic as in certain cicumstances the endpoints become invalid and tracker announces are skipped from the particular listen socket even when the listen socket regains a new valid endpoint.
Here's one scenario:
libtorrent is set to listen on a VPN interface(by interface name or GUID).
When the VPN is stopped, the interface doesn't have a valid IP address which libtorrent can listen on. So libtorrent issues a host_unreachable error and disables that listen socket from future annouces.
Even when we re-enable the VPN, get a new valid IP and libtorrent listens on the new IP, it skips tracker announces because the listen socket got disabled from further announces.

Here's the relevant line of codes which gets triggered and causes this issue:

https://github.com/arvidn/libtorrent/blob/48ba329a403ee81965fc2231c080f60d7a493a39/src/http_tracker_connection.cpp#L304-L308

https://github.com/arvidn/libtorrent/blob/48ba329a403ee81965fc2231c080f60d7a493a39/src/torrent.cpp#L11816-L11821

Also if you ever have an empty or invalid list of endpoints, DHT stops working forever. No matter how many times you switch interfaces or add a valid IP it never starts working again.

**Comment by arvidn** [comment] 2021-12-28 10:24
Thank you for this report and especially details!

The original idea (and incorrect assumption) was that the reachability via an interface would only change when changing the `listen_interfaces` setting (which would trigger a call to `session_impl::reopen_listen_sockets()`), causing `enable_all_trackers()` being called on all torrents. This sets the `enabled` bits to true again.

If I recall correctly, the whole point of the `enabled` flag is to suppress consistent error alerts for interfaces that aren't really used anyway (e.g. loopback when talking to the internet). It clearly seems better to get periodic errors from such interfaces than to fail to detect a change in the actual listen interface.

Would it be reasonable to just remove the `enabled` flag?

**Comment by arvidn** [comment] 2021-12-28 10:32
@an0n666 do you think this would fix it? https://github.com/arvidn/libtorrent/pull/6615

**Comment by an0n666** [comment] 2021-12-28 15:12
Sorry but I'm unable to test at the moment unless someone provides me with builds.

BTW I think I got a clue about DHT.
After you disable and re-enable the VPN, DHT doesn't start populating, but when I make connection with any peer and libtorrent succeeds in getting my external IP, DHT starts populating immediately.
Basically when I get a external IP detected alert, DHT also starts working.
Another way to make DHT working again is to disable and re-enable DHT which also results in a external IP detected alert.

These are probably the related commits which caused this regression https://github.com/arvidn/libtorrent/commit/82d4d1927d7db22ea71f5b7e3f5396bcee3b5513

Sorry If I made any misinterpretations!

**Comment by xavier2k6** [comment] 2021-12-29 10:59
@an0n666 Can you try one of the qBittorrent builds from https://github.com/xavier2k6/qBittorrent/actions/runs/1633663321?

**Comment by an0n666** [comment] 2021-12-29 11:49
Not fixed yet. I guess this is still getting triggered.
`if (ec == boost::system::errc::address_family_not_supported)`
`aep->enabled = false;`

**Comment by an0n666** [comment] 2021-12-29 12:06
Trackers work when you pause and resume the torrent. Force re-announce doesn't work.

**Comment by an0n666** [comment] 2021-12-29 17:47
@arvidn I even tried with commenting out this condition `if (ec == boost::system::errc::address_family_not_supported)`
But it looks like that doesn't fix it either.
So maybe we're looking at the wrong place.
Here's some more findings:
When the trackers stop working, the next announce time shows some abnormally high value like 68 years in qbittorrent and 21 hours in deluge. Force re-announce doesn't work. However if you change the tier of any of the trackers, then all the trackers start updating again and works fine. Also if you pause the torrent and resume it, it also starts working.

**Comment by arvidn** [comment] 2021-12-30 12:00
How do you get into this state?
* enable a VPN
* `listen_interfaces` to the VPN interface name 
* and disconnect the underlying network connection

does that do it?

**Comment by arvidn** [comment] 2021-12-30 12:43
the very long announce intervals could be a result of exponential back-off of retrying trackers.
Although, it looks like the max retry interval is 60 minutes.

Is the next announce timestamp you see the next announce for the whole torrent, or per tracker? (i.e. does it come from `torrent_status` or `announce_endpoint`)

**Comment by an0n666** [comment] 2021-12-30 13:59
> How do you get into this state?
> 
> * enable a VPN
> * `listen_interfaces` to the VPN interface name
> * and disconnect the underlying network connection
> 
> does that do it?

Yes. Enable VPN, qBt listening on VPN interface by name or GUID(windows).
Then disconnect VPN and force announce to tracker while VPN is disconnected.(this step is important) and see the very high reannounce time.
After that reconnect VPN and force reannounce. See force announce not taking any effect probably due to some very high minimum re-announce time or some other bug.

**Comment by an0n666** [comment] 2021-12-30 16:39
> the very long announce intervals could be a result of exponential back-off of retrying trackers. Although, it looks like the max retry interval is 60 minutes.
> 
I do not think so because when VPN is disconnected and you do a force re-announce, the first retry happens after like 10 seconds and then the next announce time shows very long intervals.
>
> Is the next announce timestamp you see the next announce for the whole torrent, or per tracker? (i.e. does it come from `torrent_status` or `announce_endpoint`)
>
I do not know since both qBt and Deluge shows this per torrent and not per tracker. But regardless, none of the trackers work even if torrent has multiple trackers.

**Comment by an0n666** [comment] 2021-12-31 03:08
BTW this does not require a VPN. You can listen on a specific IP address to reproduce it.

**Comment by arvidn** [comment] 2021-12-31 03:34
I haven't had time to test this yet, but this is what I'm exploring: https://github.com/arvidn/libtorrent/pull/6626

**Comment by an0n666** [comment] 2021-12-31 04:10
@arvidn 
Now the behaviour is much better.
It's showing reannounce in 5 minutes. And I waited 5 minutes then tracker announced fine.
So this fixes the long re-announce time.
However this doesn't fix the issue with force-reannounce not working.
Maybe the minimum re-announce time is also affected by this and has some very long re-announce time.
Because when it shows reannounce in 5 minutes, force announce doesn't take any effect.

**Comment by an0n666** [comment] 2021-12-31 16:48
Some more findings:
If I pass ignore_minimum_interval flag I can bypass the re-announce not taking any effect issue. However it just resets the next announce timer to 5 mins with no actual effect on the announce itself, i.e - no actual announce takes place.
If I do not pass any flags, force reannounce doesn't work at all.
Regardless of passing the flag, tracker works after the next announce time passes.
Seems like there's some underlying bigger issue in the announce logic which is causing all these undefined behaviours.

**Comment by an0n666** [comment] 2022-01-02 14:44
@arvidn 
When I force reannounce after disabling the network interface or VPN, there’s no tracker error alert. Is that expected behaviour?

**Comment by arvidn** [comment] 2022-01-02 20:23
yeah, the issue with `tracker_error_alerts` is that they include URL and local endpoints, and when the problem is that no eligible tracker or endpoints were found, there isn't any information identifying the tracker that failed.

**Comment by arvidn** [comment] 2022-01-02 20:25
`force_reannounce()` is supposed to reset the announce-timer, and supposed to work within the 5 minutes. Maybe the `min_reannounce` somehow gets set too high as well.

**Comment by an0n666** [comment] 2022-01-05 13:03
@arvidn can the patch be merged with whatever improvements that were made?

**Comment by arvidn** [comment] 2022-01-05 19:27
Yes, so the PR I made is a step in the right direction, right?

I updated it as well, did you check out the most recent version?

I can land it and keep looking into a more complete fix.

I'm travelling right now, so I'm a bit slow to respond.

**Comment by an0n666** [comment] 2022-01-06 15:13
Yes I've tested the most recent version and it mitigates the issue by re-annoucing in 1 min.
However the issue that force-reannounce doesn't work still remains.
Also another issue is lack of tracker_error_alerts. Without alerts the client doesn't update the tracker status properly.

The things you should look into is how the next announce time gets set so high and why nothing works before the tracker announces itself after the countdown is over. Also why DHT fails to work after network is back online till external IP is found. Maybe keep trying to get our external IP when there's no other help around(i.e - other peers or trackers that supply ext IP).

**Comment by summerqB** [comment] 2022-06-29 13:10
@arvidn 
I was looking into the issue of DHT nodes staying at zero after a disconnect/reconnect.
I found that when it stays at zero, if I attempt to download metadata from a magnet link, DHT starts populating again.
So my question is, Is this a bug in session status not updating the dht_nodes count because it's counting those nodes as inactive or something? Do you plan to explore this issue further?
There are multiple other ways that DHT node count starts to increase such as when you have a active torrent with transfers happening.

**Closed** 2022-07-03 12:04 UTC
