### ISSUE TITLE
Broken pkgconfig file

### ISSUE THREAD

**Issue by lgbaldoni** [arvidn/libtorrent#6830] opened 2022-04-21 09:13 UTC
**Please provide the following information**

libtorrent version (or branch): 2.0.6

platform/architecture: openSUSE Leap 15.4

compiler and compiler version: gcc 7.5.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

This is what comes out:
```
prefix=/usr
libdir=${prefix}/lib64

Name: libtorrent
Description: Bittorrent library
Version: 2.0.6
Libs: -L${libdir} -ltorrent-rasterbar -l-pthread -lssl -lcrypto -lboost_system
Cflags: -fexceptions  -pthread -I/usr/include -DTORRENT_LINKING_SHARED -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_NO_DEPRECATED -DTORRENT_USE_OPENSSL -DTORRENT_USE_LIBCRYPTO -DTORRENT_SSL_PEERS -DOPENSSL_NO_SSL2
```
Perhaps the parser is confused by `-pthread` coming from `libcrypto.pc` ? (`Libs.private: -lz -ldl -pthread`)

**Comment by zywo** [comment] 2022-04-21 14:16
Caused by this change: https://github.com/arvidn/libtorrent/pull/6722
Problem reported here:  https://github.com/arvidn/libtorrent/pull/6722#issuecomment-1039117140 but not solved since then.

**Comment by xavier2k6** [comment] 2022-04-21 14:28
may be fixed by PR https://github.com/arvidn/libtorrent/pull/6828 ?!

**Comment by arvidn** [comment] 2022-05-07 11:10
the fix has landed

**Closed by arvidn** 2022-05-07 11:10 UTC
