### ISSUE TITLE
FTBFS

### ISSUE THREAD

**Issue by d33tah** [arvidn/libtorrent#1665] opened 2017-02-05 17:17 UTC
libtorrent version (or branch):

master branch

platform/architecture:

ubuntu:16.04, x86_64

compiler and compiler version:

TBH I don't know. Latest currently available there.

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

```
  CXX      performance_counters.lo
In file included from ../include/libtorrent/performance_counters.hpp:37:0,
                 from performance_counters.cpp:33:
../include/libtorrent/aux_/array.hpp: In instantiation of 'constexpr IndexType libtorrent::aux::array<T, Size, IndexType>::end_index() const [with T = std::atomic<long int>; long unsigned int Size = 292ul; IndexType = int]':
performance_counters.cpp:53:49:   required from here
../include/libtorrent/aux_/array.hpp:73:3: error: body of constexpr function 'constexpr IndexType libtorrent::aux::array<T, Size, IndexType>::end_index() const [with T = std::atomic<long int>; long unsigned int Size = 292ul; IndexType = int]' not a return-statement
   }
   ^
Makefile:952: recipe for target 'performance_counters.lo' failed
make[1]: *** [performance_counters.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/libtorrent/src'
Makefile:622: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
The command '/bin/sh -c cd libtorrent && ./autotool.sh && ./configure --prefix=/usr && make -j`nproc` && make install' returned a non-zero code: 2
```

Here's a Dockerfile that lets you reproduce it:

```
FROM ubuntu:16.04
RUN cp /etc/apt/sources.list /etc/apt/sources.list_ && sed -i 's/deb /deb-src /' /etc/apt/sources.list_ && cat /etc/apt/sources.list_ >> /etc/apt/sources.list && rm /etc/apt/sources.list_
RUN apt-get update && apt-get build-dep libtorrent -y && apt-get install -y git libboost-system-dev
RUN git clone https://github.com/arvidn/libtorrent.git
RUN cd libtorrent && ./autotool.sh && ./configure --prefix=/usr && make -j`nproc` && make install
```

**Comment by arvidn** [comment] 2017-02-05 17:34
@aldenml could this perhaps be caused by ``std::array<>::size()`` not being ``const`` in C++11? (according to cppreference it was fixed in C++14).

@d33tah please find out which compiler version you're using. Presumably it's gcc, so type: ``g++ --version``

**Comment by d33tah** [comment] 2017-02-05 17:38
```
root@ab186b32cb29:/# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

@arvidn 

Sorry for being too lazy to do in the first place, had no terminal on that box at that moment :p

**Comment by arvidn** [comment] 2017-02-05 17:41
@aldenml in fact, I'm seeing this on clang/OSX right now:

```
include/libtorrent/aux_/array.hpp:71:4: error: statement not allowed in constexpr function
   do {} while (0);
```

That statement is what asserts are replaced with in release builds. Perhaps that particular assert need to be more conservatively enabled.

**Comment by arvidn** [comment] 2017-02-05 17:49
I'm merging RC_1_1 into master right now, I will remove the ``constexpr`` qualifier from that function for now

**Comment by aldenml** [comment] 2017-02-05 22:28
Well, I see you already took action :)

In fact, it's not `const` in c++11, but it's `constexpr`. In any case, I will try to make this with `static_assert` and avoid any call inside `end_index`

**Comment by aldenml** [comment] 2017-02-05 22:44
For reference: https://github.com/arvidn/libtorrent/pull/1666

**Closed** 2017-02-16 21:37 UTC
