### ISSUE TITLE
Disabling ssl port impossible when using interface on session constructor

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#248] opened 2015-11-07 02:14 UTC
Until a few hours ago, qbt constructed the session using `session(fingerprint, 0)` and then later on, while configuring the session, it called `listen_on()` with the appropriate interface and port.
I changed the session construction to use the configured interface+port at construction. (security measure: If the configured interface didn't exist anymore, listen_on() was too late. The session had already connected for a few moments to 0.0.0.0).

Also during session configuration I disable the ssl port by setting `ssl_listen` to `0`. Up until now, it worked. Now that I changed to using the session constructor like `session(fingerprint, ports, ip, 0);` setting `ssl_listen` to `0` doesn't have any effect.

I get a `portmap_alert` for port 4433. And netstat confirms that qbt is still listening on that port, even after I set ssl_listen to zero.

Latest RC_1_0 on Windows 7.

**Comment by arvidn** [comment] 2015-11-07 03:36
the race condition should have been fixed in master (where you can set any setting on construction). fixing that would be difficult RC_1_0 since it most likely would require API changes to the constructor.

However, the fact that it doesn't close the listen socket should definitely be fixed

**Comment by arvidn** [comment] 2015-11-08 07:49
did setting ssl_listen to 0 close the ssl port before transitioning away from listen_on()?

**Comment by sledgehammer999** [comment] 2015-11-08 10:24
>did setting ssl_listen to 0 close the ssl port before transitioning away from listen_on()?

Yes.

**Comment by arvidn** [comment] 2015-11-08 17:39
I can't reproduce this either. could you double check that session_impl::open_listen_port() is called when you call set_settings() with ssl_listen=0? I tested this in client_test and it is called and it closes all listen ports and re-opens the ones it's supposed to, and none of the ssl ports.

as for the portmap alert, are you sure that's not the alert for first opening of ports? I wouldn't expect you to get another one to indicate the port was closed.

also, netstat may indicate the socket being in CLOSE_WAIT, or some other closed state.

**Comment by sledgehammer999** [comment] 2015-11-08 17:56
Just checked it is in LISTENING state. However, I noticed something else weird. Initial setting of session_settings has the above result.
If I reapply them by eg changing port the ssl_listen port indeed closes. I need to more closely inspect the code logic of qbt. It might be wrong in our side.
PS: Each time I reapply the session_settings, qbt always sets ssl_listen to 0.

**Comment by sledgehammer999** [comment] 2015-11-09 22:46
@glassez can you take a look at this as a second pair of eyes? Our code flow is straight-forward on how we set ssl_listen port during launch. Do you see anything wrong? Or do you also conclude that this comes from libtorrent?

**Comment by sledgehammer999** [comment] 2015-11-09 22:59
@arvidn I put these breaks in gdb:
1. `break libtorrent::aux::session_impl::open_listen_port` 
2. `break libtorrent::session::set_settings`.

open_listen_port fires once during start and BEFORE set_settings. After set_settings open_listen_post doesn't break.

**Comment by arvidn** [comment] 2015-11-11 02:11
the second time it fires, could you check if ssl_listen is 0 in the settings at that point? Is there any chance you may call set_settings() from some other place, causing the second hit?

When settings settings, if no setting affecting the listen port changed, open_listen_port() will not be called.

**Comment by sledgehammer999** [comment] 2015-11-11 15:28
Finally, I found out why it is happening. I hope you'll be able to fix it now.
We load the previous session state (session::load_state()) and **afterwards** call set_settings(). If the `ssl_listen` contained in the state is the same as the one you pass via set_settings() nothing happens. If I change one of those the port changes(or closes) correctly upon first call.

**Comment by arvidn** [comment] 2015-11-12 01:49
you mean, if you load a session state file from disk where ssl_listen is 0, the socket is not closed?

**Comment by arvidn** [comment] 2015-11-12 06:38
could you please give this patch a try? https://github.com/arvidn/libtorrent/pull/261

**Comment by sledgehammer999** [comment] 2015-11-12 18:15
It works! Thank you.
PS: If there aren't any pending bugs I think it is time to release 1.0.7

**Comment by arvidn** [comment] 2015-11-13 01:31
good. yeah, I will update the version() string and then cut 1.0.7

**Closed by arvidn** 2015-11-13 01:31 UTC
