### ISSUE TITLE
Torrent still keep in valid after removed

### ISSUE THREAD

**Issue by lihehub** [arvidn/libtorrent#1913] opened 2017-04-13 03:57 UTC
Torrent still keep in valid when I called remove_torrent()

**Comment by lihehub** [comment] 2017-04-13 07:49
This is my demo program. 

int main(int argc, char const* argv[])
{

    if (argc != 2) {
        std::cerr << "usage: " << argv[0] << " <magnet-url>" << std::endl;
        return 1;
    }

    lt::settings_pack pack;
    pack.set_int(lt::settings_pack::alert_mask
                 , lt::alert::error_notification
                 | lt::alert::storage_notification
                 | lt::alert::status_notification
				 | lt::alert::session_log_notification
				 | lt::alert::all_categories);
    pack.set_bool(lt::settings_pack::enable_dht, false);
    
    lt::session ses(pack);
    lt::add_torrent_params atp;
    clk::time_point last_save_resume = clk::now();
    
    // load resume data from disk and pass it in as we add the magnet link
    std::ifstream ifs(".resume_file", std::ios_base::binary);
    ifs.unsetf(std::ios_base::skipws);
    atp.resume_data.assign(std::istream_iterator<char>(ifs)
                           , std::istream_iterator<char>());
    atp.url = argv[1];
    atp.save_path = "."; // save in current dir
    atp.flags |= lt::add_torrent_params::flag_sequential_download;
    ses.async_add_torrent(atp);
    
    // this is the handle we'll set once we get the notification of it being
    // added
    lt::torrent_handle h;
    for (;;) {
        std::vector<lt::alert*> alerts;
        ses.pop_alerts(&alerts);
        
        for (lt::alert const* a : alerts) {
            std::cout << a->message() << std::endl;
            
            if (auto at = lt::alert_cast<lt::add_torrent_alert>(a)) {
                h = at->handle;
            }
            // if we receive the finished alert or an error, we're done
            if (lt::alert_cast<lt::torrent_finished_alert>(a)) {
                h.save_resume_data();
                goto done;
            }
            if (lt::alert_cast<lt::torrent_error_alert>(a)) {
                std::cout << a->message() << std::endl;
                goto done;
            }
            
            // when resume data is ready, save it
            if (auto rd = lt::alert_cast<lt::save_resume_data_alert>(a)) {
                std::ofstream of(".resume_file", std::ios_base::binary);
                of.unsetf(std::ios_base::skipws);
                lt::bencode(std::ostream_iterator<char>(of)
                            , *rd->resume_data);
            }
        }
        std::this_thread::sleep_for(std::chrono::milliseconds(200));
        
        // ask the session to post a state_update_alert, to update our
        // state output for the torrent
        ses.post_torrent_updates();
        
        // save resume data once every 30 seconds
        if (clk::now() - last_save_resume > std::chrono::seconds(30)) {
            h.save_resume_data();
            last_save_resume = clk::now();

            std::cout << "torrent_handle remove_torrent" << std::endl;
            ses.remove_torrent(h, lt::session::delete_files);`
        }

        if (h.is_valid()) {
            std::cout << "torrent_handle is valid, use_count: " << h.native_handle().use_count() << std::endl;
        } else {
            std::cout << "torrent_handle is invalid" << std::endl;
        }
    }

done:
    std::cout << "\ndone, shutting down" << std::endl;

}

**Comment by arvidn** [comment] 2017-04-13 22:12
what do you mean by "keep in valid"?
do you mean that ``h.is_valid()`` does not return ``false`` ever?

**Comment by lihehub** [comment] 2017-04-14 03:01
@arvidn Yes, `h.is_valid()` always return `true` and `use_count == 2`

**Comment by arvidn** [comment] 2017-04-14 15:50
which version of libtorrent are you using?

**Comment by arvidn** [comment] 2017-04-14 19:37
it appears to be a problem in RC_1_1 at least. Thanks for this report, I'm hoping to have a fix + test shortly.

**Comment by arvidn** [comment] 2017-04-15 03:52
if you have a chance, please try this patch: https://github.com/arvidn/libtorrent/pull/1915

**Comment by lihehub** [comment] 2017-04-15 09:58
I'm using release version 1.1.1 (i.e. tag libtorrent-1_1_1).
I have tryed the patch. It seems to be passing the test case. but it **FAILED** when I changed the piece number to `10240`. So I realize that if you remove a torrent when the torrent `is downloading` or the status of the torrent `is not finish`, the test case will go to fail.

test_remove_torrent.cpp:
`boost::shared_ptr<torrent_info> t = ::create_torrent(&file, "temporary", 16 * 1024, 10240, false);`

**Comment by arvidn** [comment] 2017-04-15 15:01
ok, I'll extend the test. thanks!

**Comment by arvidn** [comment] 2017-04-15 22:04
I extended the test to cover what you suggested, but I still can't get it to fail locally. I'll see if it fails on travis or appveyor.

**Comment by arvidn** [comment] 2017-04-16 03:09
It's passing on travis and appveyor too. Do you have any suggestions of how to reproduce the problem with this patch?

**Comment by arvidn** [comment] 2017-04-16 03:14
I just realized you increase the number of pieces by an order of magnitude more. Trying that doesn't make a difference for me though

**Comment by lihehub** [comment] 2017-04-16 03:36
I tryed your new patch and I got passed too. I found that the test break out from loop when reached the following line 
`if (st1.upload_payload_rate == 0 && i > 20) break;`
You should ensure that there is data transmission 
你应该确保z

**Comment by lihehub** [comment] 2017-04-16 04:01
I tryed your new patch and I got passed too. 
I found the test program break out the loop at the beginning  when the following line was executed
`if (st1.upload_payload_rate == 0 && i > 20) break;`

You should make sure that the data is being transmitted when you remove the torrent.
You can modify the piece number to 10240 based on the original commit (commit : 45118561a1390cad87999880f5a7416919526e20), not based on the current commit 

I will keep testing

**Comment by lihehub** [comment] 2017-04-16 05:11
I don't know why you make the rate limit. The test case is failed when I disable the rate limit.
Like this:

![Uploading 20170416-1.png…]()

**Comment by lihehub** [comment] 2017-04-16 05:15
I don't know why you make the rate limit. The test case is failed when I disable the rate limit.
Like this:

    void test_remove_torrent(int const remove_options
    	, test_case const test = complete_download)
    {
	// this allows shutting down the sessions in parallel
	std::vector<session_proxy> sp;
	settings_pack pack = settings();

	//pack.set_int(settings_pack::upload_rate_limit, 10000);
	//pack.set_int(settings_pack::download_rate_limit, 10000);

	pack.set_str(settings_pack::listen_interfaces, "0.0.0.0:48075");
	lt::session ses1(pack);

	pack.set_str(settings_pack::listen_interfaces, "0.0.0.0:49075");
	lt::session ses2(pack);

	//boost::uint32_t const mask = 1 << lt::session::global_peer_class_id;
	//ip_filter f;

	//// make the global rate limit apply to all peers, regardless of IP
	//f.add_rule(address_v4::from_string("0.0.0.0")
		//, address_v4::from_string("255.255.255.255")
		//, mask);
    //#if TORRENT_USE_IPV6
    	//f.add_rule(address_v6::from_string("::")
    		//, address_v6::from_string("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff")
    		//, mask);
    //#endif
	//ses1.set_peer_class_filter(f);

	torrent_handle tor1;
	torrent_handle tor2;

**Comment by lihehub** [comment] 2017-04-16 05:52
This is the log of the above program execution:

[test_remove_torrent.log.txt](https://github.com/arvidn/libtorrent/files/924110/test_remove_torrent.log.txt)

**Comment by arvidn** [comment] 2017-04-16 05:55
I see. I was worried that the transfer would complete too quickly to be able to stop it mid-way through

**Comment by lihehub** [comment] 2017-04-16 06:03
I think you should make sure that the data is being fully transmitted.
I also found that the `use_count` of torrent are usually large when the problem occurs

**Comment by arvidn** [comment] 2017-04-16 12:10
thanks for helping with this. I believe my latest update fixes this issue as well. The problem was that ghost entries in the cache would not be evicted when stopping the torrent. The first patch fix evicting regular cache entries (which previously would just be demoted to ghost entries).

**Comment by arvidn** [comment] 2017-04-16 14:34
there's still one more failure

**Comment by lihehub** [comment] 2017-04-16 15:17
I run the test program. `remove_torrent_mid_download` and `remove_torrent_and_files_mid_download`  failed. This is the output :
`***** test_remove_torrent.cpp:114 "TEST_CHECK failed: "st2.is_finished == false"" *****`

**Comment by arvidn** [comment] 2017-04-16 20:38
updated again

**Comment by lihehub** [comment] 2017-04-18 02:45
I run the test program and I get a assertion failure:

removed
piece: 182
refcount: 0
piece_refcount: 0
num_blocks: 1
hashing: 0

hash: 0x0
hash_offset: -1
cache_state: (2) read-lru
outstanding_flush: 0
piece: 182
num_dirty: 0
num_blocks: 1
blocks_in_piece: 1
hashing_done: 1
marked_for_deletion: 1
need_readback: 0
hash_passed: 1
read_jobs: 0
jobs: 0
piece_log:
 read (0), set_outstanding_jobs (-1), read (0), read (0), clear_outstanding_jobs (-1)
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.1.1.0-1229491

file: 'block_cache.cpp'
line: 1645
function: void libtorrent::block_cache::check_invariant() const
expression: pe->storage->has_piece(pe)

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2: libtorrent::block_cache::check_invariant() const
3: libtorrent::invariant_checker_impl<libtorrent::block_cache>::invariant_checker_impl(libtorrent::block_cache const&)
4: libtorrent::block_cache::clear(libtorrent::tailqueue<libtorrent::disk_io_job>&)
5: libtorrent::disk_io_thread::abort_jobs()
6: libtorrent::disk_io_thread::thread_fun(int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work>)
7: boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work> >::operator()(libtorrent::disk_io_thread*, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work>) const
8: void boost::_bi::list4<boost::_bi::value<libtorrent::disk_io_thread*>, boost::_bi::value<int>, boost::_bi::value<libtorrent::disk_io_thread::thread_type_t>, boost::_bi::value<boost::shared_ptr<boost::asio::io_service::work> > >::operator()<boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work> >, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work> >&, boost::_bi::list0&, int)
9: boost::asio::detail::posix_thread::func<boost::_bi::bind_t<void, boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work> >, boost::_bi::list4<boost::_bi::value<libtorrent::disk_io_thread*>, boost::_bi::value<int>, boost::_bi::value<libtorrent::disk_io_thread::thread_type_t>, boost::_bi::value<boost::shared_ptr<boost::asio::io_service::work> > > > >::run()
10: boost_asio_detail_posix_thread_function
11: _pthread_body
12: _pthread_body
13: thread_start

signal: SIGINT caught:
1: sig_handler(int)
2: _sigtramp
3: 0x0
4: raise
5: assert_fail(char const*, int, char const*, char const*, char const*, int)
6: libtorrent::block_cache::check_invariant() const
7: libtorrent::invariant_checker_impl<libtorrent::block_cache>::invariant_checker_impl(libtorrent::block_cache const&)
8: libtorrent::block_cache::clear(libtorrent::tailqueue<libtorrent::disk_io_job>&)
9: libtorrent::disk_io_thread::abort_jobs()
10: libtorrent::disk_io_thread::thread_fun(int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work>)
11: boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work> >::operator()(libtorrent::disk_io_thread*, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work>) const
12: void boost::_bi::list4<boost::_bi::value<libtorrent::disk_io_thread*>, boost::_bi::value<int>, boost::_bi::value<libtorrent::disk_io_thread::thread_type_t>, boost::_bi::value<boost::shared_ptr<boost::asio::io_service::work> > >::operator()<boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work> >, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work> >&, boost::_bi::list0&, int)
13: boost::asio::detail::posix_thread::func<boost::_bi::bind_t<void, boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_service::work> >, boost::_bi::list4<boost::_bi::value<libtorrent::disk_io_thread*>, boost::_bi::value<int>, boost::_bi::value<libtorrent::disk_io_thread::thread_type_t>, boost::_bi::value<boost::shared_ptr<boost::asio::io_service::work> > > > >::run()
14: boost_asio_detail_posix_thread_function
15: _pthread_body
16: _pthread_body
17: thread_start

**Comment by arvidn** [comment] 2017-04-18 04:38
yeah. I've found one more issue. I'm working on another patch.

**Comment by arvidn** [comment] 2017-04-18 21:50
I discovered 2 more separate issues. I feel fairly confident I got them all now. I just updated the PR

**Comment by arvidn** [comment] 2017-04-19 04:50
appveyor and travis are happy now too. please give it another try!

**Comment by lihehub** [comment] 2017-04-19 05:10
I tryed again. I have not found any problems at the moment. My original demo program is running normally

**Comment by arvidn** [comment] 2017-04-22 23:01
as far as I can tell, this is fixed now (and covered by a test)

**Closed by arvidn** 2017-04-22 23:01 UTC
Labels: bug
