### ISSUE TITLE
msvc 14 ambiguous call to snprintf (64bit)

### ISSUE THREAD

**Issue by CriseX** [arvidn/libtorrent#98] opened 2015-08-19 13:32 UTC
This happens because stdio.h that ships with it defines snprintf and you have an inline function for it in config.hpp

Interestingly enough, the else branch of that preprocessor block seems to be obsolete as well, because you include limits.h at the top of config.hpp anyways. Of course previous versions of msvc still need that inline declaration though.

**Comment by arvidn** [comment] 2015-08-19 17:31
Do you know which version of msvc started shipping with this function? is it associated with c++11 support? (I don't think msvc10 had it though)

**Comment by CriseX** [comment] 2015-08-19 18:39
14 has it 12 doesn't so basically only the latest version has it at the time of writing this.

**Comment by ssiloti** [comment] 2015-08-20 02:04
I'm able to reproduce this. It only happens when building 64-bit and not 32-bit which is a little odd. Arvid, you want me to take over this one since I know you don't have a windows machine on-hand?

**Comment by arvidn** [comment] 2015-08-23 22:33
I'm still seeing this: https://ci.appveyor.com/project/arvidn/libtorrent/build/1.0.435/job/hc49j6ewxs3u91vl

**Comment by ssiloti** [comment] 2015-08-23 22:41
That's because PR 106 is missing 36c1a2f6 which hasn't been merged from the fix-msvc-build branch.

**Comment by arvidn** [comment] 2015-08-24 05:25
oh, I was convinced I had rebased on top of master..

**Comment by arvidn** [comment] 2015-08-27 10:34
I've been trying to get appveyor to cover 64 bit builds on msvc-14 (and have encountered a few issues trying to get there). Now I'm at a point where it says:

"LINK : fatal error LNK1101: incorrect MSPDB140.DLL version; recheck installation of this product"

does anyone have any ideas of what might be going on? (it only affects the 64 bit build):

https://ci.appveyor.com/project/arvidn/libtorrent/build/1.0.463/job/193pq226v78ei4np

**Comment by CriseX** [comment] 2015-08-27 16:28
I've heard of that error in cases where the 32bit cross-compiler is being used to make 64bit binaries, however, I don't really have a fix to offer (other than using a native 64bit compiler if that is not the case already).

Little research shows that if a machine has ever had a CTP of msvc installed this error is more likely for some reason (presumably the upgrade messes something up).

**Comment by ssiloti** [comment] 2015-08-28 03:21
Ok, with a little fiddling I was able to get my system into a state where the LNK1101 error reproduces consistently. I believe this thread describes the same issue that I'm seeing:

http://lists.boost.org/Archives/boost/2015/07/224365.php

For me the problem goes away if I switch from Boost 1.58 to 1.59 so it seems the problem was fixed in the version of Boost.Build shipped with 1.59.

**Comment by arvidn** [comment] 2015-08-30 18:15
ok. appveyor doesn't have a 64 bit build of bjam nor boost 1.59 yet. So I'm just building 64 bit with msvc-12 for now.

**Closed by arvidn** 2015-08-30 18:15 UTC
