### ISSUE TITLE
Upload slots aren't respected

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2586] opened 2017-12-03 19:00 UTC
**libtorrent version (or branch):**
1.1.5+gitf42b63c7ea

**platform/architecture:**
Windows 10 64bit

**compiler and compiler version:**
msvc2017 64bit

**please describe what symptom you see, what you would expect to see instead and
how to reproduce it.**

User reports that with:
1. global upload slots = 8
2. max per torrent upload slots = 4
3. choking algo = fixed slots
4. seeding choking algo = fastest upload

he observes that he uploads to more than 4 peers for one torrent.
He also provides screenshots.
Relevant issue in our bug tracker: https://github.com/qbittorrent/qBittorrent/issues/7842#issuecomment-348543748

**Comment by ssiloti** [comment] 2017-12-03 19:48
IME a peer reporting non-zero upload speed is not an accurate indication of its choke state. The reported speed is an average over a sliding window so it can be non-zero if the peer was recently choked. To get an accurate count of unchoked peers you need to check the `choked` peer flag.

**Comment by sledgehammer999** [comment] 2017-12-03 21:04
>IME a peer reporting non-zero upload speed is not an accurate indication of its choke state. The reported speed is an average over a sliding window so it can be non-zero if the peer was recently choked. To get an accurate count of unchoked peers you need to check the choked peer flag.

@Nemo-qB check the "Flags" column. See https://github.com/qbittorrent/qBittorrent/wiki/Frequently-Asked-Questions#What_do_all_those_flags_in_the_Flags_column_mean
Do you have only 4 peers with `U` flag, and the rest are with the `u` flag?

**Comment by ahmedtds** [comment] 2017-12-03 21:55
My upload slot per torrent is set to 1 and I can confirm that qbittorrent v4 sends to more than 1 peers at a time. Yes I check flags and there are more than one peer (around 4-5) that is not choked and actively sending data. New version definitely doesn't respect slot limits.

**Comment by ssiloti** [comment] 2017-12-04 00:55
I'm able to reproduce this in qBittorrent but not with libtorrent's test client. I've found that the problem goes away if I disable `Apply rate limit to uTP protocol` or if I disable uTP entirely. It looks like the problem is that if rate limiting of uTP is enabled, both libtorrent and qBittorrent have code which adds uTP connections to the local peer class. Any connection with the local class will ignore the upload slot limit. It seems wrong to add all uTP connections to the local peer class, we don't do that with TCP connections at least.

@arvidn does that sound right?

**Comment by sledgehammer999** [comment] 2017-12-04 01:49
Were you able to reproduce with uTP disabled in test client too?
Otherwise this bug might be a sideeffect of another bug that I am fixing with https://github.com/qbittorrent/qBittorrent/pull/7974

**Comment by arvidn** [comment] 2017-12-05 23:46
adding utp sockets to the local peer class does sound suspicious. I suppose choking is a form of rate limiting, but it doesn't really make sense to unchoke all utp peers.

**Comment by arvidn** [comment] 2017-12-08 08:51
I'm pretty sure this is the fix: https://github.com/arvidn/libtorrent/pull/2596
However, I haven't had time to write a test yet, and maybe I'll do that in master since it's a bit easier.
Any chance someone could try it?

**Comment by Nemo-qB** [comment] 2017-12-11 01:04
Hopefully it will get fixed. I prefer 4-6 slots while downloading so the leechers get a decent speed. Low upload speeds results in slow downloading speed from these peers because of this problem.

**Comment by arvidn** [comment] 2017-12-11 13:40
fixed in RC_1_1 now.

**Closed by arvidn** 2017-12-11 13:40 UTC
Labels: bug

**Comment by kef71** [comment] 2017-12-18 04:51
Confirmed. Neither "Global maximum number of upload slots" or "Maximum number of upload slots per torrent" is working. Linux Mint 18.3, qBitTorrent (4.0.2.99201712180333-6226-13210b3ubuntu16.04.1), libtorrent (1.1.5+git20171217.d52763805c+patched-configure-1ppa1~xenial1).

**Comment by arvidn** [comment] 2017-12-18 07:12
@kef71 did that build include the fix?

**Comment by kef71** [comment] 2017-12-18 07:43
@arvidn I doesn't look like it did. I am uncertain. If I understand correctly this was fixed in 1.1.6 RC_1_1 and the version number is 1.1.5+

**Comment by sledgehammer999** [comment] 2017-12-18 12:39
>libtorrent (1.1.5+git20171217.d52763805c+patched-configure-1ppa1~xenial1).

This uses git commit d52763805c (aka latest RC_1_1).

Also the v4.0.3 windows release uses the same version. Does anyone from Windows say if it is fixed or not?

**Comment by kef71** [comment] 2017-12-18 15:27
Not fixed in Windows either.

**Comment by ssiloti** [comment] 2017-12-18 16:19
qBittorrent also needs to be patched. See `Session::configurePeerClasses` which adds a filter to assign the local class to UTP connections when UTP rate limiting is enabled.

**Comment by Nemo-qB** [comment] 2017-12-19 23:26
Can confirm that it isn't fixed yet with v4.0.3 release.

**Comment by sledgehammer999** [comment] 2017-12-20 01:36
@ssiloti damn it, I forgot about it.
In any case, https://github.com/qbittorrent/qBittorrent/pull/7974 should take of this problem too.
Could you take a look at the diff? @arvidn too if you please.
I just hope that there won't be any internal libtorrent side effects now that I completely disassociate utp connections from the global and local classes.
