### ISSUE TITLE
libtorrent 1.1.x/RC_1_1 - UPnP issues

### ISSUE THREAD

**Issue by Seeker2** [arvidn/libtorrent#2481] opened 2017-10-25 16:32 UTC
UPnP/NAT-PMP cannot be turned off (for listening port)  https://github.com/qbittorrent/qBittorrent/issues/7144
[3.4.0] qBittorrent still attempts UPnP port mapping when option is disabled  https://github.com/qbittorrent/qBittorrent/issues/7338

Minor additional issue with UPnP:
UPNP doesn't use configured Optional IP Address  https://github.com/qbittorrent/qBittorrent/issues/6702

**Comment by aldenml** [comment] 2017-10-25 17:57
Is the `session` object created with the right `settings_pack` in the constructor?

**Comment by Seeker2** [comment] 2017-10-25 18:11
I hope arvidn and/or someone else can answer that, because I only run pre-compiled installers of qBT and Deluge.

**Comment by arvidn** [comment] 2017-10-27 09:21
For the first issue you mention, the log you post in the qbt issue only mentions MAT-PMP ports being forwarded.

nat-pmp is disabled by setting ``settings_pack::enable_natpmp`` to false. is qbt for sure doing that? The code in libtorrent is pretty simple, the object is only ever created under the condition that this setting is true.

I have a feeling that t the issue is in qbt failing to honor this setting in the gui

**Comment by asturel** [comment] 2017-10-27 15:22
https://github.com/qbittorrent/qBittorrent/blob/master/src/base/net/portforwarder.cpp#L130

**Comment by asturel** [comment] 2017-10-27 16:31
https://github.com/qbittorrent/qBittorrent/blob/master/src/base/bittorrent/session.cpp#L526 ?

**Comment by aldenml** [comment] 2017-10-27 16:35
At this line: https://github.com/qbittorrent/qBittorrent/blob/master/src/base/bittorrent/session.cpp#L444, I don't see that the port mapping settings are set in the pack, could that be the problem?

**Comment by asturel** [comment] 2017-10-27 16:40
yeah probably, but i think setEnabled should be used to follow qBitorrent's code guideline (?) since they have some output for other settings too.. (similar to upnp/nat-pmp):

2017. 10. 25. 0:06 - Embedded Tracker [OFF]
2017. 10. 25. 0:06 - Encryption support [ON]
2017. 10. 25. 0:06 - Anonymous mode [OFF]

and PortForwarder::start() / stop() have the same logic

**Comment by aldenml** [comment] 2017-10-27 16:42
sorry, don't understand?

**Comment by asturel** [comment] 2017-10-27 16:46
Yeah, the port mapping settings are missing, I just thought calling PortForwarder::setEnabled(bool) makes more sense (instead of doing pack.setXXXX) since 'setEnabled' does the logging + libtorrent settings pack already

**Comment by aldenml** [comment] 2017-10-27 16:48
I understand now, well, if you start the setting with the default value, you will get the service(s) started, and then stopped (if `setEnabled(false)`). Same applies for all sort of internal features, specially the DHT. If you call `apply_settings` with no value changed, then nothing is executed.

**Comment by Seeker2** [comment] 2017-10-27 21:11
I tested qBitTorrent and uTorrent on my wireless gateway (modem-router-wifi device) and determined that NAT-PMP didn't trigger anything according to the gateway's logs but UPnP did. The gateway explicitly listed UPnP as something I could enable and disable, but no mention of NAT-PMP, so no surprise there. Also, uTorrent let me test NAT-PMP and UPnP separately, like qBT should.

In short, qBT v3.4.0beta2 even when UPnP was disabled caused a UPnP entry in the gateway like this:
[IGD][3176]: Add Port mapping :55500 to 10.0.0.12:55500 	2017/10/27 04:31:53	Notice 
uTorrent did not when it had UPnP disabled.

**Comment by arvidn** [comment] 2017-10-27 21:41
libtorrent lets you enable/disable nat-pmp and UPnP independently. Also, it seems like there's some evidence that this problem fundamentally is that qBittorrent doesn't disable UPnP and NAT-PMP when that checkbox is unchecked (i.e. it assumes that the default is off). Well, with libtorrent-1.1, the default is on, so the session constructor needs to have a settings_pack passed to it that disables them (or enables them if that qbt setting is enabled)

**Comment by arvidn** [comment] 2017-10-27 21:42
I'm inclined to close this ticket

**Comment by arvidn** [comment] 2017-10-27 21:45
i suppose there is the other issue of poor support for multi-homed machines. UPnP currently attempts to broadcast on all interfaces (iirc), whereas NAT-PMP only sends to the gateway of the default route. this is an issue, should we keep this ticket to cover that? if so, would you mind renaming and editing it?

**Comment by Seeker2** [comment] 2017-10-27 22:20
There is also this side-issue:
UPnP doesn't use configured Optional IP Address
https://github.com/qbittorrent/qBittorrent/issues/6702
...In which case UPnP broadcast on all interfaces is probably not the right way to go.

**Comment by arvidn** [comment] 2017-10-27 23:14
yeah, that's what i referred to as "poor support for multi-homed machines".

**Comment by Seeker2** [comment] 2017-11-05 20:24
It's probably a bad idea for someone using a proxy or VPN to have "regular" UPnP or NAT-PMP port forward their router.

Does either UPnP or NAT-PMP try to tunnel through the VPN (or proxy, if applicable) to forward their gateway?

**Comment by arvidn** [comment] 2017-11-05 21:30
no, NAT-PMP nor UPnP attempt to go through a proxy (there are actually several reasons that's hard, if not impossible).

If one intends to run all traffic via a proxy, then it does not make sense to have either NAT-PMP or UPnP enabled.

even when going through a VPN, UPnP will still (iirc) try to map ports on all interfaces. NAT-PMP always only try to map on the default gateway, which should be correct on a VPN.

**Comment by Seeker2** [comment] 2017-11-05 23:26
...so another reason to separate UPnP and NAT-PMP enabling in qBitTorrent.

**Comment by arvidn** [comment] 2017-11-05 23:43
well, I would not imagine any normal VPN setup to actually implement any NAT-PMP port forwarding

**Comment by arvidn** [comment] 2017-11-28 23:09
@Seeker2 actually, upnp binding to the correct interface was fixed here: https://github.com/arvidn/libtorrent/pull/1985

**Comment by sledgehammer999** [comment] 2017-12-03 19:17
IMO, this should be closed. As far as I can tell this was fixed by https://github.com/qbittorrent/qBittorrent/pull/7657

**Closed** 2017-12-03 19:52 UTC
