### ISSUE TITLE
assertion failed, pe->outstanding_read == 1

### ISSUE THREAD

**Issue by ssiloti** [arvidn/libtorrent#524] opened 2016-03-05 20:03 UTC
I've hit this a few times now while testing 2bd6ad9974491de782421809cd455f278d651491. I've managed to capture it in gdb with disk_io_thread logging and full event logging. This is on linux with deluge and I've got the disk cache enabled for now.

[logs and backtraces](https://github.com/arvidn/libtorrent/files/159998/assert.outstanding_read.eq.1.zip)

@zywo has reported the same assertion in #498.

**Comment by arvidn** [comment] 2016-03-05 20:20
yeah, I actually managed to hit it in gdb as well (no disk logging though). It appears to only happen with a disk cache size set to -1 (i.e. auto). This setting have a number of issues with it. Some of them have been fixed in https://github.com/arvidn/libtorrent/pull/523

I haven't had time to analyze it yet. the expected invariant for that flag is that any disk job in the disk queue is supposed to set this flag, and have it still be set when it get executed. The reason is for subsequent jobs for the same piece to instead be hung off of the per-piece job queue, instead of the main job queue. This is to ensure jobs on the same piece go to the same disk thread, and are serialized.

**Comment by arvidn** [comment] 2016-03-05 21:36
I'm pretty sure this happens because of bug related to treating negative cache_size as "auto".  When issuing a read job, a negative cache_size was interpreted as "don't use the cache", which would not allocate a piece where it could set this flag.

Once the job was picked up by one of the disk threads, the piece entry in the cache may have been created without this flag, and the negative cache size is interpreted as using the cache at this point, so we expected there to be a piece with this flag set.

The basic bug of misinterpreting the cache_size setting has been fixed in #523. However, there's still a fundamental issue with interpreting this global setting twice, in separate threads at different times, and require it to be the same both times. If this setting changes from or to 0 for instance (disabling the cache), any outstanding read job will have the exact same issue.

I think the proper fix to this is to record in the job whether it's using the cache or not.

**Comment by arvidn** [comment] 2016-03-05 22:17
pushed update to #523.

**Comment by ssiloti** [comment] 2016-03-06 02:48
I haven't seen any asserts with #523.

**Comment by ssiloti** [comment] 2016-03-06 03:11
Of course right after I say that I hit the pe->outstanding_read == 1 assert again. I think the key is that I set cache_size to 0 to test with the disk cache disabled. I changed the cache size before starting any torrents so it's not the edge case arvid described.

**Comment by arvidn** [comment] 2016-03-06 04:17
I could reproduce this by toggling the cache on and off while downloading. I'm pretty confident my latest patch fixes it. thanks for testing!

**Closed** 2016-03-06 21:23 UTC
