### ISSUE TITLE
Some tests fail on big endian architectures

### ISSUE THREAD

**Issue by lgbaldoni** [arvidn/libtorrent#4932] opened 2020-08-02 08:41 UTC
**Please provide the following information**

> libtorrent version (or branch):

RC_2_0

> platform/architecture:

openSUSE Factory ppc64BE and s390x

> compiler and compiler version:

gcc 10.1.1

> please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Build the project normally and then launch `ctest --output-on-failure --force-new-ctest-process --verbose --exclude-regex test_upnp --parallel 1`.

Log snippets for [ppc64](https://github.com/arvidn/libtorrent/files/5011864/libtorrent20rc2_ppc64_tests.txt) and [s390x](https://github.com/arvidn/libtorrent/files/5011865/libtorrent20rc2_zSystems_tests.txt).

**Comment by arvidn** [comment] 2020-08-02 10:00
thanks, this is an excellent catch! (now, if only there was some free CI provider that could run on PPC).

out of the 3 tests that fail, at least the last one seems to be testing an SSE specific instruction without properly conditioning the test on running with SSE support. That will be an easy fix.

I'll get back with a fix soon!

**Comment by arvidn** [comment] 2020-08-02 11:40
the both the CRC and the `classify_prefix()` issues are not trivial unfortunately. I may need to come up with a way to reproduce this myself. I held on to my PowerMac G5 for a long time, to be able to test on it. But it turns out I no longer have any big-endian hardware. maybe QEMU is my best bet.

I'm a bit curious though; since the CRC test failed, I would expect at least the DHT node id test to fail as well, but it isn't for you. Are you running `test_dht` as well?

**Comment by arvidn** [comment] 2020-08-02 11:40
I'll set the milestone to 1.2.8 for now. I think some of the fixes I have should be back-ported as well

**Comment by lgbaldoni** [comment] 2020-08-02 12:18
> the both the CRC and the classify_prefix() issues are not trivial unfortunately. I may need to come up with a way to reproduce this myself. I held on to my PowerMac G5 for a long time, to be able to test on it. But it turns out I no longer have any big-endian hardware. maybe QEMU is my best bet.

I have used QEMU myself debug ppc and arm troubles. Not the funniest experience, but it worked.

> I'm a bit curious though; since the CRC test failed, I would expect at least the DHT node id test to fail as well, but it isn't for you. Are you running test_dht as well?

As you can see at the bottom of the log, the failing tests are: crc32, dht and ffs.

**Comment by aldenml** [comment] 2020-08-02 17:39
maybe something can done in travis similar to the arm setup

**Comment by aldenml** [comment] 2020-08-03 00:36
Not a fix, just to add tests to the BE related fixes: https://github.com/arvidn/libtorrent/pull/4937

**Comment by arvidn** [comment] 2020-08-04 11:18
I feel pretty confident I understand 2 out of the 3 issues, but they don't seem to reproduce in the qemu environment on travis, so I can't know for sure. Here are those fixes though, I will back port this to 1.2.8 and to 2.0 once this lands. https://github.com/arvidn/libtorrent/pull/4940

**Comment by lgbaldoni** [comment] 2020-08-04 13:20
Using the `fix-tests-endian` branch (the patches did not apply cleanly to RC_2_0). Could not build on ppc64 due to OBS troubles, but whilst waiting for it to be repaired, [here](https://github.com/arvidn/libtorrent/files/5022272/libtorrent_fix-endian_s390x.txt) is the result for s390x. test_ffs is no longer a problem, but as you can see test_crc32
and test_dht still are and now test_peer_priority is failing as well.

In addition to that, I regret to announce that now test_flags [fails](https://github.com/arvidn/libtorrent/files/5022280/libtorrent_fix-endian_i586.txt) on i586.

> I feel pretty confident I understand 2 out of the 3 issues, but they don't seem to reproduce in the qemu environment on travis

Any chance there's a difference in dependencies or environment variables? I'm on boost 1.71 if that could be a factor.

**Comment by arvidn** [comment] 2020-08-04 13:49
I would have expected `test_peer_priority` as well as one other test in `test_dht` to fail, since they depend in `crc32` working correctly. One step forward, though, is that the CRC32 test failures are now clearly the results being byte-swapped.

I attempted to fix this by introducing `little_endian_to_host()` and passed the return crc32 value through that. Perhaps something is making that not work right.

**Comment by arvidn** [comment] 2020-08-04 13:51
here: https://github.com/arvidn/libtorrent/pull/4940/files#diff-f411edb3320d69226127da426bd459bcR70

if neither of `BOOST_ENDIAN_BIG_BYTE` and `BOOST_ENDIAN_LITTLE_BYTE` is defined, there would be a compilation error. Surely the little endian define can't be set on s390x.

**Comment by lgbaldoni** [comment] 2020-08-04 16:29
I triggered a rebuild and now the number of test errors has increased. I'm sending you the [full build log](https://github.com/arvidn/libtorrent/files/5023286/libtorrent_fix-endian_s390x_full.txt), perhaps you'll notice some detail I might have missed.

(please disregard any network-related failure for that's most likely a problem on my end)

**Comment by arvidn** [comment] 2020-08-08 06:34
I'm not sure what the best next step is. my fixes so far have landed in RC_1_2, RC_2_0 and master. As far as I can tell, the crc32 issue the root cause of all failures in your latest log (apart from some flaky tests).

The issue is that the `crc32c()` functions (as well as the optimized `crc32c_32()`) return the digest byte-swapped. I added a function to swap it, but somehow that didn't solve it. I can think of a few possibilities:

1. your build (for some reason) did not include that patch
2. when building on your machines, libtorrent/boost fail to detect and set `BOOST_ENDIAN_BIG_BYTE`, so the byte swapping function isn't applied. I tried to rule this out though, but ensuring that it's set on the QEMU environment on travis. Where I successfully asserted that this *is* working.
3. Some other crc32c code path is run on your builds that I'm not expecting (although, I inserted the call to `aux::little_endian_to_host()` on all paths).

**Comment by lgbaldoni** [comment] 2020-08-08 08:08
Like I said, I was building from the `fix-tests-endian` branch. Will try again with RC_2_0 and report back.

**Comment by lgbaldoni** [comment] 2020-08-08 10:31
[Here's](https://github.com/arvidn/libtorrent/files/5045110/libtorrent-rasterbar-RC_2_0-20200807.e7d3e3b01.tar.gz) the build logs.
As you can see, test_crc32, test_dht and test_peer_priority are the ones that still fail.

This time I built from the RC_2_0 branch: please let me know if I should test master instead.

**Comment by lgbaldoni** [comment] 2020-08-10 10:27
No change with https://github.com/arvidn/libtorrent/commit/0b6447084504fd8e503c68fb75e639e750e9c7eb. Big endian still fails in the same way and i586 fails for test_flags.

Is there anything I can do to help?

**Comment by arvidn** [comment] 2020-08-10 10:39
the `test_flags` test is flaky. I will need to look into fixing it, but it's an issue with the test itself, I'm pretty sure.

as for the CRC issue. If I make another attempt in a PR, would it be a lot of work for you to trigger a build from that?

**Comment by lgbaldoni** [comment] 2020-08-10 11:06
> as for the CRC issue. If I make another attempt in a PR, would it be a lot of work for you to trigger a build from that?

Not at all.

**Comment by lgbaldoni** [comment] 2020-08-10 16:08
Also I finally have a ppc64 shell where I can test things interactively if it's of any use.

**Comment by arvidn** [comment] 2020-08-13 23:51
I'm pretty sure this patch fixed it!
https://github.com/arvidn/libtorrent/pull/4979

**Comment by lgbaldoni** [comment] 2020-08-14 06:26
PR https://github.com/arvidn/libtorrent/pull/4979 indeed fixes the tests for s390x and ppc64, but now test_dht on i586 is [failing](https://github.com/arvidn/libtorrent/files/5072943/libtorrent-rasterbar2-test_dht_i586.txt) :cry: 

Strangely enough, armv7l is 32bit too, but test_dht doesn't fail as opposed to https://github.com/arvidn/libtorrent/issues/4985.

Will try rebuilding to see if it might be an intermittent problem.

**Comment by arvidn** [comment] 2020-08-14 06:39
> PR #4979 indeed fixes the tests for s390x and ppc64, but now test_dht on i586 is [failing](https://github.com/arvidn/libtorrent/files/5072943/libtorrent-rasterbar2-test_dht_i586.txt) 😢

That test is flaky. If you run it again I think it will pass.
I haven't had time to look into fixing the test properly.

**Comment by lgbaldoni** [comment] 2020-08-14 07:44
Yes, I ran the build another two times and it didn't fail anymore.

**Comment by arvidn** [comment] 2020-08-14 08:43
I think this has been addressed now. Thanks for reporting and helping with tests!

**Closed by arvidn** 2020-08-14 08:43 UTC
