### ISSUE TITLE
fast_download session_settings preset

### ISSUE THREAD

**Issue by max-posedon** [arvidn/libtorrent#257] opened 2015-11-09 17:06 UTC
It will be nice to have fast_download preset, for cases when downloading time should be minimized.

For example, my case is following
- download one torrent file with one file inside, size is about 1 - 5 GB
- a lot of torrent seeders in datacenter prepared to distribute this file
- a torrent tracker tweaked for my torrent seeders to have higher priority then others
- file uploaded to the high speed popular CDN, and link added to torrent as a web seed
- for some users there is very fast seeders in local network

I would like to minimize download time for user, money which I'm paying from traffic from seeders or CDN is less important. Right now download behavior isn't best I think
- sometimes at the end, speed going down to almost 0 with downloading last (or few last) peaces
- I would like torrent to prefer faster seeders, e.g. may be even kicking slower ones and try to switch to fasters
- use webseeds if CDN gives better speed 

Settings which I use is following

``` cpp
settings.announce_to_all_trackers = true;
settings.announce_to_all_tiers = true;
settings.user_agent = TORRENT_CLIENT_NAME;
settings.auto_upload_slots_rate_based = true;
settings.optimize_hashing_for_speed = false;
settings.disk_cache_algorithm = session_settings::largest_contiguous;
settings.allow_multiple_connections_per_ip = true;
settings.min_announce_interval = 30;
settings.local_service_announce_interval = 30;
settings.close_redundant_connections = true;
settings.max_rejects = 10;
settings.file_pool_size = 20;
settings.request_timeout = 10;
settings.peer_timeout = 20;
settings.inactivity_timeout = 20;
settings.active_limit = 2000;
settings.active_seeds = 2000;
settings.auto_upload_slots = false;
settings.send_buffer_watermark = 5 * 1024 * 1024;
settings.max_failcount = 2;
settings.urlseed_wait_retry = 60;
settings.ban_web_seeds = false;
settings.smooth_connects = false;
settings.ignore_limits_on_local_network = false;
```

What will be the best session_settings options to handle this use case?

**Comment by arvidn** [comment] 2015-11-11 05:54
There is a fundamental problem with "prefer faster peers". Let's consider two main scenarios:

1. you are not saturating your down-link because the peers you're downloading from have a combined upload capacity lower than your download capacity
2. you are saturating your down-link and there is no possibility to download at any higher rate.

If you know which one of those modes you're in, most of the problem is solved. It turns out, it's quite hard to know with certainty which mode you're in.

In mode (1) you want to connect to as many peers as possible and request as much as possible from as many as possible, and comparing the download rates you're getting from different peers make sense.

In mode (2), you want to request from fewer peers (but not too few to leave mode (2)). If one peer is slow, it may be because some other peer started sending to you. The rates you're getting is now a zero-sum game. trying to compare which peer is faster than the other is meaningless, because all you're measuring is noise and your download capacity.

Another issue is that you can easily transition back and forth between mode (1) and (2), especially if you have unstable heuristics.

Now, the end-game mode is especially interesting (which is what you're talking about). You want to predict whether or not it would be beneficial to disconnect a peer in favor of requesting a block from another peer (say, a web seed).

If you're in mode (2), you're worse off doing that. But in mode (1) you should probably stay connected to both. One additional complication with end game mode is that it's the same data you're downloading. If you decide to request the last piece from every peer (because you assume mode (1)), you will probably get the shortest download time, unless that download bandwidth throws you into mode (2) of course. If you assume you're in mode (2), you want to stay with the current peers, and not double-request anything. Every redundant byte you download with push out the completion time that much more.

Here's a related blogpost: http://blog.libtorrent.org/2011/11/block-request-time-outs/

You can configure the end-game mode more aggressive, but beware that you're sacrificing performance for people in mode (2) when doing so. See http://libtorrent.org/reference-Settings.html#strict_end_game_mode

**Comment by arvidn** [comment] 2015-11-11 05:56
That said, it's probably possible to improve specific situations with simple heuristics. If the heuristics becomes even slightly complicated, it's very difficult to understand the consequences with certainty.

**Comment by max-posedon** [comment] 2015-11-11 08:14
Thank you, it means there is nothing wrong in my settings. I'll try to do A/B end_game_mode in my case. If found smth interesting, will share results.

**Comment by Falcosc** [comment] 2016-12-26 17:23
I guess we could close it because everthing is already documented.

**Closed** 2017-01-11 00:23 UTC
