### ISSUE TITLE
Force terminating sockets results in excessive cpu utilization 

### ISSUE THREAD

**Issue by senposage** [arvidn/libtorrent#2977] opened 2018-04-26 16:18 UTC
**Please provide the following information**

libtorrent version (or branch):
1.0x+ and probably older 
platform/architecture:
windows
compiler and compiler version:
n/a
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

use any client using libtorrent and force terminate the  TCP socket 

client immediately starts consuming 20 to 30% more cpu then normal  
so far I have reproduced this with qbittorrent,deluge,transmission-win

**Comment by senposage** [comment] 2018-04-27 01:38
download TCPview and force terminate the socket of any application using libtorrent
and yes as far as I am aware its all versions of libtorrent from 1.0 up I don't have anything older to test tho

**Comment by Seeker2** [comment] 2018-04-27 09:11
The problem has probably been around for awhile (October 18, 2016):
https://qbforums.shiki.hu/index.php/topic,3982.msg23615.html#msg23615

My speculation on what's happening:
https://github.com/arvidn/libtorrent/issues/2020#issuecomment-314712637

**Comment by yegors** [comment] 2018-05-09 01:41
You can replicate the issue with this: https://www.nirsoft.net/utils/cports.html

**Comment by arvidn** [comment] 2018-05-09 11:00
using tcp_killer.py I cannot reproduce this on mac. is there any chance anyone could get a verbose log and/or a profile (from a build with debug information) of when this issue happens?

**Comment by arvidn** [comment] 2018-05-19 14:49
I've been trying to reproduce this on mac in `RC_1_1` and `master`, but I'm unable to. The original report says it happens in libtorrent 1.0.x, does anyone know if this still happens in later version? Specifically, libtorrent 1.1.7.

Does this only happen on windows? If so, could someone please make a release build with debug symbols of libtorrent and profile it under this condition (for instance under [very sleepy](http://www.codersnotes.com/sleepy/))

**Comment by Seeker2** [comment] 2018-05-30 13:46
@arvidn 
I only know the problem happens on Windows XP Pro SP3 and Win 7.

**Comment by senposage** [comment] 2018-05-30 16:07
sorry completely forgot about this
yes I can reproduce it on 1.1.7(qbittorrent latest uses this version) I am assuming yes on windows because linux/mac os handles socket termination a lot better then win (untested)

**Comment by arvidn** [comment] 2018-05-30 21:16
@senposage would it be possible for you to profile the CPU usage, with a build with debug information?

**Comment by senposage** [comment] 2018-05-30 23:54
I don't currently have a build envro for qbt 
if somebody can throw a debug build up with symbols I can post whatever debug information you need

**Comment by arvidn** [comment] 2018-05-31 00:41
ideally it should be a release build with debug symbols, to more accurately capture the part that uses a lot of CPU, and not just the parts that are poorly optimized

**Comment by Seeker2** [comment] 2018-05-31 11:27
I'd like that build as well, although I'm certainly not set up to build it myself.
I'm seeing qBitTorrent CPU usage go over 70% on my Intel i5 650 3.2 Ghz cpu.

**Comment by arvidn** [comment] 2018-09-28 23:18
I recently landed this patch. does it affect this issue? https://github.com/arvidn/libtorrent/pull/3312

**Comment by Seeker2** [comment] 2020-03-06 00:43
Problem still occurs on qBitTorrent v4.2.1 using libtorrent v1.2.3.0 on Windows 7 Pro.

**Comment by arvidn** [comment] 2020-03-06 08:10
There's nothing I can do about this without being able to reproduce it or more information

**Comment by UrbanPotato** [comment] 2020-03-06 08:46
ok so you can replicate this issue as mentioned in 
https://github.com/arvidn/libtorrent/issues/2977#issuecomment-384701936

install the latest qbittorrent release. run cports as admin force close one of the ports
cpu usage jumps to 25 to 30%

**Comment by Seeker2** [comment] 2020-03-06 22:22
Under windows dos prompt (CMD) the NETSTAT command (with -n for showing them as numbers) can at least show you the 2 spurious ESTABLISHED connections that qBitTorrent makes on IPv4 address 127.0.0.1 -- which typically uses 2 port numbers in a row, like 45039 and 45040...almost always in the ephemeral range.

It is the breaking of those connections that causes qBitTorrent to immediately max out a cpu core (or virtual core, as the case may be on an Intel processor using hyperthreading).

Breaking those connections in any way is extremely likely to trigger this CPU usage jump that remains until qBitTorrent is closed.
TCP view, which is hosted and owned by Microsoft, can be used to break TCP connections...and it is what I and others have used to test this CPU usage jump.
I have heard that people using VPNs or proxies that go down may also be triggering the CPU usage jump.

**Comment by arvidn** [comment] 2020-03-07 17:42
That socket is internal to boost.asio and used to wake up iocp to add new events to wait for, called "socket_interrupter". as far as I can tell, asio does not handle the socket going away from under its feet. If you think it should, please file a bug against [asio](https://github.com/chriskohlhoff/asio).

Personally, I'm not sure it makes sense to fix that. If it hurts, don't do it.

**Comment by Seeker2** [comment] 2020-03-07 21:35
Why disconnecting a couple of "barely active" (checked via Process Monitor app) established connections on 127.0.0.1 should max out a CPU core is disconcerting in the first place.
Does asio have a tight loop that on no response keeps resending?

I've seen reports of a dropping VPN or proxy that also causes high CPU usage, so this may not be only a case of self-inflicted pain.

I initially discovered this problem years ago when manually disconnecting peers+seeds with qBitTorrent and other BT apps.

I've run across a lot of unexpected pain when using qBitTorrent and Deluge which also uses libtorrent, so "don't do it" is probably good advice.

**Comment by rafi-d** [comment] 2020-03-08 07:19
> 
> 
> That socket is internal to boost.asio and used to wake up iocp to add new events to wait for, called "socket_interrupter". as far as I can tell, asio does not handle the socket going away from under its feet. If you think it should, please file a bug against [asio](https://github.com/chriskohlhoff/asio).
> 
> Personally, I'm not sure it makes sense to fix that. If it hurts, don't do it.

You might want to try update to: https://www.boost.org/users/history/version_1_72_0.html 
Who knows, this might have been fixed with some socket related fixes mentioned in there...

**Comment by arvidn** [comment] 2020-03-08 11:30
On windows 10, I can only reproduce this issue by terminating the interruptor socket. No other socket causes any problem. Testing libtorrent `RC_1_2` (soon to be 1.2.5).

I'm tempted to close this ticket for two reasons:

1. I haven't heard compelling arguments why libtorrent should support users terminting these "interrupt_socket" connections.

2. It's fundamentally an implementation detail in asio with its iocp back-end, and I think a limitation in windows (at least some version of it) for not having an eventfd for using with iocp. But, I'm not the expert on this, so I may be wrong.

**Comment by rafi-d** [comment] 2020-03-08 11:55
> 
> I'm tempted to close this ticket for two reasons:
> 
>     1. I haven't heard compelling arguments why libtorrent should support users terminting these "interrupt_socket" connections.
> 
@arvidn 
You don't really believe people are doing it "for fun"... more likely just as a mean to reproduce what they believe might be the root cause for possibly related issues, like VPN related:
https://github.com/qbittorrent/qBittorrent/issues/8740#issuecomment-381447333

> I can only reproduce this issue by terminating the interruptor socket. 
Was this also happening with latest asio - v1.72?

**Comment by arvidn** [comment] 2020-03-08 13:45
The ticket about putting the computer to sleep is a very compelling use case. That seems to be reason to treat this as a bug in asio.

> Was this also happening with latest asio - v1.72?

I was testing with boost 1.71.0, but I would be surprised if there is *any* development on the interrupt sockets.

**Comment by rafi-d** [comment] 2020-03-08 14:29
Well, you are more them welcome to  comment in this bug-report ... https://github.com/boostorg/asio/issues/330 

Plus there is no harm in confirming with the latest  release, since they will expect it...

**Comment by rafi-d** [comment] 2020-03-09 06:41
Great, seems like you have succeeded to reproduce & w/a (fix) it in here  ( chriskohlhoff/asio#461 )...

Since that project is not updating release that often, will you include your own fix (1.7.2 mod?) with libtorrent/qBT for now, till they will update asio in there?

**Comment by arvidn** [comment] 2020-03-09 10:03
I don't ship asio with libtorrent, but qbittorrent does

**Comment by rafi-d** [comment] 2020-03-09 17:01
Can you share the code/info of your suggested fix with them?

**Comment by Seeker2** [comment] 2020-03-09 22:41
Deluge shares with qBitTorrent the 127.0.0.1 established connections and CPU spike when they're closed, but I did not find that it uses asio or boost.asio.

**Comment by arvidn** [comment] 2020-03-09 23:55
libtorrent uses boost.asio (so Deluge does indirectly). boost.asio is generated from asio when boost is released.

**Comment by rafi-d** [comment] 2020-03-11 15:45
> 
> 
> libtorrent uses boost.asio (so Deluge does indirectly). boost.asio is generated from asio when boost is released.

I don't get it... if there is an issue with asio, boost.asio should have it as well, so libtorrent will inherit it from using <-boost<-asio , right? This is from boostorg repo (seems a year old, with the same error you've fixed):
https://github.com/boostorg/asio/blob/develop/include/boost/asio/detail/impl/socket_select_interrupter.ipp

**Comment by arvidn** [comment] 2020-03-11 15:54
@rafi-d that's correct. I was responding to Seeker2, saying that Deluge also uses asio.

**Comment by rafi-d** [comment] 2020-03-11 16:00
So, in order for qBT to have it fixed can't you just add to your release  (temporarily, till asio fill have a new release)  this single file, patched,  so to have it available to whoever uses libtorrent, such as qBT?

**Comment by arvidn** [comment] 2020-03-11 16:29
https://github.com/arvidn/libtorrent/issues/2977#issuecomment-596436512

**Comment by arvidn** [comment] 2020-03-13 11:23
I defer this ticket to the asio one: https://github.com/chriskohlhoff/asio/issues/461

**Closed by arvidn** 2020-03-13 11:23 UTC
